// Pass B: append 108 Infection Control questions (ids 661–768) to questions.js
import { readFileSync, writeFileSync } from 'fs'

const FILE = new URL('../src/questions.js', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')

const T  = 'Sanitation & Infection Control'
const TE = 'Saneamiento y Control de Infecciones'
const P  = 'Infection Control'
const PE = 'Control de Infecciones'

const questions = [
  { id:661, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"OSHA's Bloodborne Pathogen Standard applies to cosmetology salons because:",
    question_es:"El estándar de patógenos de transmisión sanguínea de OSHA se aplica a los salones de cosmetología porque:",
    options:["Cosmetologists regularly handle blood products","There is potential occupational exposure to bloodborne pathogens through accidental cuts","Salons are classified as medical facilities","All workplaces must follow medical safety regulations"],
    options_es:["Los cosmetólogos manejan regularmente productos de sangre","Existe una posible exposición ocupacional a patógenos de transmisión sanguínea a través de cortes accidentales","Los salones están clasificados como instalaciones médicas","Todos los lugares de trabajo deben seguir las regulaciones de seguridad médica"],
    correct:1,
    explanation:"Any workplace where employees may be exposed to blood must comply with OSHA's Bloodborne Pathogen Standard, including cosmetology salons." },

  { id:662, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"When a client is accidentally cut and bleeds during a service, the FIRST action should be:",
    question_es:"Cuando un cliente se corta accidentalmente y sangra durante un servicio, la PRIMERA acción debe ser:",
    options:["Continue the service and clean up blood afterward","Stop the service, don gloves, and apply standard precautions immediately","Ask the client to step outside","Wipe the blood with a dry towel and continue"],
    options_es:["Continuar el servicio y limpiar la sangre después","Detener el servicio, ponerse guantes y aplicar precauciones estándar de inmediato","Pedir al cliente que salga","Limpiar la sangre con una toalla seca y continuar"],
    correct:1,
    explanation:"Standard precautions must be applied immediately upon any blood exposure; gloves must be worn before handling blood-contaminated items." },

  { id:663, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Used razor blades and sharp implements must be disposed of in:",
    question_es:"Las hojas de afeitar usadas y los implementos cortantes deben desecharse en:",
    options:["The regular waste bin","A puncture-resistant sharps container","A paper bag","The salon's utility sink drain"],
    options_es:["El basurero regular","Un contenedor de objetos punzocortantes resistente a perforaciones","Una bolsa de papel","El desagüe del lavabo de servicio del salón"],
    correct:1,
    explanation:"Sharps that contact skin must be disposed of in puncture-resistant sharps containers to prevent injury and contamination." },

  { id:664, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which type of hepatitis is most efficiently transmitted through blood in a salon setting?",
    question_es:"¿Qué tipo de hepatitis se transmite más eficientemente a través de la sangre en un entorno de salón?",
    options:["Hepatitis A","Hepatitis B","Hepatitis C","Hepatitis D only"],
    options_es:["Hepatitis A","Hepatitis B","Hepatitis C","Solo hepatitis D"],
    correct:1,
    explanation:"Hepatitis B is far more resilient and transmissible through blood contact than HIV, making it the most significant bloodborne pathogen concern in salons." },

  { id:665, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"After a blood spill in a salon, the correct protocol includes:",
    question_es:"Después de un derrame de sangre en un salón, el protocolo correcto incluye:",
    options:["Rinsing with water only and returning to work","Cleaning with soap and water, applying an EPA-registered disinfectant, and documenting the incident","Calling emergency services for every blood incident","Only reporting the incident verbally to the salon owner"],
    options_es:["Enjuagar solo con agua y volver al trabajo","Limpiar con agua y jabón, aplicar un desinfectante registrado en la EPA y documentar el incidente","Llamar a servicios de emergencia por cada incidente de sangre","Solo informar el incidente verbalmente al propietario del salón"],
    correct:1,
    explanation:"Blood spills require soap-and-water cleaning, EPA-registered disinfection of the area, and written documentation of the incident." },

  { id:666, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A 'hospital-grade' disinfectant is one that is EPA-registered and proven effective against:",
    question_es:"Un desinfectante de 'grado hospitalario' es aquel que está registrado en la EPA y ha demostrado ser efectivo contra:",
    options:["Only common bacteria","Mycobacterium tuberculosis (tuberculocidal) and a broad spectrum of pathogens","Only household germs","Only mold and mildew"],
    options_es:["Solo bacterias comunes","Mycobacterium tuberculosis (tuberculocida) y un amplio espectro de patógenos","Solo gérmenes domésticos","Solo moho y hongos"],
    correct:1,
    explanation:"Hospital-grade (tuberculocidal) disinfectants are EPA-registered and proven effective against a broad spectrum of pathogens including mycobacterium tuberculosis." },

  { id:667, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Mycobacterium tuberculosis is used as the benchmark for disinfectant classification because:",
    question_es:"El Mycobacterium tuberculosis se usa como referencia para la clasificación de desinfectantes porque:",
    options:["It is the most common salon infection","It is one of the hardest bacteria to kill, so agents that destroy it are broadly effective","It only affects nail salon environments","It is the easiest organism to culture in laboratory testing"],
    options_es:["Es la infección de salón más común","Es una de las bacterias más difíciles de eliminar, por lo que los agentes que la destruyen son ampliamente efectivos","Solo afecta los entornos de salones de uñas","Es el organismo más fácil de cultivar en pruebas de laboratorio"],
    correct:1,
    explanation:"A disinfectant proven effective against TB (a very resistant organism) is considered broadly effective against less resistant pathogens." },

  { id:668, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An EPA registration number on a disinfectant label confirms:",
    question_es:"Un número de registro de la EPA en la etiqueta de un desinfectante confirma:",
    options:["The product is safe to ingest","The product has been tested and registered for its claimed disinfection effectiveness","The product was manufactured in the United States","The product is approved for safe use on skin"],
    options_es:["El producto es seguro para ingerir","El producto ha sido probado y registrado por su efectividad de desinfección declarada","El producto fue fabricado en los Estados Unidos","El producto está aprobado para uso seguro en la piel"],
    correct:1,
    explanation:"An EPA registration number confirms the disinfectant has been evaluated and registered for its claimed disinfection effectiveness." },

  { id:669, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The standard bleach dilution for disinfecting non-porous salon surfaces is approximately:",
    question_es:"La dilución estándar de blanqueador para desinfectar superficies no porosas del salón es aproximadamente:",
    options:["1 part bleach to 5 parts water","1 part bleach to 10 parts water","1 part bleach to 100 parts water","Undiluted bleach for best results"],
    options_es:["1 parte de blanqueador por 5 partes de agua","1 parte de blanqueador por 10 partes de agua","1 parte de blanqueador por 100 partes de agua","Blanqueador sin diluir para mejores resultados"],
    correct:1,
    explanation:"A 1:10 bleach-to-water ratio (approximately 5,000 ppm) is the EPA-recognized standard for salon surface disinfection." },

  { id:670, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Efficacy' on a disinfectant label refers to:",
    question_es:"'Eficacia' en la etiqueta de un desinfectante se refiere a:",
    options:["The pleasant fragrance of the product","The product's proven ability to kill specific pathogens as determined by EPA-approved testing","The product's safety record for human skin contact","The shelf life and storage stability of the product"],
    options_es:["La fragancia agradable del producto","La capacidad comprobada del producto para eliminar patógenos específicos según las pruebas aprobadas por la EPA","El historial de seguridad del producto para el contacto con la piel humana","La vida útil y la estabilidad de almacenamiento del producto"],
    correct:1,
    explanation:"Efficacy refers to the demonstrated effectiveness of a disinfectant against specific organisms as determined by EPA-approved testing." },

  { id:671, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Tinea capitis is a fungal infection of the:",
    question_es:"La tiña capitis es una infección fúngica del:",
    options:["Nails","Feet","Scalp","Hands"],
    options_es:["Uñas","Pies","Cuero cabelludo","Manos"],
    correct:2,
    explanation:"Tinea capitis is ringworm of the scalp; a cosmetologist must recognize this condition and decline service, referring the client to a physician." },

  { id:672, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Tinea pedis is commonly known as:",
    question_es:"La tinea pedis se conoce comúnmente como:",
    options:["Ringworm of the scalp","Athlete's foot","Nail fungus","Jock itch"],
    options_es:["Tiña del cuero cabelludo","Pie de atleta","Hongo de las uñas","Tiña inguinal"],
    correct:1,
    explanation:"Tinea pedis is athlete's foot, a fungal infection of the feet; cosmetologists performing pedicures should recognize and decline service when present." },

  { id:673, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Onychomycosis refers to:",
    question_es:"La onicomicosis se refiere a:",
    options:["A form of skin cancer","Fungal infection of the nail","A bacterial scalp condition","Head lice infestation"],
    options_es:["Una forma de cáncer de piel","Infección fúngica de la uña","Una condición bacteriana del cuero cabelludo","Infestación de piojos en la cabeza"],
    correct:1,
    explanation:"Onychomycosis is a fungal infection of the nail; nail technicians should refuse service and refer the client to a physician." },

  { id:674, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A client arrives with signs of head lice (pediculosis capitis). The cosmetologist should:",
    question_es:"Un cliente llega con signos de piojos en la cabeza (pediculosis capitis). El cosmetólogo debe:",
    options:["Apply a medicated shampoo and proceed with the service","Refuse service and refer the client to a physician or pharmacist","Proceed but use extra protective coverings","Sanitize the client's scalp with disinfectant and continue"],
    options_es:["Aplicar un champú medicado y continuar con el servicio","Negarse a dar el servicio y referir al cliente a un médico o farmacéutico","Continuar pero usar coberturas protectoras adicionales","Desinfectar el cuero cabelludo del cliente con desinfectante y continuar"],
    correct:1,
    explanation:"Head lice is a parasitic infestation; cosmetologists cannot treat it and must refuse service to prevent spread to other clients." },

  { id:675, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Pediculosis is caused by:",
    question_es:"La pediculosis es causada por:",
    options:["Bacteria","Viruses","Fungi","Parasitic insects (lice)"],
    options_es:["Bacterias","Virus","Hongos","Insectos parásitos (piojos)"],
    correct:3,
    explanation:"Pediculosis is an infestation caused by parasitic lice (insects); it is not caused by bacteria, viruses, or fungi." },

  { id:676, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Scabies is caused by:",
    question_es:"La sarna es causada por:",
    options:["A fungal infection","A parasitic mite (Sarcoptes scabiei)","Staphylococcal bacteria","The herpes simplex virus"],
    options_es:["Una infección fúngica","Un ácaro parásito (Sarcoptes scabiei)","Bacterias estafilocócicas","El virus del herpes simple"],
    correct:1,
    explanation:"Scabies is caused by the microscopic itch mite Sarcoptes scabiei, which burrows into the skin." },

  { id:677, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A client has an active cold sore (herpes simplex) on their lip and requests a facial. The cosmetologist should:",
    question_es:"Un cliente tiene un herpes labial activo (herpes simple) en el labio y solicita un facial. El cosmetólogo debe:",
    options:["Proceed with the facial as usual","Avoid the affected area only and continue the service","Decline the service until the lesion has fully healed","Apply disinfectant to the sore and proceed"],
    options_es:["Continuar con el facial como de costumbre","Evitar solo el área afectada y continuar el servicio","Rechazar el servicio hasta que la lesión haya sanado completamente","Aplicar desinfectante al herpes labial y continuar"],
    correct:2,
    explanation:"An active herpes lesion is contagious; facial services must be declined until the lesion is fully healed to prevent transmission." },

  { id:678, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The primary route of HIV transmission relevant to salon settings is:",
    question_es:"La principal vía de transmisión del VIH relevante en los entornos de salón es:",
    options:["Airborne droplets spread through the air","Casual skin contact such as handshakes","Blood-to-blood contact through cuts or open wounds","Sharing combs, brushes, or styling tools"],
    options_es:["Gotitas en el aire transmitidas por el aire","Contacto casual de piel como apretones de manos","Contacto de sangre a sangre a través de cortes o heridas abiertas","Compartir peines, cepillos o herramientas para el cabello"],
    correct:2,
    explanation:"HIV requires direct blood-to-blood, sexual, or perinatal transmission; routine salon contact does not transmit HIV." },

  { id:679, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"MRSA (Methicillin-Resistant Staphylococcus aureus) is a concern in salons because:",
    question_es:"El MRSA (Staphylococcus aureus resistente a la meticilina) es una preocupación en los salones porque:",
    options:["It spreads instantaneously through the air throughout the salon","It can survive on surfaces and spread through skin contact or contaminated implements","It only affects immunocompromised clients in hospital settings","No disinfectant can kill it under any circumstances"],
    options_es:["Se propaga instantáneamente por el aire en todo el salón","Puede sobrevivir en superficies y propagarse por contacto con la piel o implementos contaminados","Solo afecta a los clientes inmunocomprometidos en entornos hospitalarios","Ningún desinfectante puede eliminarlo bajo ninguna circunstancia"],
    correct:1,
    explanation:"MRSA is an antibiotic-resistant staph bacteria that can survive on surfaces; proper disinfection of implements and surfaces is essential to prevent spread." },

  { id:680, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which PPE item is most important when a cosmetologist encounters a bleeding client?",
    question_es:"¿Qué artículo de EPP es más importante cuando un cosmetólogo se encuentra con un cliente que sangra?",
    options:["Safety glasses","Disposable gloves","A protective gown","A face shield"],
    options_es:["Gafas de seguridad","Guantes desechables","Una bata protectora","Una careta"],
    correct:1,
    explanation:"Disposable gloves are the first line of defense against bloodborne pathogen exposure from client blood." },

  { id:681, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The correct technique for removing contaminated disposable gloves is:",
    question_es:"La técnica correcta para quitarse los guantes desechables contaminados es:",
    options:["Tear both gloves off at once by pulling from the fingertips","Peel the first glove off from the wrist and trap it inside the second, then remove the second inside-out","Remove gloves by pulling from fingertips of both hands simultaneously","Use scissors to cut the gloves off at the wrist"],
    options_es:["Rasgar ambos guantes de una vez jalando desde las puntas de los dedos","Despegar el primer guante desde la muñeca y atraparlo dentro del segundo, luego quitarse el segundo al revés","Quitar los guantes jalando desde las puntas de los dedos de ambas manos simultáneamente","Usar tijeras para cortar los guantes en la muñeca"],
    correct:1,
    explanation:"The inside-out removal technique minimizes contact with the contaminated outer surface of the gloves during removal." },

  { id:682, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Fomites' are defined as:",
    question_es:"Los 'fomites' se definen como:",
    options:["Airborne disease particles suspended in the air","Inanimate objects that can carry and transfer pathogens","Beneficial microorganisms found in the gut","A category of chemical disinfectants"],
    options_es:["Partículas de enfermedad en el aire suspendidas en el aire","Objetos inanimados que pueden portar y transferir patógenos","Microorganismos beneficiosos que se encuentran en el intestino","Una categoría de desinfectantes químicos"],
    correct:1,
    explanation:"Fomites (combs, towels, implements) can harbor and transfer pathogens between clients and are a key vector for cross-contamination." },

  { id:683, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"To prevent pathogen transmission through fomites in a salon, cosmetologists must:",
    question_es:"Para prevenir la transmisión de patógenos a través de fomites en un salón, los cosmetólogos deben:",
    options:["Clean tools only at the end of each workday","Disinfect implements between every client","Rinse implements with water only between uses","Use the same tools all day without cleaning if they look clean"],
    options_es:["Limpiar las herramientas solo al final de cada jornada de trabajo","Desinfectar los implementos entre cada cliente","Enjuagar los implementos solo con agua entre usos","Usar las mismas herramientas todo el día sin limpiarlas si se ven limpias"],
    correct:1,
    explanation:"Each implement must be properly cleaned and disinfected between clients to prevent pathogen transfer through fomites." },

  { id:684, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An 'opportunistic infection' is one that:",
    question_es:"Una 'infección oportunista' es aquella que:",
    options:["Occurs only in people with very strong immune systems","Develops when the immune system is weakened and cannot fight off normally harmless organisms","Is always highly contagious to healthy individuals","Occurs exclusively in clinical or hospital settings"],
    options_es:["Ocurre solo en personas con sistemas inmunitarios muy fuertes","Se desarrolla cuando el sistema inmunitario está debilitado y no puede combatir organismos normalmente inofensivos","Siempre es muy contagiosa para personas sanas","Ocurre exclusivamente en entornos clínicos u hospitalarios"],
    correct:1,
    explanation:"Opportunistic infections exploit a weakened immune system; clients undergoing chemotherapy or with HIV/AIDS may be more susceptible." },

  { id:685, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following best describes 'indirect contact' transmission in a salon?",
    question_es:"¿Cuál de los siguientes describe mejor la transmisión por 'contacto indirecto' en un salón?",
    options:["A pathogen passes directly from an infected person's skin to a client during a service","A pathogen travels through the air from one person to another","A pathogen is transferred through a contaminated implement or surface rather than direct person-to-person contact","A pathogen enters the body through ingestion of contaminated food"],
    options_es:["Un patógeno pasa directamente de la piel de una persona infectada a un cliente durante un servicio","Un patógeno viaja por el aire de una persona a otra","Un patógeno se transfiere a través de un implemento o superficie contaminados en lugar de contacto directo de persona a persona","Un patógeno entra al cuerpo mediante la ingestión de alimentos contaminados"],
    correct:2,
    explanation:"Indirect contact transmission occurs when pathogens travel via contaminated objects (implements, towels, surfaces) rather than direct person-to-person contact." },

  { id:686, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Tinea unguium and onychomycosis refer to:",
    question_es:"La tinea unguium y la onicomicosis se refieren a:",
    options:["Two completely different nail conditions","The same condition: fungal infection of the nail","A bacterial nail infection","A viral nail lesion"],
    options_es:["Dos condiciones de uñas completamente diferentes","La misma condición: infección fúngica de la uña","Una infección bacteriana de las uñas","Una lesión viral de las uñas"],
    correct:1,
    explanation:"Tinea unguium is another name for onychomycosis — both describe fungal infection of the nail." },

  { id:687, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An autoclave sterilizes implements using:",
    question_es:"Un autoclave esteriliza los implementos mediante:",
    options:["UV light and ozone gas","Steam under high pressure at 250°F (121°C)","Chemical vapor at room temperature","Dry heat at 400°F for two hours"],
    options_es:["Luz UV y gas ozono","Vapor a alta presión a 121°C (250°F)","Vapor químico a temperatura ambiente","Calor seco a 200°C durante dos horas"],
    correct:1,
    explanation:"Autoclaves use saturated steam under pressure (15 psi at 121°C/250°F) to achieve complete sterilization." },

  { id:688, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Implements that penetrate the skin (such as lancets) require:",
    question_es:"Los implementos que penetran la piel (como lancetas) requieren:",
    options:["Low-level disinfection only","High-level disinfection only","Sterilization","Sanitization with soap and water"],
    options_es:["Solo desinfección de bajo nivel","Solo desinfección de alto nivel","Esterilización","Saneamiento con agua y jabón"],
    correct:2,
    explanation:"Items that penetrate the skin are critical items per the Spaulding Classification and require sterilization, not just disinfection." },

  { id:689, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The most common source of cross-contamination in a salon is:",
    question_es:"La fuente más común de contaminación cruzada en un salón es:",
    options:["Unopened product containers on the shelf","Multi-use implements that were not properly disinfected between clients","Display items placed on retail shelves","Clean towels stored in a covered cabinet"],
    options_es:["Recipientes de productos cerrados en el estante","Implementos de uso múltiple que no fueron debidamente desinfectados entre clientes","Artículos de exhibición colocados en estantes de venta","Toallas limpias guardadas en un armario cerrado"],
    correct:1,
    explanation:"Reused implements (combs, brushes, clippers, files) not properly cleaned and disinfected between clients are the most common source of cross-contamination." },

  { id:690, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The correct order for decontaminating a reusable salon implement is:",
    question_es:"El orden correcto para descontaminar un implemento de salón reutilizable es:",
    options:["Disinfect first, then clean with soap and water","Remove visible debris with soap and water, rinse, then immerse in EPA-registered disinfectant","Spray disinfectant and immediately wipe dry","Rinse with cold water, then air-dry"],
    options_es:["Desinfectar primero, luego limpiar con agua y jabón","Eliminar los residuos visibles con agua y jabón, enjuagar, luego sumergir en desinfectante registrado en la EPA","Rociar desinfectante y secar inmediatamente","Enjuagar con agua fría, luego dejar secar al aire"],
    correct:1,
    explanation:"Pre-cleaning (removing debris with soap and water) must occur BEFORE disinfection, as organic material inactivates disinfectants." },

  { id:691, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Disinfectant solutions in wet sanitizers must be changed:",
    question_es:"Las soluciones desinfectantes en los sanitizadores húmedos deben cambiarse:",
    options:["Once per week regardless of condition","When visibly dirty or contaminated, or per manufacturer's guidelines","Every six months unless depleted","Only when the salon is scheduled for an inspection"],
    options_es:["Una vez por semana independientemente de su condición","Cuando estén visiblemente sucias o contaminadas, o según las indicaciones del fabricante","Cada seis meses a menos que se agoten","Solo cuando el salón esté programado para una inspección"],
    correct:1,
    explanation:"Disinfectant efficacy decreases with contamination; change solutions when visibly dirty or as the manufacturer specifies." },

  { id:692, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A 'wet sanitizer' in a salon is a covered container that holds:",
    question_es:"Un 'sanitizador húmedo' en un salón es un recipiente tapado que contiene:",
    options:["Water only for rinsing tools","An EPA-registered disinfectant solution for immersing pre-cleaned implements","Steam or heated water for towel steaming","Shampoo solution for pre-service preparation"],
    options_es:["Solo agua para enjuagar herramientas","Una solución desinfectante registrada en la EPA para sumergir implementos previamente limpios","Vapor o agua caliente para vaporizar toallas","Solución de champú para la preparación previa al servicio"],
    correct:1,
    explanation:"A wet sanitizer holds EPA-registered disinfectant solution at the correct dilution for immersing pre-cleaned implements between clients." },

  { id:693, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Contact time (also called 'dwell time') for disinfectants means:",
    question_es:"El tiempo de contacto (también llamado 'tiempo de permanencia') para los desinfectantes significa:",
    options:["How long the product can be safely stored","The duration the surface or implement must remain wet with disinfectant for it to be effective","How quickly the product kills pathogens when not directly applied","The manufacturer's warranty period for the product"],
    options_es:["Cuánto tiempo se puede almacenar el producto de manera segura","La duración que la superficie o el implemento debe permanecer húmedo con el desinfectante para que sea efectivo","Con qué rapidez el producto elimina patógenos cuando no se aplica directamente","El período de garantía del fabricante para el producto"],
    correct:1,
    explanation:"The surface must remain visibly wet with disinfectant for the full contact time; wiping dry early reduces or eliminates efficacy." },

  { id:694, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"If a disinfectant is diluted more than the manufacturer recommends, it:",
    question_es:"Si un desinfectante se diluye más de lo que recomienda el fabricante:",
    options:["Becomes more effective and safer","May become too weak to kill target pathogens","Is stronger and kills more organisms","Achieves sterilization level instead of disinfection"],
    options_es:["Se vuelve más efectivo y seguro","Puede ser demasiado débil para eliminar los patógenos objetivo","Es más fuerte y elimina más organismos","Alcanza un nivel de esterilización en lugar de desinfección"],
    correct:1,
    explanation:"Over-dilution reduces the active ingredient below its effective concentration, potentially failing to kill target organisms." },

  { id:695, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A 'virucidal' disinfectant is one that can:",
    question_es:"Un desinfectante 'virucida' es aquel que puede:",
    options:["Kill only bacteria","Kill only fungi","Inactivate viruses","Kill all forms of microbial life including spores"],
    options_es:["Eliminar solo bacterias","Eliminar solo hongos","Inactivar virus","Eliminar todas las formas de vida microbiana, incluidas las esporas"],
    correct:2,
    explanation:"Virucidal agents can inactivate viruses; this claim is listed and verified on the product label by the EPA." },

  { id:696, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A 'bactericidal' agent is one that:",
    question_es:"Un agente 'bactericida' es aquel que:",
    options:["Inhibits bacterial growth without killing bacteria","Kills bacteria","Only reduces bacterial odor","Is the same as a bacteriostatic agent"],
    options_es:["Inhibe el crecimiento bacteriano sin matar las bacterias","Mata las bacterias","Solo reduce el olor bacteriano","Es igual que un agente bacteriostático"],
    correct:1,
    explanation:"Bactericidal agents kill bacteria (as opposed to bacteriostatic agents, which only inhibit growth without killing)." },

  { id:697, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Effective hand washing should last at least:",
    question_es:"El lavado de manos efectivo debe durar al menos:",
    options:["5 seconds","10 seconds","20 seconds","2 minutes"],
    options_es:["5 segundos","10 segundos","20 segundos","2 minutos"],
    correct:2,
    explanation:"CDC guidelines recommend scrubbing hands with soap for at least 20 seconds to effectively remove pathogens." },

  { id:698, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Soap and water hand washing is preferred over alcohol-based hand sanitizer when hands are:",
    question_es:"El lavado de manos con agua y jabón es preferible al desinfectante de manos a base de alcohol cuando las manos están:",
    options:["Visibly clean and dry","Visibly soiled with dirt or organic material","Slightly damp from water","Very cold from the environment"],
    options_es:["Visiblemente limpias y secas","Visiblemente sucias con tierra o material orgánico","Ligeramente húmedas por el agua","Muy frías por el entorno"],
    correct:1,
    explanation:"Hand sanitizers are less effective on visibly soiled hands; soap and water must be used when hands have visible contamination." },

  { id:699, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"OSHA's Hazard Communication Standard (HazCom) requires salons to:",
    question_es:"El Estándar de Comunicación de Peligros (HazCom) de OSHA requiere que los salones:",
    options:["Have clients sign chemical hazard waivers before services","Train employees on chemical hazards and maintain accessible Safety Data Sheets (SDS)","Use only organic or natural products","Obtain EPA approval for every product used"],
    options_es:["Que los clientes firmen exenciones de peligros químicos antes de los servicios","Capacitar a los empleados sobre los peligros químicos y mantener Hojas de Datos de Seguridad (SDS) accesibles","Usar solo productos orgánicos o naturales","Obtener la aprobación de la EPA para cada producto utilizado"],
    correct:1,
    explanation:"OSHA's HazCom (Right to Know) Standard requires employee training on chemical hazards and accessible SDS for all hazardous chemicals in the workplace." },

  { id:700, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"OSHA's Bloodborne Pathogen Standard requires covered employers to have:",
    question_es:"El Estándar de Patógenos de Transmisión Sanguínea de OSHA requiere que los empleadores cubiertos tengan:",
    options:["Only verbal bloodborne pathogen training for new hires","A written Exposure Control Plan (ECP) and annual BBP training for exposed employees","Only a posted sign about bloodborne pathogen risks","Annual HIV and hepatitis testing for all employees"],
    options_es:["Solo capacitación verbal sobre patógenos de transmisión sanguínea para los nuevos empleados","Un Plan de Control de Exposición (PCE) escrito y capacitación anual sobre PTS para los empleados expuestos","Solo un cartel publicado sobre los riesgos de patógenos de transmisión sanguínea","Pruebas anuales de VIH y hepatitis para todos los empleados"],
    correct:1,
    explanation:"OSHA requires a written ECP, annual employee BBP training, hepatitis B vaccination offer, and documentation of exposure incidents." },

  { id:701, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A whirlpool foot bath used in nail services must be disinfected:",
    question_es:"Un baño de pies con hidromasaje utilizado en servicios de uñas debe desinfectarse:",
    options:["Once at the end of each workday only","After every client using an EPA-registered disinfection protocol","Once per week during off-peak hours","Only when it appears visibly dirty"],
    options_es:["Solo una vez al final de cada jornada de trabajo","Después de cada cliente siguiendo un protocolo de desinfección registrado en la EPA","Una vez por semana en las horas de menor actividad","Solo cuando parece visiblemente sucio"],
    correct:1,
    explanation:"Whirlpool foot baths must be disinfected after each client using an EPA-registered disinfectant to prevent bacterial infections." },

  { id:702, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Non-tuberculous mycobacteria (NTM) infections in nail salons are most often linked to:",
    question_es:"Las infecciones por micobacterias no tuberculosas (MNT) en los salones de uñas se asocian más frecuentemente con:",
    options:["Sharing nail polish between clients","Inadequately disinfected whirlpool foot baths","Using acetone nail polish remover","UV gel lamp exposure during services"],
    options_es:["Compartir el esmalte de uñas entre clientes","Baños de pies con hidromasaje inadecuadamente desinfectados","Usar acetona para quitar el esmalte","Exposición a lámparas UV de gel durante los servicios"],
    correct:1,
    explanation:"NTM outbreaks (particularly M. fortuitum) have been traced to improperly maintained whirlpool foot baths in nail salons." },

  { id:703, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Porous materials (such as wooden handles or nail files) cannot be fully disinfected and must be:",
    question_es:"Los materiales porosos (como los mangos de madera o las limas de uñas) no pueden desinfectarse completamente y deben:",
    options:["Soaked in disinfectant for twice the normal contact time","Discarded after each client use or avoided in professional salon settings","Autoclaved before each reuse","Disinfected with bleach at full concentration"],
    options_es:["Sumergirse en desinfectante el doble del tiempo de contacto normal","Desecharse después del uso de cada cliente o evitarse en entornos profesionales de salón","Esterilizarse en autoclave antes de cada reutilización","Desinfectarse con blanqueador a concentración total"],
    correct:1,
    explanation:"Porous materials absorb and harbor pathogens that cannot be fully removed by disinfection; they must be single-use or avoided." },

  { id:704, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The Spaulding Classification categorizes salon items as:",
    question_es:"La Clasificación de Spaulding categoriza los artículos del salón como:",
    options:["High-value, medium-value, and low-value based on cost","Critical, semi-critical, and non-critical based on infection risk","Regulated, semi-regulated, and unregulated by licensing status","Metallic, plastic, and organic by material composition"],
    options_es:["De alto valor, valor medio y bajo valor según el costo","Críticos, semicríticos y no críticos según el riesgo de infección","Regulados, semi-regulados y no regulados según el estado de licencias","Metálicos, plásticos y orgánicos según la composición del material"],
    correct:1,
    explanation:"The Spaulding Classification determines the required level of disinfection or sterilization based on how the item contacts body tissue." },

  { id:705, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Non-critical items that contact only intact skin require, at minimum:",
    question_es:"Los artículos no críticos que contactan solo la piel intacta requieren, como mínimo:",
    options:["Sterilization after every use","High-level disinfection after every use","Low-level disinfection or thorough cleaning","No cleaning as long as they look clean"],
    options_es:["Esterilización después de cada uso","Desinfección de alto nivel después de cada uso","Desinfección de bajo nivel o limpieza minuciosa","Sin limpieza siempre que se vean limpios"],
    correct:2,
    explanation:"Per the Spaulding Classification, non-critical items (those touching only intact skin) require low-level disinfection or cleaning." },

  { id:706, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Ventilation in a nail salon is important primarily to:",
    question_es:"La ventilación en un salón de uñas es importante principalmente para:",
    options:["Reduce the salon's electricity costs","Remove chemical fumes and vapors that can cause respiratory harm to staff and clients","Keep the salon cooler during summer months","Improve the overall Wi-Fi signal in the workspace"],
    options_es:["Reducir los costos de electricidad del salón","Eliminar los vapores y humos químicos que pueden causar daño respiratorio al personal y a los clientes","Mantener el salón más fresco durante los meses de verano","Mejorar la señal de Wi-Fi general en el espacio de trabajo"],
    correct:1,
    explanation:"Nail services involve chemicals (acetone, acrylics, gels) that emit harmful fumes; proper ventilation is essential to protect health." },

  { id:707, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An 'antiseptic' differs from a 'disinfectant' in that antiseptics are:",
    question_es:"Un 'antiséptico' se diferencia de un 'desinfectante' en que los antisépticos son:",
    options:["The same thing — the terms are interchangeable","Formulated for safe use on living skin and tissue, while disinfectants are for non-living surfaces","Always stronger and more effective than disinfectants","Only used in hospital surgical suites"],
    options_es:["Lo mismo: los términos son intercambiables","Formulados para uso seguro en piel viva y tejidos, mientras que los desinfectantes son para superficies no vivas","Siempre más fuertes y más efectivos que los desinfectantes","Solo se usan en quirófanos hospitalarios"],
    correct:1,
    explanation:"Antiseptics are designed for safe use on skin; disinfectants are formulated for non-living surfaces and must not be used on skin." },

  { id:708, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetologist should NOT perform services if they themselves have:",
    question_es:"Un cosmetólogo NO debe realizar servicios si él mismo tiene:",
    options:["Mild fatigue from a long work shift","An active communicable disease or open skin infection","A personal preference against a specific service type","A mild headache or minor discomfort"],
    options_es:["Fatiga leve por un largo turno de trabajo","Una enfermedad transmisible activa o una infección cutánea abierta","Una preferencia personal en contra de un tipo de servicio específico","Dolor de cabeza leve o malestar menor"],
    correct:1,
    explanation:"A cosmetologist with an active communicable disease or infectious skin condition risks transmitting the infection to clients." },

  { id:709, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Blood-contaminated implements must be handled by:",
    question_es:"Los implementos contaminados con sangre deben manejarse mediante:",
    options:["Rinsing with warm water and returning to service immediately","Pre-cleaning with soap and water, then fully immersing in an EPA-registered hospital-grade disinfectant","Throwing all blood-contaminated implements away after every incident","Using UV sanitizer exposure for 10 minutes only"],
    options_es:["Enjuagar con agua tibia y volver al servicio de inmediato","Prelimpiar con agua y jabón, luego sumergir completamente en un desinfectante de grado hospitalario registrado en la EPA","Desechar todos los implementos contaminados con sangre después de cada incidente","Usar solo exposición al sanitizador UV durante 10 minutos"],
    correct:1,
    explanation:"Blood-contaminated implements must be pre-cleaned (removing all visible blood) then fully immersed in an EPA-registered, hospital-grade (tuberculocidal) disinfectant." },

  { id:710, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Environmental surfaces (countertops, headrests, armrests) should be disinfected:",
    question_es:"Las superficies ambientales (encimeras, reposacabezas, apoyabrazos) deben desinfectarse:",
    options:["Once per week during regular deep cleaning","Between each client and at the end of each workday","Only at the end of each workday","Only when visibly contaminated with blood or product"],
    options_es:["Una vez por semana durante la limpieza profunda regular","Entre cada cliente y al final de cada jornada de trabajo","Solo al final de cada jornada de trabajo","Solo cuando estén visiblemente contaminadas con sangre o producto"],
    correct:1,
    explanation:"Surfaces that clients contact should be disinfected between clients to prevent cross-contamination, and again at day's end." },

  { id:711, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"After accidentally pricking themselves with a used lancet, a cosmetologist should FIRST:",
    question_es:"Después de pincharse accidentalmente con una lanceta usada, un cosmetólogo debe PRIMERO:",
    options:["Continue working and clean the wound after the appointment ends","Immediately wash the wound with soap and water, then report the incident and follow the exposure protocol","Apply only hand sanitizer and continue the service","Self-administer an antibiotic without medical guidance"],
    options_es:["Continuar trabajando y limpiar la herida después de que finalice la cita","Lavar inmediatamente la herida con agua y jabón, luego reportar el incidente y seguir el protocolo de exposición","Solo aplicar desinfectante de manos y continuar el servicio","Autoadministrarse un antibiótico sin orientación médica"],
    correct:1,
    explanation:"A needlestick requires immediate wound washing, incident documentation, and following the Exposure Control Plan, which may include medical evaluation." },

  { id:712, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Standard precautions require a cosmetologist to treat all clients:",
    question_es:"Las precauciones estándar requieren que un cosmetólogo trate a todos los clientes:",
    options:["Only with extra care if they appear visibly ill","As potentially infectious, regardless of their apparent health status","With standard care unless the client discloses a condition","Differently based on known risk factors disclosed during consultation"],
    options_es:["Solo con cuidado adicional si parecen visiblemente enfermos","Como potencialmente infecciosos, independientemente de su estado de salud aparente","Con cuidado estándar a menos que el cliente revele una condición","De manera diferente según los factores de riesgo conocidos revelados durante la consulta"],
    correct:1,
    explanation:"Standard precautions assume all clients may be infectious regardless of appearance or disclosed health status, protecting both client and cosmetologist." },

  { id:713, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Bacteria reproduce asexually by a process called:",
    question_es:"Las bacterias se reproducen de forma asexual mediante un proceso llamado:",
    options:["Spore formation","Binary fission","Budding","Mitosis and meiosis"],
    options_es:["Formación de esporas","Fisión binaria","Gemación","Mitosis y meiosis"],
    correct:1,
    explanation:"Bacteria reproduce by binary fission, splitting into two identical daughter cells; this allows rapid multiplication under favorable conditions." },

  { id:714, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Viruses differ from bacteria in that viruses:",
    question_es:"Los virus se diferencian de las bacterias en que los virus:",
    options:["Are larger and easier to filter out","Can reproduce independently without a host cell","Require a living host cell to replicate","Are effectively killed by antibiotics"],
    options_es:["Son más grandes y más fáciles de filtrar","Pueden reproducirse de forma independiente sin una célula huésped","Requieren una célula huésped viva para replicarse","Son eliminados eficazmente por los antibióticos"],
    correct:2,
    explanation:"Viruses are obligate intracellular parasites that can only replicate inside a living host cell, unlike bacteria which reproduce independently." },

  { id:715, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Antibiotics are effective against:",
    question_es:"Los antibióticos son efectivos contra:",
    options:["Viruses and bacteria equally","Bacteria only — they have no effect on viruses","Fungi only","All infectious microorganisms"],
    options_es:["Virus y bacterias por igual","Solo bacterias — no tienen efecto sobre los virus","Solo hongos","Todos los microorganismos infecciosos"],
    correct:1,
    explanation:"Antibiotics target bacterial structures or processes; they have no effect on viruses, which is why they cannot treat colds or flu." },

  { id:716, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Bacterial endospores are dangerous because they:",
    question_es:"Las endosporas bacterianas son peligrosas porque:",
    options:["Reproduce faster than vegetative bacteria","Are highly resistant structures that survive extreme conditions that kill vegetative bacteria","Are the only form of bacteria visible to the naked eye","Only form in viruses during latency"],
    options_es:["Se reproducen más rápido que las bacterias vegetativas","Son estructuras muy resistentes que sobreviven condiciones extremas que matan las bacterias vegetativas","Son la única forma de bacteria visible a simple vista","Solo se forman en los virus durante la latencia"],
    correct:1,
    explanation:"Endospores are resistant dormant structures formed by some bacteria that survive high temperatures, UV light, and many disinfectants; sterilization is required to destroy them." },

  { id:717, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Proper storage of disinfected implements requires placing them in:",
    question_es:"El almacenamiento adecuado de los implementos desinfectados requiere colocarlos en:",
    options:["Back in the disinfectant solution for ongoing protection","A clean, covered, and labeled container until next use","An open container on the counter to air-dry","The same drawer as unused dirty implements"],
    options_es:["De vuelta en la solución desinfectante para protección continua","Un recipiente limpio, tapado y etiquetado hasta el próximo uso","Un recipiente abierto en el mostrador para que se seque al aire","El mismo cajón que los implementos sucios sin usar"],
    correct:1,
    explanation:"Disinfected implements must be stored in a clean, covered, labeled container to prevent re-contamination until use." },

  { id:718, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which statement about 70% isopropyl alcohol in a salon context is CORRECT?",
    question_es:"¿Qué afirmación sobre el alcohol isopropílico al 70% en el contexto de un salón es CORRECTA?",
    options:["It sterilizes all salon implements when used for 10 minutes","It is an effective skin antiseptic but is not a registered hospital-grade salon implement disinfectant","It kills all spores on contact with no immersion time needed","It is the preferred EPA-registered disinfectant for all nail implements"],
    options_es:["Esteriliza todos los implementos del salón cuando se usa durante 10 minutos","Es un antiséptico cutáneo efectivo pero no es un desinfectante de implementos de salón de grado hospitalario registrado","Mata todas las esporas al contacto sin necesidad de tiempo de inmersión","Es el desinfectante preferido registrado en la EPA para todos los implementos de uñas"],
    correct:1,
    explanation:"70% isopropyl alcohol is effective as a skin antiseptic but does not meet EPA registration requirements for hospital-grade salon implement disinfection." },

  { id:719, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The hepatitis B vaccine is recommended for cosmetologists because:",
    question_es:"La vacuna contra la hepatitis B se recomienda para los cosmetólogos porque:",
    options:["It is mandatory under TDLR regulations","HBV can survive on dry surfaces for up to 7 days, posing an occupational exposure risk","It also protects against all other types of hepatitis","Getting vaccinated eliminates the need for standard precautions"],
    options_es:["Es obligatoria según las regulaciones de TDLR","El VHB puede sobrevivir en superficies secas hasta 7 días, lo que representa un riesgo de exposición ocupacional","También protege contra todos los demás tipos de hepatitis","Vacunarse elimina la necesidad de precauciones estándar"],
    correct:1,
    explanation:"Hepatitis B virus survives on dry surfaces for days, making salon exposure a real occupational risk; vaccination significantly reduces this risk." },

  { id:720, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Conjunctivitis (pink eye) can spread in a salon through:",
    question_es:"La conjuntivitis (ojo rojo) puede propagarse en un salón a través de:",
    options:["Only direct eye-to-eye contact between individuals","Contact with infected eye secretions via contaminated towels or tools","Only airborne transmission in enclosed spaces","Only through contaminated food or beverages"],
    options_es:["Solo contacto directo de ojo a ojo entre individuos","Contacto con secreciones oculares infectadas a través de toallas o herramientas contaminadas","Solo transmisión aérea en espacios cerrados","Solo a través de alimentos o bebidas contaminados"],
    correct:1,
    explanation:"Infectious conjunctivitis spreads through contact with eye secretions; shared towels or tools touching the eye area can transmit it." },

  { id:721, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetologist with an open cut on their hand providing a service should:",
    question_es:"Un cosmetólogo con una cortada abierta en la mano que brinda un servicio debe:",
    options:["Stop working for the remainder of the day","Cover the cut with a liquid bandage or bandage and wear gloves over it","Apply only a bandage without gloves","Work without any coverage since small cuts pose minimal risk"],
    options_es:["Dejar de trabajar por el resto del día","Cubrir el corte con un vendaje o vendaje líquido y ponerse guantes encima","Aplicar solo un vendaje sin guantes","Trabajar sin ninguna cobertura ya que los cortes pequeños representan un riesgo mínimo"],
    correct:1,
    explanation:"Open cuts must be covered and gloves worn to prevent both pathogen transmission to clients and infection of the cosmetologist's own wound." },

  { id:722, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The key difference between cleaning, disinfecting, and sterilizing is:",
    question_es:"La diferencia clave entre limpiar, desinfectar y esterilizar es:",
    options:["They are essentially the same process with different marketing names","Cleaning removes visible dirt; disinfecting kills most pathogens; sterilizing destroys all microorganisms including spores","Sterilizing is the lowest level of microbial control","Cleaning kills the greatest number of pathogens of the three methods"],
    options_es:["Son esencialmente el mismo proceso con diferentes nombres de marketing","Limpiar elimina la suciedad visible; desinfectar mata la mayoría de los patógenos; esterilizar destruye todos los microorganismos, incluidas las esporas","Esterilizar es el nivel más bajo de control microbiano","Limpiar mata la mayor cantidad de patógenos de los tres métodos"],
    correct:1,
    explanation:"Each level provides progressively greater microbial reduction: cleaning removes soils, disinfecting kills most organisms, sterilization eliminates all life." },

  { id:723, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Chemical disinfectants can be neutralized by:",
    question_es:"Los desinfectantes químicos pueden ser neutralizados por:",
    options:["Clean water applied after disinfection","Organic matter (blood, hair, skin cells), hard water minerals, or excessive dilution","Sunlight exposure during application","Keeping them in sealed, airtight containers"],
    options_es:["Agua limpia aplicada después de la desinfección","Materia orgánica (sangre, cabello, células de la piel), minerales del agua dura o dilución excesiva","Exposición a la luz solar durante la aplicación","Mantenerlos en recipientes sellados y herméticos"],
    correct:1,
    explanation:"Organic matter and mineral deposits inactivate disinfectants; implements must be pre-cleaned before disinfection to ensure full efficacy." },

  { id:724, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Decontamination' in a salon broadly encompasses:",
    question_es:"La 'descontaminación' en un salón abarca en general:",
    options:["Only sterilization of metal implements","Only disinfection of hard surfaces","Any process — cleaning, disinfecting, or sterilizing — that reduces pathogens to a safe level","Only the removal of chemical products from salon tools"],
    options_es:["Solo la esterilización de implementos metálicos","Solo la desinfección de superficies duras","Cualquier proceso — limpiar, desinfectar o esterilizar — que reduzca los patógenos a un nivel seguro","Solo la eliminación de productos químicos de las herramientas del salón"],
    correct:2,
    explanation:"Decontamination encompasses all levels of pathogen reduction — from basic cleaning through full sterilization — making an item safe for use." },

  { id:725, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Formaldehyde is no longer commonly used as a salon disinfectant because:",
    question_es:"El formaldehído ya no se usa comúnmente como desinfectante de salón porque:",
    options:["It is not effective against any bacteria or fungi","It is a known carcinogen and highly toxic to the respiratory system","It permanently changes the color of metal implements","It is far too expensive for regular salon use"],
    options_es:["No es efectivo contra ninguna bacteria u hongo","Es un carcinógeno conocido y altamente tóxico para el sistema respiratorio","Cambia permanentemente el color de los implementos metálicos","Es demasiado caro para el uso regular en salones"],
    correct:1,
    explanation:"Formaldehyde is classified as a human carcinogen and is severely irritating to the respiratory tract; safer alternatives are used today." },

  { id:726, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A 'patch test' (allergy test) before a chemical service is performed to:",
    question_es:"Una 'prueba de parche' (prueba de alergia) antes de un servicio químico se realiza para:",
    options:["Test the color result on a small area before full application","Determine if the client has an allergic or adverse reaction to the chemical product","Check whether the client's hair can withstand chemical processing","Confirm the chemical product is not expired or contaminated"],
    options_es:["Probar el resultado del color en un área pequeña antes de la aplicación completa","Determinar si el cliente tiene una reacción alérgica o adversa al producto químico","Verificar si el cabello del cliente puede soportar el procesamiento químico","Confirmar que el producto químico no ha caducado ni está contaminado"],
    correct:1,
    explanation:"A patch test (also called a predisposition or allergy test) is applied 24–48 hours before a service to detect allergic reactions to chemical ingredients." },

  { id:727, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A patch test for hair color should be performed:",
    question_es:"Una prueba de parche para el color de cabello debe realizarse:",
    options:["Immediately before each service on the same day","24 to 48 hours before the chemical service","Only for clients who report prior reactions","Only when using a new brand of product for the first time"],
    options_es:["Inmediatamente antes de cada servicio el mismo día","De 24 a 48 horas antes del servicio químico","Solo para clientes que reportan reacciones previas","Solo cuando se usa una nueva marca de producto por primera vez"],
    correct:1,
    explanation:"A patch test must be performed 24–48 hours before the chemical service to allow adequate time for an allergic reaction to develop if one will occur." },

  { id:728, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A positive patch test result means the client:",
    question_es:"Un resultado positivo de la prueba de parche significa que el cliente:",
    options:["Is not allergic and the service can proceed safely","Shows an allergic reaction and should NOT receive the chemical service","Needs a stronger concentration of the product for the service","Has hair that is already fully processed and needs no further chemical"],
    options_es:["No es alérgico y el servicio puede proceder con seguridad","Muestra una reacción alérgica y NO debe recibir el servicio químico","Necesita una concentración más fuerte del producto para el servicio","Tiene cabello que ya está completamente procesado y no necesita más químico"],
    correct:1,
    explanation:"A positive (reactive) patch test indicates allergy or sensitivity; the chemical service must not be performed to avoid severe adverse reactions." },

  { id:729, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A strand test before a chemical hair service is performed to:",
    question_es:"Una prueba de mecha antes de un servicio químico para el cabello se realiza para:",
    options:["Determine if the client has a chemical allergy","Assess how the hair responds to the chemical — including processing time, color result, and hair integrity","Test whether the scalp is sensitive to the product","Verify that the mixing ratio of the product is correct"],
    options_es:["Determinar si el cliente tiene una alergia química","Evaluar cómo el cabello responde al químico, incluido el tiempo de procesamiento, el resultado del color y la integridad del cabello","Probar si el cuero cabelludo es sensible al producto","Verificar que la proporción de mezcla del producto sea correcta"],
    correct:1,
    explanation:"A strand test evaluates the hair's response to the chemical service — checking processing time, color result, and hair strength before full application." },

  { id:730, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which skin condition is caused by the herpes simplex virus and presents as a cluster of fluid-filled blisters?",
    question_es:"¿Qué condición de la piel es causada por el virus del herpes simple y se presenta como un grupo de ampollas llenas de líquido?",
    options:["Impetigo","Fever blisters (cold sores / herpes labialis)","Psoriasis","Contact dermatitis"],
    options_es:["Impétigo","Ampollas febriles (herpes labial / herpes labialis)","Psoriasis","Dermatitis por contacto"],
    correct:1,
    explanation:"Herpes labialis (cold sores / fever blisters) is caused by herpes simplex virus type 1 (HSV-1) and presents as clustered fluid-filled blisters, typically around the mouth." },

  { id:731, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Impetigo is a highly contagious skin infection caused by:",
    question_es:"El impétigo es una infección cutánea muy contagiosa causada por:",
    options:["A fungus","Bacteria (Staphylococcus or Streptococcus)","A virus","A parasitic mite"],
    options_es:["Un hongo","Bacterias (Staphylococcus o Streptococcus)","Un virus","Un ácaro parásito"],
    correct:1,
    explanation:"Impetigo is a bacterial skin infection caused by Staphylococcus aureus or Streptococcus pyogenes; a cosmetologist must refuse service and refer the client to a physician." },

  { id:732, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Psoriasis is a non-contagious skin condition characterized by:",
    question_es:"La psoriasis es una afección cutánea no contagiosa caracterizada por:",
    options:["Fluid-filled blisters from a viral infection","Red, scaly patches caused by an autoimmune disorder with accelerated skin cell turnover","A fungal rash that spreads easily between clients","Open sores from bacterial infection"],
    options_es:["Ampollas llenas de líquido por una infección viral","Parches rojos y escamosos causados por un trastorno autoinmune con renovación acelerada de células de la piel","Un sarpullido fúngico que se propaga fácilmente entre clientes","Llagas abiertas por infección bacteriana"],
    correct:1,
    explanation:"Psoriasis is a non-contagious autoimmune skin condition; services may be performed if there are no open lesions, though the cosmetologist should consult with the client." },

  { id:733, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Contact dermatitis in a cosmetologist is often caused by:",
    question_es:"La dermatitis de contacto en un cosmetólogo frecuentemente es causada por:",
    options:["Exposure to ultraviolet light from salon windows","Repeated contact with hair chemicals, dyes, or latex gloves","Exposure to client hair that has been bleached","Eating food at the salon workstation"],
    options_es:["Exposición a la luz ultravioleta de las ventanas del salón","Contacto repetido con químicos capilares, tintes o guantes de látex","Exposición al cabello del cliente que ha sido decolorado","Comer alimentos en el puesto de trabajo del salón"],
    correct:1,
    explanation:"Cosmetologists frequently develop allergic or irritant contact dermatitis from prolonged exposure to hair chemicals, dyes, and latex; nitrile gloves are often recommended as an alternative." },

  { id:734, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Folliculitis is an infection of the:",
    question_es:"La foliculitis es una infección de:",
    options:["Nail bed","Hair follicle","Sweat glands","Deep dermal tissue"],
    options_es:["Lecho ungueal","Folículo capilar","Glándulas sudoríparas","Tejido dérmico profundo"],
    correct:1,
    explanation:"Folliculitis is a bacterial infection of the hair follicle, often caused by Staphylococcus aureus; it appears as red, inflamed pustules around hair follicles." },

  { id:735, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A carbuncle differs from a furuncle (boil) in that a carbuncle:",
    question_es:"Un carbúnculo se diferencia de un furúnculo (divieso) en que un carbúnculo:",
    options:["Is a fungal infection while a furuncle is bacterial","Is a cluster of interconnected infected follicles that is larger and deeper than a single furuncle","Is found only on the scalp whereas furuncles occur elsewhere","Heals without treatment unlike a furuncle"],
    options_es:["Es una infección fúngica mientras que un furúnculo es bacteriano","Es un grupo de folículos infectados interconectados que es más grande y profundo que un solo furúnculo","Se encuentra solo en el cuero cabelludo mientras que los furúnculos ocurren en otros lugares","Se cura sin tratamiento a diferencia de un furúnculo"],
    correct:1,
    explanation:"A carbuncle is a severe cluster of interconnected boils (furuncles), larger and deeper than a single boil, typically caused by Staphylococcus aureus." },

  { id:736, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following nail conditions indicates possible fungal infection and warrants referral to a physician?",
    question_es:"¿Cuál de las siguientes condiciones de las uñas indica una posible infección fúngica y justifica la derivación a un médico?",
    options:["A slight ridge down the center of the nail","Nails that appear thickened, discolored (yellow/brown/white), and brittle","A small white spot (leukonychia) in the nail plate","Nails that have grown slightly past the fingertip"],
    options_es:["Una ligera cresta en el centro de la uña","Uñas que parecen engrosadas, decoloradas (amarillas/marrones/blancas) y quebradizas","Una pequeña mancha blanca (leuconiquia) en la placa ungueal","Uñas que han crecido ligeramente más allá de la punta del dedo"],
    correct:1,
    explanation:"Thickened, discolored (yellow, brown, or white), and brittle nails are classic signs of onychomycosis (nail fungus) requiring medical treatment, not salon services." },

  { id:737, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following is a contraindication for nail services?",
    question_es:"¿Cuál de los siguientes es una contraindicación para los servicios de uñas?",
    options:["Nails that are slightly shorter than average","An active fungal nail infection (onychomycosis)","Nails with a natural ridge pattern","Cuticles that are dry and slightly overgrown"],
    options_es:["Uñas que son ligeramente más cortas de lo normal","Una infección activa de hongos en las uñas (onicomicosis)","Uñas con un patrón de crestas natural","Cutículas que están secas y ligeramente crecidas"],
    correct:1,
    explanation:"Active nail fungal infection (onychomycosis) is a contraindication for nail services; the client must be referred to a physician for medical treatment." },

  { id:738, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Paronychia is an infection of the:",
    question_es:"La paroniquia es una infección de:",
    options:["Nail plate surface","Skin surrounding the nail (nail fold/cuticle area)","Deep bone beneath the nail","Nail matrix under the lunula"],
    options_es:["Superficie de la placa ungueal","Piel que rodea la uña (pliegue ungueal/área de la cutícula)","Hueso profundo debajo de la uña","Matriz ungueal debajo de la lúnula"],
    correct:1,
    explanation:"Paronychia is a bacterial (or sometimes fungal) infection of the skin surrounding the nail; salon services must be declined and the client referred to a physician." },

  { id:739, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Dandruff (pityriasis capitis) is associated with an overgrowth of the fungus:",
    question_es:"La caspa (pitiriasis capitis) está asociada con un crecimiento excesivo del hongo:",
    options:["Tinea capitis","Malassezia (Pityrosporum)","Candida albicans","Aspergillus niger"],
    options_es:["Tinea capitis","Malassezia (Pityrosporum)","Candida albicans","Aspergillus niger"],
    correct:1,
    explanation:"Dandruff is associated with an overgrowth of Malassezia (formerly Pityrosporum), a naturally occurring scalp fungus; it is not contagious and services may be performed." },

  { id:740, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Seborrheic dermatitis differs from simple dandruff in that it:",
    question_es:"La dermatitis seborreica se diferencia de la caspa simple en que:",
    options:["Is caused by a virus rather than a fungus","Involves more severe inflammation, red patches, and greasy scaling beyond the scalp","Affects only children and teenagers","Is contagious and spreads easily between clients through combs"],
    options_es:["Es causada por un virus en lugar de un hongo","Implica una inflamación más severa, parches rojos y descamación grasosa más allá del cuero cabelludo","Afecta solo a niños y adolescentes","Es contagiosa y se propaga fácilmente entre clientes a través de peines"],
    correct:1,
    explanation:"Seborrheic dermatitis is a more severe form involving inflammation, red patches, and greasy scaling that can extend to the face and ears; it is not contagious." },

  { id:741, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Alopecia areata is best described as:",
    question_es:"La alopecia areata se describe mejor como:",
    options:["Hair loss caused by a fungal scalp infection","Patchy, non-scarring hair loss believed to be caused by an autoimmune response","Permanent hair loss from severe chemical damage","Hair thinning from nutritional deficiency only"],
    options_es:["Pérdida de cabello causada por una infección fúngica del cuero cabelludo","Pérdida de cabello irregular y sin cicatrices que se cree es causada por una respuesta autoinmune","Pérdida de cabello permanente por daño químico severo","Adelgazamiento del cabello solo por deficiencia nutricional"],
    correct:1,
    explanation:"Alopecia areata is a non-scarring, autoimmune-related condition causing patchy hair loss; cosmetologists should recognize it and suggest physician evaluation." },

  { id:742, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Tinea versicolor is a fungal skin condition that causes:",
    question_es:"La tiña versicolor es una condición cutánea fúngica que causa:",
    options:["Deep painful nodules under the skin","Discolored (lighter or darker) patches on the skin due to Malassezia overgrowth","Severe blistering along nerve pathways","Open sores with bacterial discharge"],
    options_es:["Nódulos dolorosos profundos bajo la piel","Parches decolorados (más claros o más oscuros) en la piel debido al crecimiento excesivo de Malassezia","Formación severa de ampollas a lo largo de las vías nerviosas","Llagas abiertas con secreción bacteriana"],
    correct:1,
    explanation:"Tinea versicolor (pityriasis versicolor) causes discolored skin patches due to Malassezia overgrowth; it is not highly contagious under normal salon contact." },

  { id:743, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Herpes zoster (shingles) is caused by:",
    question_es:"El herpes zóster (culebrilla) es causado por:",
    options:["Herpes simplex virus type 1","The varicella-zoster virus (the same virus that causes chickenpox) reactivating","A bacterial skin infection","A fungal skin reaction to chemical products"],
    options_es:["Virus del herpes simple tipo 1","El virus varicela-zóster (el mismo que causa la varicela) reactivándose","Una infección bacteriana de la piel","Una reacción fúngica de la piel a los productos químicos"],
    correct:1,
    explanation:"Shingles occurs when the varicella-zoster virus (dormant after a prior chickenpox infection) reactivates; it causes a painful blistering rash along nerve pathways and is contagious to non-immune individuals." },

  { id:744, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetologist notices a client has warts on their hands. Warts are caused by:",
    question_es:"Un cosmetólogo nota que un cliente tiene verrugas en las manos. Las verrugas son causadas por:",
    options:["A fungal skin infection","The human papillomavirus (HPV)","A bacterial skin infection","An autoimmune skin disorder"],
    options_es:["Una infección fúngica de la piel","El virus del papiloma humano (VPH)","Una infección bacteriana de la piel","Un trastorno autoinmune de la piel"],
    correct:1,
    explanation:"Warts (verrucae) are caused by the human papillomavirus (HPV); they are mildly contagious through direct contact and a cosmetologist should use standard precautions." },

  { id:745, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The term 'pathogenicity' refers to:",
    question_es:"El término 'patogenicidad' se refiere a:",
    options:["The size or physical shape of a microorganism","The ability of a microorganism to cause disease in a host","The speed at which bacteria reproduce under ideal conditions","The visible color of a bacterial culture on a petri dish"],
    options_es:["El tamaño o forma física de un microorganismo","La capacidad de un microorganismo de causar enfermedad en un huésped","La velocidad a la que las bacterias se reproducen bajo condiciones ideales","El color visible de un cultivo bacteriano en una placa de Petri"],
    correct:1,
    explanation:"Pathogenicity is an organism's capacity to cause disease; highly pathogenic organisms cause illness in most exposed hosts." },

  { id:746, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Virulence' describes:",
    question_es:"La 'virulencia' describe:",
    options:["The number of viral particles in a sample","The degree or severity of disease caused by a pathogen at a given dose","The speed at which a virus replicates in host cells","Whether a virus spreads through airborne or droplet routes"],
    options_es:["El número de partículas virales en una muestra","El grado o gravedad de la enfermedad causada por un patógeno en una dosis dada","La velocidad a la que un virus se replica en las células huésped","Si un virus se propaga por rutas aéreas o de gotitas"],
    correct:1,
    explanation:"Virulence is the degree of pathogenicity — how severe the disease is relative to the infectious dose; a highly virulent pathogen causes serious disease at low doses." },

  { id:747, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The 'chain of infection' represents the sequence of events required for disease to spread. Salon sanitation protocols aim to break this chain primarily at:",
    question_es:"La 'cadena de infección' representa la secuencia de eventos necesarios para que una enfermedad se propague. Los protocolos de saneamiento del salón tienen como objetivo interrumpir esta cadena principalmente en:",
    options:["The genetic material of the pathogen","The mode of transmission (via implements, surfaces, or contact)","The client's susceptibility to infection","The pathogen's ability to replicate outside a host"],
    options_es:["El material genético del patógeno","El modo de transmisión (a través de implementos, superficies o contacto)","La susceptibilidad del cliente a la infección","La capacidad del patógeno para replicarse fuera de un huésped"],
    correct:1,
    explanation:"Disinfecting implements, cleaning surfaces, and proper hand hygiene break the mode of transmission link in the chain of infection." },

  { id:748, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Quaternary ammonium compounds (quats) used as salon disinfectants are:",
    question_es:"Los compuestos de amonio cuaternario (quats) utilizados como desinfectantes de salón son:",
    options:["Effective sterilants that destroy all microbial life including spores","Broad-spectrum disinfectants effective against bacteria, fungi, and some viruses but NOT spores","Antiseptics safe for use directly on client skin","Only effective against gram-positive bacteria"],
    options_es:["Esterilizantes efectivos que destruyen toda la vida microbiana, incluidas las esporas","Desinfectantes de amplio espectro efectivos contra bacterias, hongos y algunos virus, pero NO contra las esporas","Antisépticos seguros para usar directamente en la piel del cliente","Solo efectivos contra las bacterias grampositivas"],
    correct:1,
    explanation:"Quaternary ammonium compounds are broad-spectrum disinfectants effective against bacteria, fungi, and many viruses; they do not destroy bacterial spores." },

  { id:749, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"High-level disinfection kills all bacteria, fungi, and viruses but:",
    question_es:"La desinfección de alto nivel mata todas las bacterias, hongos y virus, pero:",
    options:["Also destroys all bacterial endospores","Does not reliably destroy all bacterial endospores — sterilization is needed for that","Is the same level of kill as sterilization","Only works on metal implements, not plastic"],
    options_es:["También destruye todas las endosporas bacterianas","No destruye de manera confiable todas las endosporas bacterianas — para eso se necesita esterilización","Es el mismo nivel de eliminación que la esterilización","Solo funciona en implementos metálicos, no en plástico"],
    correct:1,
    explanation:"High-level disinfection kills all vegetative organisms but not reliably all bacterial endospores; sterilization is required to eliminate spores." },

  { id:750, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Resident flora' on the skin refers to:",
    question_es:"La 'flora residente' en la piel se refiere a:",
    options:["Plants and flowers kept in the salon","Microorganisms that permanently live on the skin without causing disease under normal conditions","Pathogenic bacteria found in salon products","Only bacteria that are introduced from outside the body"],
    options_es:["Plantas y flores que se mantienen en el salón","Microorganismos que viven permanentemente en la piel sin causar enfermedades en condiciones normales","Bacterias patógenas encontradas en los productos del salón","Solo bacterias que se introducen desde fuera del cuerpo"],
    correct:1,
    explanation:"Resident (normal) flora are permanent microbial communities on the skin that coexist without causing harm and can actually protect against pathogens." },

  { id:751, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Transient flora' on the skin differs from resident flora in that transient flora:",
    question_es:"La 'flora transitoria' en la piel se diferencia de la flora residente en que la flora transitoria:",
    options:["Permanently colonizes the skin and cannot be removed","Is temporarily acquired from environmental contact and can be removed through proper hand washing","Is always more pathogenic than resident flora","Lives only in the bloodstream, not on the skin surface"],
    options_es:["Coloniza permanentemente la piel y no puede eliminarse","Se adquiere temporalmente del contacto ambiental y puede eliminarse mediante el lavado adecuado de manos","Es siempre más patógena que la flora residente","Vive solo en el torrente sanguíneo, no en la superficie de la piel"],
    correct:1,
    explanation:"Transient flora are temporarily picked up from environmental contact; they can be removed through proper hand washing, unlike permanent resident flora." },

  { id:752, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Wet heat sterilization (autoclave) is preferred over dry heat sterilization because:",
    question_es:"La esterilización por calor húmedo (autoclave) es preferida sobre la esterilización por calor seco porque:",
    options:["Dry heat is faster and less expensive to operate","Moist steam transfers heat more efficiently, achieving sterilization at lower temperatures in less time","Dry heat destroys a broader spectrum of microorganisms","Autoclaves are cheaper and easier to maintain"],
    options_es:["El calor seco es más rápido y económico de operar","El vapor húmedo transfiere el calor más eficientemente, logrando la esterilización a temperaturas más bajas en menos tiempo","El calor seco destruye un espectro más amplio de microorganismos","Los autoclaves son más baratos y fáciles de mantener"],
    correct:1,
    explanation:"Moist heat (steam) is more efficient at killing microorganisms than dry heat, requiring lower temperatures and shorter exposure times." },

  { id:753, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An 'epidemic' is best described as:",
    question_es:"Una 'epidemia' se describe mejor como:",
    options:["A single isolated case of illness in a salon","An outbreak of disease affecting more people than expected in a given community or region","A disease found only in one specific country","A disease that exclusively affects salon and spa professionals"],
    options_es:["Un caso aislado de enfermedad en un salón","Un brote de enfermedad que afecta a más personas de lo esperado en una comunidad o región determinada","Una enfermedad que se encuentra solo en un país específico","Una enfermedad que afecta exclusivamente a los profesionales de salones y spas"],
    correct:1,
    explanation:"An epidemic is a significant increase in disease cases above what is normally expected in a population or geographic area." },

  { id:754, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Natural immunity' is immunity acquired through:",
    question_es:"La 'inmunidad natural' es la inmunidad adquirida a través de:",
    options:["Receiving a vaccine against a specific disease","Actual exposure to and recovery from a disease, or transfer of maternal antibodies","Taking prescribed vitamin or mineral supplements","Genetic engineering of immune cells"],
    options_es:["Recibir una vacuna contra una enfermedad específica","La exposición real y recuperación de una enfermedad, o la transferencia de anticuerpos maternos","Tomar suplementos vitamínicos o minerales recetados","Ingeniería genética de células inmunitarias"],
    correct:1,
    explanation:"Natural immunity develops through actual infection and recovery, or from passive transfer of maternal antibodies; it differs from vaccine-induced immunity." },

  { id:755, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"In a salon, controlling the work environment to reduce infection risk includes:",
    question_es:"En un salón, controlar el entorno de trabajo para reducir el riesgo de infección incluye:",
    options:["Keeping the salon very warm to prevent pathogen survival","Ensuring good ventilation, adequate lighting, proper waste disposal, and clean water supply","Restricting client access to reduce the number of people in the salon","Displaying motivational posters about hygiene for clients to read"],
    options_es:["Mantener el salón muy caliente para evitar la supervivencia de patógenos","Asegurar buena ventilación, iluminación adecuada, eliminación adecuada de desechos y suministro de agua limpia","Restringir el acceso de los clientes para reducir el número de personas en el salón","Mostrar carteles motivacionales sobre higiene para que los clientes los lean"],
    correct:1,
    explanation:"A safe work environment requires good ventilation, adequate lighting, proper waste disposal, and a clean water supply — all of which reduce infection risk." },

  { id:756, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Texas cosmetology establishments that repeatedly fail sanitation inspections may face:",
    question_es:"Los establecimientos de cosmetología de Texas que reprueban repetidamente las inspecciones de saneamiento pueden enfrentar:",
    options:["Only a small written warning with no further consequences","Escalating penalties including potential suspension or revocation of the establishment license","Only a fine with no license impact","No consequences if the owner agrees to improve within 90 days"],
    options_es:["Solo una pequeña advertencia escrita sin más consecuencias","Sanciones crecientes que incluyen la posible suspensión o revocación de la licencia del establecimiento","Solo una multa sin impacto en la licencia","Sin consecuencias si el propietario acepta mejorar dentro de 90 días"],
    correct:1,
    explanation:"Repeated sanitation failures lead to escalating penalties, including potential suspension or revocation of the establishment license by TDLR." },

  { id:757, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following CANNOT be disinfected and must be discarded after a single client use?",
    question_es:"¿Cuál de los siguientes NO puede desinfectarse y debe descartarse después de usarse con un solo cliente?",
    options:["Stainless steel scissors","A wooden cuticle stick or emery board","A metal nail pusher","A glass manicure bowl"],
    options_es:["Tijeras de acero inoxidable","Un palito de cutícula de madera o lima de cartón","Un empujador de cutícula metálico","Un tazón de manicura de vidrio"],
    correct:1,
    explanation:"Porous items like wooden cuticle sticks and emery boards cannot be effectively disinfected and must be disposed of after single-client use." },

  { id:758, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following best describes 'sanitization' of a salon surface?",
    question_es:"¿Cuál de los siguientes describe mejor el 'saneamiento' de una superficie del salón?",
    options:["Completely eliminating all microbial life including spores","Reducing microbial contamination to a safe public health level (typically 99.9% bacterial reduction)","Killing all fungi and viruses but not bacteria","Achieving the same level of kill as hospital-grade disinfection"],
    options_es:["Eliminar completamente toda la vida microbiana, incluidas las esporas","Reducir la contaminación microbiana a un nivel seguro de salud pública (típicamente 99.9% de reducción bacteriana)","Matar todos los hongos y virus pero no las bacterias","Lograr el mismo nivel de eliminación que la desinfección de grado hospitalario"],
    correct:1,
    explanation:"Sanitization reduces bacteria to a safe level per public health standards; it is less rigorous than disinfection and far less rigorous than sterilization." },

  { id:759, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"When preparing a disinfectant solution for salon use, you should always:",
    question_es:"Al preparar una solución desinfectante para uso en salón, siempre debe:",
    options:["Double the concentration for extra effectiveness","Follow the manufacturer's instructions exactly for dilution ratio, contact time, and safety precautions","Use the hottest water available to increase effectiveness","Mix several disinfectants together for a broader spectrum kill"],
    options_es:["Duplicar la concentración para mayor efectividad","Seguir exactamente las instrucciones del fabricante para la proporción de dilución, el tiempo de contacto y las precauciones de seguridad","Usar el agua más caliente disponible para aumentar la efectividad","Mezclar varios desinfectantes juntos para una eliminación de espectro más amplio"],
    correct:1,
    explanation:"Always follow manufacturer instructions precisely; under- or over-dilution can reduce efficacy, and mixing disinfectants can create toxic chemical reactions." },

  { id:760, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A disinfectant that should NOT be used on a salon implement is one that is:",
    question_es:"Un desinfectante que NO debe usarse en un implemento de salón es aquel que está:",
    options:["Recently purchased and within its expiration date","Past its expiration date, improperly diluted, or visibly contaminated","Stored in a cool, dark location away from sunlight","EPA-registered and labeled for use on salon implements"],
    options_es:["Comprado recientemente y dentro de su fecha de vencimiento","Pasado su fecha de vencimiento, diluido incorrectamente o visiblemente contaminado","Almacenado en un lugar fresco y oscuro lejos de la luz solar","Registrado en la EPA y etiquetado para uso en implementos de salón"],
    correct:1,
    explanation:"Expired, improperly diluted, or contaminated disinfectants cannot be relied upon for efficacy and must be discarded." },

  { id:761, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An SDS (Safety Data Sheet) section labeled 'First Aid Measures' provides:",
    question_es:"Una sección de la Hoja de Datos de Seguridad (SDS) etiquetada 'Primeros Auxilios' proporciona:",
    options:["Emergency contact information for the manufacturer only","Instructions for responding to chemical exposure by route (skin, eyes, ingestion, inhalation)","A list of which chemicals can be safely mixed together","The chemical formula and molecular weight of the substance"],
    options_es:["Solo información de contacto de emergencia del fabricante","Instrucciones para responder a la exposición química por vía (piel, ojos, ingestión, inhalación)","Una lista de qué químicos se pueden mezclar de manera segura","La fórmula química y el peso molecular de la sustancia"],
    correct:1,
    explanation:"The SDS First Aid Measures section provides specific instructions for managing exposure through each route: skin contact, eye contact, ingestion, and inhalation." },

  { id:762, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Personal protective equipment (PPE) used in a salon primarily serves to:",
    question_es:"El equipo de protección personal (EPP) utilizado en un salón sirve principalmente para:",
    options:["Improve the cosmetologist's professional appearance","Create a physical barrier protecting against infectious material and chemical exposure","Replace the need for proper implement disinfection","Indicate professional certification status to clients"],
    options_es:["Mejorar la apariencia profesional del cosmetólogo","Crear una barrera física que proteja contra material infeccioso y exposición química","Reemplazar la necesidad de la desinfección adecuada de implementos","Indicar el estado de certificación profesional a los clientes"],
    correct:1,
    explanation:"PPE creates a physical barrier protecting both practitioners and clients from pathogens, chemicals, and other occupational hazards." },

  { id:763, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Mixing bleach (sodium hypochlorite) with an acidic cleaner or ammonia-based product creates:",
    question_es:"Mezclar blanqueador (hipoclorito de sodio) con un limpiador ácido o un producto a base de amoníaco crea:",
    options:["A stronger and more effective disinfectant","Toxic chlorine or chloramine gases that are hazardous to breathe","A safe, pH-neutral cleaning solution","A diluted, less effective product that still can be used"],
    options_es:["Un desinfectante más fuerte y más efectivo","Gases tóxicos de cloro o cloramina que son peligrosos para respirar","Una solución de limpieza segura y de pH neutro","Un producto diluido y menos efectivo que aún puede usarse"],
    correct:1,
    explanation:"Mixing bleach with acids or ammonia produces toxic chlorine or chloramine gases; never mix bleach with other cleaning products." },

  { id:764, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"'Universal precautions' (the predecessor to standard precautions) required treating all blood and certain body fluids as:",
    question_es:"Las 'precauciones universales' (el predecesor de las precauciones estándar) requería tratar toda la sangre y ciertos fluidos corporales como:",
    options:["Safe for contact since most people are healthy","Potentially infectious regardless of the person's known health status","Infectious only when the client discloses a bloodborne infection","Infectious only if the fluid is visible to the naked eye"],
    options_es:["Seguros para el contacto ya que la mayoría de las personas están sanas","Potencialmente infecciosos independientemente del estado de salud conocido de la persona","Infecciosos solo cuando el cliente revela una infección de transmisión sanguínea","Infecciosos solo si el fluido es visible a simple vista"],
    correct:1,
    explanation:"Universal precautions treated all blood and specified body fluids as potentially infectious regardless of a person's apparent or known health status." },

  { id:765, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The term 'biocidal' refers to a substance that:",
    question_es:"El término 'biocida' se refiere a una sustancia que:",
    options:["Only cleans surfaces by removing dirt","Kills or inactivates living organisms, broadly speaking","Only inhibits microbial growth without killing","Promotes the growth of beneficial bacteria"],
    options_es:["Solo limpia superficies eliminando la suciedad","Mata o inactiva organismos vivos, en términos generales","Solo inhibe el crecimiento microbiano sin matar","Promueve el crecimiento de bacterias beneficiosas"],
    correct:1,
    explanation:"A biocidal agent kills or inactivates living organisms; biocidal products include disinfectants, antiseptics, fungicides, and virucidal agents." },

  { id:766, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetology salon must maintain a clean, sanitary environment to:",
    question_es:"Un salón de cosmetología debe mantener un entorno limpio y sanitario para:",
    options:["Only improve the overall aesthetic appeal of the salon","Comply with TDLR regulations and protect the health of clients and staff","Attract higher-paying clients exclusively","Reduce the cost of disinfectant and cleaning products over time"],
    options_es:["Solo mejorar el atractivo estético general del salón","Cumplir con las regulaciones de TDLR y proteger la salud de los clientes y el personal","Atraer exclusivamente a clientes con mayor poder adquisitivo","Reducir el costo de los productos de desinfección y limpieza a lo largo del tiempo"],
    correct:1,
    explanation:"Sanitation compliance is legally required by TDLR and fundamentally exists to protect the health and safety of clients and cosmetology staff." },

  { id:767, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following correctly describes the difference between disinfection and sterilization in a salon context?",
    question_es:"¿Cuál de los siguientes describe correctamente la diferencia entre desinfección y esterilización en el contexto de un salón?",
    options:["Sterilization is a lower level of decontamination than disinfection","Disinfection reduces pathogens to safe levels; sterilization destroys all forms of microbial life including resistant spores","Disinfection is only used in hospital operating rooms","Sterilization can be fully achieved in a salon using UV light alone"],
    options_es:["La esterilización es un nivel más bajo de descontaminación que la desinfección","La desinfección reduce los patógenos a niveles seguros; la esterilización destruye todas las formas de vida microbiana, incluidas las esporas resistentes","La desinfección solo se usa en quirófanos hospitalarios","La esterilización puede lograrse completamente en un salón usando solo luz UV"],
    correct:1,
    explanation:"Disinfection kills most pathogens to safe levels; sterilization achieves complete elimination of all microbial life, including the most resistant bacterial endospores." },

  { id:768, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An effective salon infection control program requires all of the following EXCEPT:",
    question_es:"Un programa efectivo de control de infecciones en un salón requiere todo lo siguiente EXCEPTO:",
    options:["Properly cleaning and disinfecting implements between every client","Replacing all metal implements with disposable single-use implements for every service","Washing hands before and after each client service","Storing disinfected implements in a clean, covered container"],
    options_es:["Limpiar y desinfectar adecuadamente los implementos entre cada cliente","Reemplazar todos los implementos metálicos con implementos desechables de un solo uso para cada servicio","Lavarse las manos antes y después de cada servicio al cliente","Guardar los implementos desinfectados en un recipiente limpio y tapado"],
    correct:1,
    explanation:"Metal implements can be reused after proper cleaning and disinfection; replacing all metal implements with single-use disposables is not required by salon infection control protocols." },
]

// Validate
console.log(`Questions to append: ${questions.length}`)
for (const q of questions) {
  if (q.options.length !== 4 || q.options_es.length !== 4) throw new Error(`id ${q.id}: option count error`)
  if (q.correct < 0 || q.correct > 3) throw new Error(`id ${q.id}: correct out of range`)
}
console.log('Validation passed — all questions have 4 options and valid correct index.')

// Build lines to append
const newLines = [
  '',
  '// ─── SANITATION & INFECTION CONTROL EXPANSION (ids 661–768) ───',
]
for (const q of questions) {
  const line = `  { id:${q.id}, topic:"${q.topic}", topic_es:"${q.topic_es}", psi_topic:"${q.psi_topic}", psi_topic_es:"${q.psi_topic_es}", question:"${q.question}", question_es:"${q.question_es}", options:${JSON.stringify(q.options)}, options_es:${JSON.stringify(q.options_es)}, correct:${q.correct}, explanation:"${q.explanation}" },`
  newLines.push(line)
}

// Read file, replace closing ] with new content + ]
let content = readFileSync(FILE, 'utf8')
if (!content.trimEnd().endsWith(']')) throw new Error('Unexpected file ending — aborting.')
content = content.trimEnd().slice(0, -1)
content += newLines.join('\n') + '\n]'
writeFileSync(FILE, content, 'utf8')
console.log('Done. questions.js updated.')
