// Pass A: append 60 Licensing & Regulation questions (ids 601–660) to questions.js
import { readFileSync, writeFileSync } from 'fs'

const FILE = new URL('../src/questions.js', import.meta.url).pathname.replace(/^\/([A-Z]:)/, '$1')

const T  = 'Texas TDLR Laws & Regulations'
const TE = 'Leyes y Regulaciones de Texas TDLR'
const P  = 'Licensing & Regulation'
const PE = 'Licencias y Regulaciones'

const questions = [
  { id:601, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"How many hours of training are required to obtain a Texas cosmetology operator (Class A) license?",
    question_es:"¿Cuántas horas de capacitación se requieren para obtener una licencia de operador de cosmetología Clase A de Texas?",
    options:["500 hours","1,000 hours","1,500 hours","2,000 hours"],
    options_es:["500 horas","1,000 horas","1,500 horas","2,000 horas"],
    correct:2,
    explanation:"Texas requires 1,500 hours at a TDLR-approved cosmetology school for a Class A operator license." },

  { id:602, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which Texas state agency issues and regulates cosmetology licenses?",
    question_es:"¿Qué agencia estatal de Texas emite y regula las licencias de cosmetología?",
    options:["Texas Department of Health","Texas Department of Licensing and Regulation (TDLR)","Texas State Board of Cosmetology","Texas Medical Board"],
    options_es:["Departamento de Salud de Texas","Departamento de Licencias y Regulación de Texas (TDLR)","Junta Estatal de Cosmetología de Texas","Junta Médica de Texas"],
    correct:1,
    explanation:"TDLR (Texas Department of Licensing and Regulation) is the regulatory authority for cosmetology in Texas." },

  { id:603, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"How often must a Texas cosmetology operator license be renewed?",
    question_es:"¿Con qué frecuencia debe renovarse una licencia de operador de cosmetología de Texas?",
    options:["Every year","Every 2 years","Every 3 years","Every 5 years"],
    options_es:["Cada año","Cada 2 años","Cada 3 años","Cada 5 años"],
    correct:1,
    explanation:"Texas cosmetology licenses must be renewed biennially — every 2 years." },

  { id:604, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"How many continuing education (CE) hours are required for Texas cosmetology license renewal?",
    question_es:"¿Cuántas horas de educación continua se requieren para renovar la licencia de cosmetología de Texas?",
    options:["2 hours","4 hours","8 hours","16 hours"],
    options_es:["2 horas","4 horas","8 horas","16 horas"],
    correct:1,
    explanation:"Texas requires 4 hours of TDLR-approved continuing education for each 2-year renewal period." },

  { id:605, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"What is the minimum age to apply for a Texas cosmetology operator license?",
    question_es:"¿Cuál es la edad mínima para solicitar una licencia de operador de cosmetología de Texas?",
    options:["14 years old","16 years old","18 years old","21 years old"],
    options_es:["14 años","16 años","18 años","21 años"],
    correct:1,
    explanation:"Applicants must be at least 16 years old to apply for a Texas cosmetology operator license." },

  { id:606, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Where must a Texas cosmetology license be displayed in a salon?",
    question_es:"¿Dónde debe exhibirse una licencia de cosmetología de Texas en un salón?",
    options:["Stored in a filing cabinet for inspection only","In a conspicuous place visible to clients","Only in the manager's private office","Shown only when a client requests it"],
    options_es:["Guardada en un archivero solo para inspección","En un lugar visible para los clientes","Solo en la oficina privada del gerente","Mostrada solo cuando un cliente la solicite"],
    correct:1,
    explanation:"Texas law requires cosmetology licenses to be displayed in a conspicuous location visible to clients at all times." },

  { id:607, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Before opening a cosmetology salon in Texas, the establishment must obtain:",
    question_es:"Antes de abrir un salón de cosmetología en Texas, el establecimiento debe obtener:",
    options:["Only individual operator licenses for each employee","An establishment license from TDLR","Only a city business license","A health department permit only"],
    options_es:["Solo licencias de operador individuales para cada empleado","Una licencia de establecimiento de TDLR","Solo una licencia comercial municipal","Solo un permiso del departamento de salud"],
    correct:1,
    explanation:"Salon establishments must obtain a TDLR establishment license in addition to individual practitioner licenses." },

  { id:608, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"What is the consequence of performing cosmetology services in Texas without a valid license?",
    question_es:"¿Cuál es la consecuencia de realizar servicios de cosmetología en Texas sin una licencia válida?",
    options:["A verbal warning for the first offense only","Civil and/or administrative penalties","A small fine with no other consequences","No penalty when working inside a licensed salon"],
    options_es:["Solo una advertencia verbal para la primera infracción","Sanciones civiles y/o administrativas","Una pequeña multa sin otras consecuencias","Sin penalización cuando se trabaja dentro de un salón con licencia"],
    correct:1,
    explanation:"Practicing without a license is a violation subject to civil penalties and administrative enforcement by TDLR." },

  { id:609, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which organization administers the Texas cosmetology written and practical licensing exams?",
    question_es:"¿Qué organización administra los exámenes escritos y prácticos de licencias de cosmetología de Texas?",
    options:["TDLR directly","PSI Services LLC","The cosmetology school attended","The Texas Medical Board"],
    options_es:["TDLR directamente","PSI Services LLC","La escuela de cosmetología a la que asistió","La Junta Médica de Texas"],
    correct:1,
    explanation:"PSI Services LLC administers the written and practical licensing exams for Texas cosmetology on behalf of TDLR." },

  { id:610, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Cosmetology students performing services on the public at a school clinic must work:",
    question_es:"Los estudiantes de cosmetología que realizan servicios al público en una clínica escolar deben trabajar:",
    options:["Without supervision after completing 500 hours","Under direct supervision of a licensed cosmetology instructor","Supervised only by another advanced student","At any time the school is open without restriction"],
    options_es:["Sin supervisión después de completar 500 horas","Bajo supervisión directa de un instructor de cosmetología con licencia","Supervisados solo por otro estudiante avanzado","En cualquier momento que la escuela esté abierta sin restricción"],
    correct:1,
    explanation:"Students must be under the direct supervision of a licensed instructor when providing services to the public." },

  { id:611, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A Texas cosmetologist who changes their mailing address must notify TDLR within:",
    question_es:"Un cosmetólogo de Texas que cambia su dirección postal debe notificar a TDLR en un plazo de:",
    options:["30 days","60 days","90 days","1 year"],
    options_es:["30 días","60 días","90 días","1 año"],
    correct:0,
    explanation:"Licensees must notify TDLR of address changes within 30 days to receive important regulatory correspondence." },

  { id:612, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Chemical service records (perm or relaxer formulas applied to clients) must be retained for at least:",
    question_es:"Los registros de servicios químicos (fórmulas de permanente o alisado aplicadas a clientes) deben conservarse por al menos:",
    options:["3 months","6 months","1 year","5 years"],
    options_es:["3 meses","6 meses","1 año","5 años"],
    correct:2,
    explanation:"Texas regulations require chemical service client records to be retained for a minimum of 1 year." },

  { id:613, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"TDLR inspectors may enter and inspect a licensed cosmetology salon:",
    question_es:"Los inspectores de TDLR pueden entrar e inspeccionar un salón de cosmetología con licencia:",
    options:["Only with 48 hours advance written notice","Only during business hours with a scheduled appointment","At any reasonable time without prior notice","Only with a court-issued warrant"],
    options_es:["Solo con 48 horas de aviso escrito previo","Solo durante el horario comercial con una cita programada","En cualquier momento razonable sin previo aviso","Solo con una orden judicial"],
    correct:2,
    explanation:"TDLR has authority to inspect at any reasonable time without advance notice to ensure regulatory compliance." },

  { id:614, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A Texas cosmetology license can be suspended or revoked for:",
    question_es:"Una licencia de cosmetología de Texas puede suspenderse o revocarse por:",
    options:["Having a large and busy client schedule","Repeatedly violating sanitation or professional conduct rules","Working overtime hours in a licensed salon","Charging rates above the posted price list"],
    options_es:["Tener una agenda de clientes grande y ocupada","Violar repetidamente las normas de saneamiento o conducta profesional","Trabajar horas extras en un salón con licencia","Cobrar tarifas por encima de la lista de precios publicada"],
    correct:1,
    explanation:"Repeated or serious regulatory violations are grounds for TDLR to suspend or revoke a license." },

  { id:615, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Under Texas regulations, a cosmetologist must refuse service to a client who has:",
    question_es:"Según las regulaciones de Texas, un cosmetólogo debe negarse a brindar servicio a un cliente que tiene:",
    options:["Dry hair and significant split ends","Mild acne on the forehead only","A communicable disease or open skin lesion in the service area","A minor sunburn on the shoulders"],
    options_es:["Cabello seco y puntas abiertas significativas","Acné leve solo en la frente","Una enfermedad transmisible o una lesión cutánea abierta en el área de servicio","Una quemadura solar leve en los hombros"],
    correct:2,
    explanation:"Services on clients with communicable diseases or open skin lesions are prohibited to protect clients and other salon patrons." },

  { id:616, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A booth renter in a Texas salon is legally classified as:",
    question_es:"Un arrendatario de cabina en un salón de Texas está legalmente clasificado como:",
    options:["An employee of the salon owner entitled to benefits","An independent contractor responsible for their own TDLR license","A student completing required clinic hours","A co-owner with shared establishment license privileges"],
    options_es:["Un empleado del propietario del salón con derecho a beneficios","Un contratista independiente responsable de su propia licencia de TDLR","Un estudiante completando las horas de clínica requeridas","Un copropietario con privilegios compartidos de licencia de establecimiento"],
    correct:1,
    explanation:"Booth renters are independent contractors who must maintain their own valid TDLR license; they are not salon employees." },

  { id:617, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which service is within the scope of practice of a Texas licensed cosmetology operator?",
    question_es:"¿Qué servicio está dentro del alcance de práctica de un operador de cosmetología con licencia de Texas?",
    options:["Performing laser hair removal treatments","Treating diagnosed medical skin conditions","Cutting, coloring, and chemically treating hair","Performing cosmetic surgical procedures"],
    options_es:["Realizar tratamientos de depilación láser","Tratar condiciones médicas de la piel diagnosticadas","Cortar, colorear y tratar químicamente el cabello","Realizar procedimientos cosméticos quirúrgicos"],
    correct:2,
    explanation:"Texas cosmetologists are licensed for hair, skin, and nail beauty services; laser and medical procedures require separate licensure." },

  { id:618, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Tattooing and permanent makeup in Texas require:",
    question_es:"Los tatuajes y el maquillaje permanente en Texas requieren:",
    options:["A standard cosmetology operator license","A separate TDLR license category distinct from cosmetology","No license — they are unregulated activities","Only an esthetician license"],
    options_es:["Una licencia estándar de operador de cosmetología","Una categoría de licencia de TDLR separada, distinta de cosmetología","Ninguna licencia — son actividades no reguladas","Solo una licencia de esteticista"],
    correct:1,
    explanation:"Tattoo artists and permanent makeup practitioners require a separate TDLR license; a cosmetology license does not authorize these services." },

  { id:619, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The minimum passing score on the Texas cosmetology written licensing exam is:",
    question_es:"La puntuación mínima para aprobar el examen escrito de licencias de cosmetología de Texas es:",
    options:["60%","65%","70%","80%"],
    options_es:["60%","65%","70%","80%"],
    correct:2,
    explanation:"Candidates must achieve a minimum score of 70% on the written licensing exam to pass." },

  { id:620, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"To receive a Texas cosmetology license, a candidate must successfully complete:",
    question_es:"Para recibir una licencia de cosmetología de Texas, un candidato debe completar exitosamente:",
    options:["A written exam only","A practical exam only","Both a written exam and a practical skills exam","Neither exam if graduated from a Texas-approved school"],
    options_es:["Solo un examen escrito","Solo un examen práctico","Tanto un examen escrito como un examen práctico de habilidades","Ningún examen si se graduó de una escuela aprobada por Texas"],
    correct:2,
    explanation:"Both a written and practical examination must be passed to obtain a Texas cosmetology license." },

  { id:621, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"How many training hours are required for a Texas esthetician (Class B facial specialty) license?",
    question_es:"¿Cuántas horas de capacitación se requieren para una licencia de esteticista Clase B de Texas?",
    options:["300 hours","500 hours","750 hours","1,500 hours"],
    options_es:["300 horas","500 horas","750 horas","1,500 horas"],
    correct:2,
    explanation:"A Texas Class B esthetician (facial specialty) license requires 750 hours of training at an approved school." },

  { id:622, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"How many training hours are required for a Texas manicurist (nail technician) license?",
    question_es:"¿Cuántas horas de capacitación se requieren para una licencia de manicurista de Texas?",
    options:["300 hours","600 hours","750 hours","1,000 hours"],
    options_es:["300 horas","600 horas","750 horas","1,000 horas"],
    correct:1,
    explanation:"A Texas manicurist license requires 600 training hours at a TDLR-approved school." },

  { id:623, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"To apply for a Texas cosmetology instructor license, an applicant must first hold:",
    question_es:"Para solicitar una licencia de instructor de cosmetología de Texas, el solicitante primero debe tener:",
    options:["Only a high school diploma","A cosmetology operator license plus required instructor training hours","A university degree in education","500 hours of cosmetology training only"],
    options_es:["Solo un diploma de preparatoria","Una licencia de operador de cosmetología más las horas de capacitación requeridas para instructor","Un título universitario en educación","Solo 500 horas de capacitación en cosmetología"],
    correct:1,
    explanation:"Instructor applicants must hold a current cosmetology operator license and complete additional instructor-specific training hours." },

  { id:624, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"If a Texas cosmetology license has been expired and unrenewed for more than 1 year, the licensee must:",
    question_es:"Si una licencia de cosmetología de Texas ha estado vencida y sin renovar por más de 1 año, el titular debe:",
    options:["Pay a late fee and renew online as usual","Retake and pass both the written and practical licensing exams","Retake only the practical exam","Submit a written explanation to TDLR"],
    options_es:["Pagar una multa por retraso y renovar en línea como de costumbre","Volver a tomar y aprobar tanto el examen escrito como el práctico","Volver a tomar solo el examen práctico","Enviar una explicación escrita a TDLR"],
    correct:1,
    explanation:"Licenses lapsed more than 1 year require full retesting (written and practical) before the license can be reinstated." },

  { id:625, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A Texas military spouse holding a valid out-of-state cosmetology license may:",
    question_es:"Un cónyuge militar de Texas que tiene una licencia de cosmetología válida de otro estado puede:",
    options:["Practice immediately in Texas without any license","Apply for a Texas license by endorsement through TDLR","Only work as an unlicensed assistant","Must complete all 1,500 Texas training hours before licensure"],
    options_es:["Ejercer inmediatamente en Texas sin ninguna licencia","Solicitar una licencia de Texas mediante endoso a través de TDLR","Solo trabajar como asistente sin licencia","Debe completar las 1,500 horas de capacitación de Texas antes de obtener la licencia"],
    correct:1,
    explanation:"Texas offers an expedited endorsement process for military spouses who hold equivalent out-of-state cosmetology licenses." },

  { id:626, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The Texas cosmetology administrative rules are found in:",
    question_es:"Las reglas administrativas de cosmetología de Texas se encuentran en:",
    options:["Texas Health and Safety Code only","Texas Administrative Code (TAC), Title 16, Chapter 83","Texas Penal Code, Chapter 12","Texas Labor Code, Chapter 201"],
    options_es:["Solo el Código de Salud y Seguridad de Texas","Código Administrativo de Texas (TAC), Título 16, Capítulo 83","Código Penal de Texas, Capítulo 12","Código Laboral de Texas, Capítulo 201"],
    correct:1,
    explanation:"TAC Title 16, Chapter 83 contains TDLR rules governing cosmetology practices, schools, and establishments in Texas." },

  { id:627, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The primary statute governing cosmetology licensing in Texas is:",
    question_es:"El estatuto principal que rige las licencias de cosmetología en Texas es:",
    options:["Texas Occupations Code Chapter 53","Texas Occupations Code Chapter 1603","Texas Government Code Chapter 481","Texas Health and Safety Code Chapter 83"],
    options_es:["Capítulo 53 del Código de Ocupaciones de Texas","Capítulo 1603 del Código de Ocupaciones de Texas","Capítulo 481 del Código de Gobierno de Texas","Capítulo 83 del Código de Salud y Seguridad de Texas"],
    correct:1,
    explanation:"Texas Occupations Code Chapter 1603 is the primary law governing cosmetology licensing and regulation in Texas." },

  { id:628, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Cosmetology salon advertisements in Texas must display:",
    question_es:"Los anuncios de salones de cosmetología en Texas deben mostrar:",
    options:["The owner's social security number","The TDLR-issued establishment license number","The total number of licensed employees","The salon's annual revenue"],
    options_es:["El número de seguro social del propietario","El número de licencia de establecimiento emitido por TDLR","El número total de empleados con licencia","Los ingresos anuales del salón"],
    correct:1,
    explanation:"Texas requires cosmetology salon advertisements to display the TDLR-issued establishment license number." },

  { id:629, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetology student who transfers between TDLR-approved schools may:",
    question_es:"Un estudiante de cosmetología que se transfiere entre escuelas aprobadas por TDLR puede:",
    options:["Lose all previously accumulated hours and start over","Transfer documented training hours to the new approved school","Only retake hours in subjects with failing grades","Retake all theory classroom hours regardless of prior completion"],
    options_es:["Perder todas las horas acumuladas previamente y empezar de cero","Transferir las horas de capacitación documentadas a la nueva escuela aprobada","Solo repetir las horas en materias con calificaciones reprobatorias","Repetir todas las horas de teoría independientemente de la finalización previa"],
    correct:1,
    explanation:"Documented training hours from one TDLR-approved cosmetology school can be transferred to another approved school." },

  { id:630, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The primary purpose of cosmetology licensing in Texas is to:",
    question_es:"El propósito principal de las licencias de cosmetología en Texas es:",
    options:["Generate revenue for the state","Protect the health, safety, and welfare of the public","Limit competition among salon businesses","Guarantee higher wages for cosmetology professionals"],
    options_es:["Generar ingresos para el estado","Proteger la salud, seguridad y bienestar del público","Limitar la competencia entre los salones","Garantizar salarios más altos para los profesionales de cosmetología"],
    correct:1,
    explanation:"Occupational licensing exists to ensure practitioners meet minimum competency and safety standards to protect the public." },

  { id:631, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"To renew a Texas cosmetology license, the licensee must:",
    question_es:"Para renovar una licencia de cosmetología de Texas, el titular debe:",
    options:["Pay only the biennial renewal fee","Complete required CE hours and pay the biennial renewal fee","Pass the written licensing exam again","Resubmit fingerprints and a new background check each cycle"],
    options_es:["Pagar solo la tarifa de renovación bienal","Completar las horas de EC requeridas y pagar la tarifa de renovación bienal","Aprobar el examen escrito de licencias nuevamente","Reenviar las huellas dactilares y una nueva verificación de antecedentes en cada ciclo"],
    correct:1,
    explanation:"Renewal requires completing 4 hours of TDLR-approved CE and paying the renewal fee before the expiration date." },

  { id:632, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"What must a Texas cosmetology salon post in a location visible to clients?",
    question_es:"¿Qué debe publicar un salón de cosmetología de Texas en un lugar visible para los clientes?",
    options:["Personal phone numbers of all staff","A price list for all services offered","Payroll and employee benefit information","Monthly revenue statements"],
    options_es:["Números de teléfono personales de todo el personal","Una lista de precios de todos los servicios ofrecidos","Información de nómina y beneficios de los empleados","Estados de ingresos mensuales"],
    correct:1,
    explanation:"Texas regulations require salons to display a price list for services where it is visible to clients." },

  { id:633, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetologist operating a salon out of their private home in Texas must:",
    question_es:"Un cosmetólogo que opera un salón desde su casa particular en Texas debe:",
    options:["Operate without any establishment license since it is a private residence","Obtain a separate TDLR establishment license for the home-based salon","Only notify the local homeowners association","Obtain only a city permit with no TDLR license required"],
    options_es:["Operar sin ninguna licencia de establecimiento ya que es una residencia privada","Obtener una licencia de establecimiento separada de TDLR para el salón en el hogar","Solo notificar a la asociación local de propietarios de viviendas","Obtener solo un permiso municipal sin requerir licencia de TDLR"],
    correct:1,
    explanation:"Even home-based cosmetology salons must obtain a TDLR establishment license to operate legally in Texas." },

  { id:634, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Providing cosmetology services in a facility not licensed as a cosmetology establishment in Texas is:",
    question_es:"Proporcionar servicios de cosmetología en una instalación que no está licenciada como establecimiento de cosmetología en Texas es:",
    options:["Permitted if the individual cosmetologist holds a valid license","A violation subject to penalties regardless of individual licensure","Allowed with written client consent","Legal only for mobile services at client residences"],
    options_es:["Permitido si el cosmetólogo individual tiene una licencia válida","Una infracción sujeta a sanciones independientemente de la licencia individual","Permitido con el consentimiento escrito del cliente","Legal solo para servicios móviles en las residencias de los clientes"],
    correct:1,
    explanation:"All cosmetology services must be performed in a properly licensed TDLR establishment; individual licensure does not exempt this requirement." },

  { id:635, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A client complaint about a Texas licensed cosmetologist should be filed with:",
    question_es:"Una queja de un cliente sobre un cosmetólogo con licencia de Texas debe presentarse ante:",
    options:["The Better Business Bureau only","TDLR's enforcement division","The local police department","The salon owner exclusively"],
    options_es:["Solo la Oficina de Mejores Negocios","La división de cumplimiento de TDLR","El departamento de policía local","Solo el propietario del salón"],
    correct:1,
    explanation:"TDLR's enforcement division investigates complaints against licensed cosmetologists and establishments." },

  { id:636, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"In a licensed Texas cosmetology salon, responsibility for maintaining sanitation standards falls on:",
    question_es:"En un salón de cosmetología con licencia de Texas, la responsabilidad de mantener los estándares de saneamiento recae en:",
    options:["Only the assigned TDLR inspector","Both the salon owner/operator and each individual licensee","Only the clients who use the salon","TDLR alone, with no individual responsibility"],
    options_es:["Solo el inspector asignado de TDLR","Tanto el propietario/operador del salón como cada titular de licencia individual","Solo los clientes que utilizan el salón","Solo TDLR, sin responsabilidad individual"],
    correct:1,
    explanation:"Both the establishment owner and individual practitioners share responsibility for maintaining proper sanitation standards." },

  { id:637, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Eyelash extension services in Texas fall under the regulated scope of:",
    question_es:"Los servicios de extensiones de pestañas en Texas caen bajo el alcance regulado de:",
    options:["No licensing requirement — unregulated beauty services","Cosmetology and esthetician licenses","Medical licensing only","Specialty spa permits only"],
    options_es:["Sin requisito de licencia — servicios de belleza no regulados","Licencias de cosmetología y esteticista","Solo licencias médicas","Solo permisos especiales de spa"],
    correct:1,
    explanation:"Eyelash extension services fall within the regulated scope of Texas cosmetology and esthetician licenses." },

  { id:638, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A Texas cosmetology candidate who fails the written licensing exam may:",
    question_es:"Un candidato de cosmetología de Texas que reprueba el examen escrito de licencias puede:",
    options:["Never retake the exam after a failure","Retake the exam after a waiting period and payment of an additional fee","Receive a provisional license immediately while waiting","Skip the written and take only the practical exam"],
    options_es:["Nunca volver a tomar el examen después de reprobarlo","Volver a tomar el examen después de un período de espera y el pago de una tarifa adicional","Recibir una licencia provisional de inmediato mientras espera","Omitir el escrito y tomar solo el examen práctico"],
    correct:1,
    explanation:"Failed candidates may retake the licensing exam after the required waiting period and payment of the retake fee." },

  { id:639, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Which of the following services REQUIRES a valid cosmetology license in Texas?",
    question_es:"¿Cuál de los siguientes servicios REQUIERE una licencia de cosmetología válida en Texas?",
    options:["Natural hair braiding using only non-chemical methods (may qualify for exemption)","Applying a chemical relaxer to a client's hair","Giving a friend a haircut as a personal favor with no payment","Painting a family member's nails at home for free"],
    options_es:["Trenzado natural de cabello usando solo métodos no químicos (puede calificar para exención)","Aplicar un alisador químico al cabello de un cliente","Cortar el cabello de un amigo como favor personal sin pago","Pintar las uñas de un familiar en casa de forma gratuita"],
    correct:1,
    explanation:"Applying chemical services such as relaxers is a regulated cosmetology practice in Texas requiring a valid license." },

  { id:640, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A hair braider in Texas who uses exclusively non-chemical methods:",
    question_es:"Un trenzador de cabello en Texas que utiliza exclusivamente métodos no químicos:",
    options:["Always requires a full Class A cosmetology license","May qualify for a specialty license or exemption separate from the Class A license","Cannot legally operate in Texas under any circumstances","Must hold an esthetician license instead"],
    options_es:["Siempre requiere una licencia completa de cosmetología Clase A","Puede calificar para una licencia especializada o exención separada de la licencia Clase A","No puede operar legalmente en Texas bajo ninguna circunstancia","Debe tener una licencia de esteticista en su lugar"],
    correct:1,
    explanation:"Texas law provides specific license categories or exemptions for natural hair braiders using only non-chemical techniques." },

  { id:641, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"TDLR administrative penalties for cosmetology violations are:",
    question_es:"Las sanciones administrativas de TDLR por infracciones de cosmetología son:",
    options:["Unlimited with no statutory maximum","Capped per violation per day as specified by the Texas Occupations Code","Applicable only to establishments, never to individual licensees","Only criminal fines imposed by Texas courts"],
    options_es:["Ilimitadas sin un máximo estatutario","Limitadas por infracción por día según lo especifica el Código de Ocupaciones de Texas","Aplicables solo a establecimientos, nunca a los titulares de licencias individuales","Solo multas penales impuestas por los tribunales de Texas"],
    correct:1,
    explanation:"Administrative penalties are capped per violation per day as set out in Texas Occupations Code Chapter 1603." },

  { id:642, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetologist's TDLR license number is required when:",
    question_es:"El número de licencia de TDLR de un cosmetólogo es requerido cuando:",
    options:["Only when taking the initial licensing exam","Renewing, advertising services, and when requested by TDLR or clients","Only for cosmetology instructors, not regular operators","Not required for booth renters operating independently"],
    options_es:["Solo cuando se toma el examen inicial de licencias","Al renovar, anunciar servicios y cuando lo soliciten TDLR o clientes","Solo para instructores de cosmetología, no para operadores regulares","No requerido para los arrendatarios de cabina que operan de forma independiente"],
    correct:1,
    explanation:"The license number is required for advertising, renewals, and must be provided upon request by TDLR or clients." },

  { id:643, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetology school operating in Texas must be approved by:",
    question_es:"Una escuela de cosmetología que opera en Texas debe estar aprobada por:",
    options:["The local school district board only","TDLR as an approved cosmetology school","Only the Texas Higher Education Coordinating Board","Any nationally recognized private accreditation body"],
    options_es:["Solo la junta del distrito escolar local","TDLR como escuela de cosmetología aprobada","Solo la Junta Coordinadora de Educación Superior de Texas","Cualquier organismo de acreditación privada reconocido a nivel nacional"],
    correct:1,
    explanation:"Cosmetology schools must be TDLR-approved to ensure their curriculum meets state-mandated training standards." },

  { id:644, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Training hours completed at a school that is NOT approved by TDLR:",
    question_es:"Las horas de capacitación completadas en una escuela que NO está aprobada por TDLR:",
    options:["Count in full toward Texas licensure requirements","Do not count toward Texas licensing requirements","Count for 50% credit toward required hours","Can be petitioned for credit on a case-by-case basis"],
    options_es:["Cuentan completamente para los requisitos de licencias de Texas","No cuentan para los requisitos de licencias de Texas","Cuentan por el 50% de crédito hacia las horas requeridas","Se pueden solicitar como crédito caso por caso"],
    correct:1,
    explanation:"Only hours completed at TDLR-approved cosmetology programs count toward Texas licensing requirements." },

  { id:645, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Student cosmetology clinic services in Texas must be performed:",
    question_es:"Los servicios de la clínica de estudiantes de cosmetología en Texas deben realizarse:",
    options:["In any commercial salon with client permission","Only within the school's licensed clinic under instructor supervision","In any licensed salon as an unpaid assistant","At the student's home with written parental consent"],
    options_es:["En cualquier salón comercial con permiso del cliente","Solo dentro de la clínica con licencia de la escuela bajo supervisión del instructor","En cualquier salón con licencia como asistente no remunerado","En la casa del estudiante con consentimiento escrito de los padres"],
    correct:1,
    explanation:"Student clinic services must be performed within the school's licensed clinic area under direct instructor supervision." },

  { id:646, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"When a TDLR inspector finds a violation during a salon inspection, the inspector may:",
    question_es:"Cuando un inspector de TDLR encuentra una infracción durante la inspección de un salón, el inspector puede:",
    options:["Issue only a verbal warning on the first visit","Issue a written violation notice and require corrective action","Permanently close the salon immediately without warning","Only photograph violations with no formal documentation"],
    options_es:["Emitir solo una advertencia verbal en la primera visita","Emitir un aviso de infracción escrito y requerir acción correctiva","Cerrar el salón permanentemente de inmediato sin advertencia","Solo fotografiar las infracciones sin documentación formal"],
    correct:1,
    explanation:"Inspectors issue written violation notices and can require corrective action, with escalating penalties for repeated violations." },

  { id:647, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Cosmetology licensing regulations primarily exist to protect:",
    question_es:"Las regulaciones de licencias de cosmetología existen principalmente para proteger:",
    options:["The financial interests of salon owners","The health, safety, and welfare of the public","The profits of cosmetology schools","The income of TDLR inspectors"],
    options_es:["Los intereses financieros de los propietarios de salones","La salud, seguridad y bienestar del público","Las ganancias de las escuelas de cosmetología","Los ingresos de los inspectores de TDLR"],
    correct:1,
    explanation:"The fundamental purpose of occupational licensing is consumer protection — ensuring practitioners are qualified to serve the public safely." },

  { id:648, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Nail services (manicures and pedicures) in Texas require:",
    question_es:"Los servicios de uñas (manicuras y pedicuras) en Texas requieren:",
    options:["No license — they are unregulated beauty services","A Class A cosmetology operator license or a separate manicurist license","Only a salon establishment license","Only an esthetician license"],
    options_es:["Ninguna licencia — son servicios de belleza no regulados","Una licencia de operador de cosmetología Clase A o una licencia de manicurista separada","Solo una licencia de establecimiento de salón","Solo una licencia de esteticista"],
    correct:1,
    explanation:"Nail services are regulated in Texas and require a Class A cosmetology operator license or a dedicated manicurist license." },

  { id:649, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A Texas cosmetologist first licensed in 2022 who never renewed would have their license expire in:",
    question_es:"Un cosmetólogo de Texas que obtuvo su primera licencia en 2022 y nunca la renovó tendría su licencia vencida en:",
    options:["2023","2024","2025","2027"],
    options_es:["2023","2024","2025","2027"],
    correct:1,
    explanation:"Texas cosmetology licenses are issued for 2-year terms; a 2022 license would expire in 2024 if never renewed." },

  { id:650, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"An unlicensed person observed providing cosmetology services for compensation should be reported to:",
    question_es:"Una persona sin licencia que brinda servicios de cosmetología por compensación debe ser reportada ante:",
    options:["Only the local city hall complaint line","TDLR's enforcement division for investigation","Only the local cosmetology industry association","The Texas Attorney General exclusively"],
    options_es:["Solo la línea de quejas del ayuntamiento local","La división de cumplimiento de TDLR para investigación","Solo la asociación local de la industria de cosmetología","Exclusivamente el Fiscal General de Texas"],
    correct:1,
    explanation:"TDLR has authority to investigate and take enforcement action against unlicensed cosmetology practice." },

  { id:651, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"The purpose of a TDLR establishment inspection is to:",
    question_es:"El propósito de una inspección de establecimiento de TDLR es:",
    options:["Collect inspection revenue for the state","Verify the salon meets sanitation, safety, and compliance standards","Review the salon's financial records and tax filings","Interview staff about wages and working conditions"],
    options_es:["Recaudar ingresos de inspección para el estado","Verificar que el salón cumpla con los estándares de saneamiento, seguridad y cumplimiento","Revisar los registros financieros y las declaraciones de impuestos del salón","Entrevistar al personal sobre salarios y condiciones laborales"],
    correct:1,
    explanation:"Inspections verify that salons meet all TDLR requirements for sanitation, safety, proper license display, and regulatory compliance." },

  { id:652, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"TDLR-approved cosmetology continuing education courses must cover:",
    question_es:"Los cursos de educación continua de cosmetología aprobados por TDLR deben cubrir:",
    options:["Any subject freely chosen by the licensee regardless of relevance","TDLR-approved topics such as sanitation, laws, and professional development","Only advanced business management and marketing","Only advanced chemical techniques"],
    options_es:["Cualquier tema elegido libremente por el titular, independientemente de su relevancia","Temas aprobados por TDLR como saneamiento, leyes y desarrollo profesional","Solo gestión empresarial avanzada y marketing","Solo técnicas químicas avanzadas"],
    correct:1,
    explanation:"CE courses must be TDLR-approved and cover topics relevant to safe, legal, and professional cosmetology practice." },

  { id:653, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A salon owner who knowingly employs a cosmetologist whose license has lapsed is:",
    question_es:"Un propietario de salón que a sabiendas emplea a un cosmetólogo cuya licencia ha vencido es:",
    options:["Not responsible — only the unlicensed cosmetologist is liable","Also subject to TDLR penalties for the establishment","Protected as long as the owner's own license is valid","Liable only if a client is actually harmed"],
    options_es:["No responsable — solo el cosmetólogo sin licencia es responsable","También sujeto a sanciones de TDLR para el establecimiento","Protegido siempre que su propia licencia sea válida","Responsable solo si un cliente resulta realmente dañado"],
    correct:1,
    explanation:"Salon owners are responsible for verifying employee licensure; employing unlicensed practitioners exposes the establishment to TDLR penalties." },

  { id:654, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A Texas Class A cosmetology operator license authorizes the holder to perform:",
    question_es:"Una licencia de operador de cosmetología Clase A de Texas autoriza al titular a realizar:",
    options:["Only nail services","A broad range of hair, skin, and nail beauty services","Only chemical services such as relaxers and perms","Only haircutting and styling"],
    options_es:["Solo servicios de uñas","Una amplia gama de servicios de belleza de cabello, piel y uñas","Solo servicios químicos como alisados y permanentes","Solo corte y peinado de cabello"],
    correct:1,
    explanation:"A Texas Class A operator license covers an extensive scope including hair, skin, and nail services regulated by Texas cosmetology law." },

  { id:655, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A signed client consent or release form:",
    question_es:"Un formulario de consentimiento o exención firmado por el cliente:",
    options:["Eliminates all legal and regulatory liability for the cosmetologist","Does not override the cosmetologist's duty to follow safety and sanitation standards","Allows any service regardless of contraindications or health risks","Replaces the need for a pre-service consultation"],
    options_es:["Elimina toda la responsabilidad legal y regulatoria del cosmetólogo","No anula el deber del cosmetólogo de seguir los estándares de seguridad y saneamiento","Permite cualquier servicio independientemente de las contraindicaciones o riesgos para la salud","Reemplaza la necesidad de una consulta previa al servicio"],
    correct:1,
    explanation:"Client consent does not override a cosmetologist's professional and legal obligation to comply with safety and sanitation requirements." },

  { id:656, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A TDLR-approved cosmetology school curriculum must include:",
    question_es:"El plan de estudios de una escuela de cosmetología aprobada por TDLR debe incluir:",
    options:["Only hands-on practical clinic hours with no classroom theory","Both theory (classroom) and practical (clinic) hours as required by TDLR","Subjects chosen entirely by the school with no regulatory oversight","A minimum of 3 full years of study"],
    options_es:["Solo horas prácticas de clínica sin teoría en el aula","Tanto horas de teoría (aula) como horas prácticas (clínica) según lo requiere TDLR","Materias elegidas íntegramente por la escuela sin supervisión regulatoria","Un mínimo de 3 años completos de estudio"],
    correct:1,
    explanation:"TDLR requires approved schools to provide curriculum combining theory instruction and practical clinic hours in prescribed proportions." },

  { id:657, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"When a Texas cosmetologist retires their license, they must:",
    question_es:"Cuando un cosmetólogo de Texas retira su licencia, debe:",
    options:["Destroy the license immediately and inform all clients","Notify TDLR and follow any required surrender procedures","Transfer the license to a recommended cosmetologist","Continue providing limited services under a retired status designation"],
    options_es:["Destruir la licencia de inmediato e informar a todos los clientes","Notificar a TDLR y seguir los procedimientos de entrega requeridos","Transferir la licencia a un cosmetólogo recomendado","Continuar brindando servicios limitados bajo una designación de estado retirado"],
    correct:1,
    explanation:"Retiring a license involves notifying TDLR; a cosmetology license is personal and cannot be transferred to another person." },

  { id:658, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"Texas Occupations Code Chapter 1603 grants TDLR authority to:",
    question_es:"El Capítulo 1603 del Código de Ocupaciones de Texas otorga a TDLR autoridad para:",
    options:["Set prices charged for cosmetology services","Issue, renew, deny, suspend, and revoke cosmetology licenses","Set minimum wage levels for cosmetologists","Directly operate and manage cosmetology schools"],
    options_es:["Establecer los precios cobrados por los servicios de cosmetología","Emitir, renovar, denegar, suspender y revocar licencias de cosmetología","Establecer los niveles de salario mínimo para los cosmetólogos","Operar y gestionar directamente las escuelas de cosmetología"],
    correct:1,
    explanation:"Chapter 1603 grants TDLR full licensing authority including issuance, renewal, denial, suspension, and revocation of cosmetology licenses." },

  { id:659, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"A cosmetologist whose Texas license renewal is pending (submitted but not yet issued) must:",
    question_es:"Un cosmetólogo cuya renovación de licencia de Texas está pendiente (presentada pero aún no emitida) debe:",
    options:["Continue providing services since the renewal application was submitted","Stop providing cosmetology services until the renewed license is officially issued","Display a copy of the renewal application in place of the expired license","Work under a supervisor's license during the pending period"],
    options_es:["Continuar brindando servicios ya que la solicitud de renovación fue presentada","Dejar de brindar servicios de cosmetología hasta que la licencia renovada sea emitida oficialmente","Mostrar una copia de la solicitud de renovación en lugar de la licencia vencida","Trabajar bajo la licencia de un supervisor durante el período pendiente"],
    correct:1,
    explanation:"A valid, currently issued license is required to perform services; submitting a renewal application does not authorize continued practice." },

  { id:660, topic:T, topic_es:TE, psi_topic:P, psi_topic_es:PE,
    question:"All Texas cosmetology establishment licenses must be:",
    question_es:"Todas las licencias de establecimiento de cosmetología de Texas deben estar:",
    options:["Kept only in the owner's personal files, available upon request","Prominently displayed within the licensed establishment","Submitted annually to TDLR for reverification","Only available in digital format on the TDLR website"],
    options_es:["Guardadas solo en los archivos personales del propietario, disponibles a solicitud","Exhibidas de manera prominente dentro del establecimiento con licencia","Presentadas anualmente a TDLR para reverificación","Solo disponibles en formato digital en el sitio web de TDLR"],
    correct:1,
    explanation:"The establishment license must be prominently displayed within the salon so that clients and inspectors can see it." },
]

// Validate
console.log(`Questions to append: ${questions.length}`)
for (const q of questions) {
  if (q.options.length !== 4 || q.options_es.length !== 4) throw new Error(`id ${q.id}: option count error`)
  if (q.correct < 0 || q.correct > 3) throw new Error(`id ${q.id}: correct out of range`)
}
console.log('Validation passed — all questions have 4 options and valid correct index.')

// Build lines to append
const newLines = [
  '',
  '// ─── TEXAS TDLR LAWS & REGULATIONS EXPANSION (ids 601–660) ───',
]
for (const q of questions) {
  const line = `  { id:${q.id}, topic:"${q.topic}", topic_es:"${q.topic_es}", psi_topic:"${q.psi_topic}", psi_topic_es:"${q.psi_topic_es}", question:"${q.question}", question_es:"${q.question_es}", options:${JSON.stringify(q.options)}, options_es:${JSON.stringify(q.options_es)}, correct:${q.correct}, explanation:"${q.explanation}" },`
  newLines.push(line)
}

// Read file, replace closing ] with new content + ]
let content = readFileSync(FILE, 'utf8')
if (!content.trimEnd().endsWith(']')) throw new Error('Unexpected file ending — aborting.')
content = content.trimEnd().slice(0, -1) // remove closing ]
content += newLines.join('\n') + '\n]'
writeFileSync(FILE, content, 'utf8')
console.log('Done. questions.js updated.')
