// 400-question bank for Board Ready Beauty
// Topics and proportions match Texas TDLR/PSI cosmetology written exam

export const questions = [

  // ─── SANITATION & INFECTION CONTROL (60 questions) ───────────────────────
  { id: 1, topic: "Sanitation & Infection Control", question: "What is the correct term for the destruction of all living organisms including spores?", options: ["Sterilization", "Disinfection", "Sanitation", "Decontamination"], correct: 0 },
  { id: 2, topic: "Sanitation & Infection Control", question: "Which is an EPA-registered disinfectant ratio used in salons?", options: ["Bleach 1:10 with water", "Bleach 1:100 with water", "Bleach 1:50 with water", "Bleach 1:5 with water"], correct: 0 },
  { id: 3, topic: "Sanitation & Infection Control", question: "How long must implements be immersed in an EPA-registered disinfectant?", options: ["5 minutes", "10 minutes", "As directed by manufacturer", "30 minutes"], correct: 2 },
  { id: 4, topic: "Sanitation & Infection Control", question: "What is the first step in decontaminating implements?", options: ["Disinfect", "Sterilize", "Clean with soap and water", "Rinse with alcohol"], correct: 2 },
  { id: 5, topic: "Sanitation & Infection Control", question: "Bacteria that cause disease are called:", options: ["Pathogenic", "Non-pathogenic", "Saprophytes", "Cocci"], correct: 0 },
  { id: 6, topic: "Sanitation & Infection Control", question: "Which type of bacteria grows in clusters like a bunch of grapes?", options: ["Streptococci", "Diplococci", "Staphylococci", "Bacilli"], correct: 2 },
  { id: 7, topic: "Sanitation & Infection Control", question: "OSHA requires salons to have which of the following on file?", options: ["Client records", "Safety Data Sheets", "Employee schedules", "Inventory lists"], correct: 1 },
  { id: 8, topic: "Sanitation & Infection Control", question: "A client has a nail infection. What should you do?", options: ["Treat with antifungal", "Refer to a physician", "Proceed with service", "Use extra disinfectant"], correct: 1 },
  { id: 9, topic: "Sanitation & Infection Control", question: "Which of the following cannot be disinfected and must be discarded after use?", options: ["Metal implements", "Porous implements", "Glass implements", "Plastic combs"], correct: 1 },
  { id: 10, topic: "Sanitation & Infection Control", question: "UV sanitizers in salons are used for:", options: ["Sterilization", "Disinfection", "Storage of clean implements", "Killing all pathogens"], correct: 2 },
  { id: 11, topic: "Sanitation & Infection Control", question: "Which hepatitis virus is most commonly transmitted in salon settings?", options: ["Hepatitis A", "Hepatitis B", "Hepatitis C", "All equally"], correct: 1 },
  { id: 12, topic: "Sanitation & Infection Control", question: "Blood exposure in the salon requires:", options: ["Ignoring if minor", "Standard precautions and proper cleanup", "Only washing with soap", "Calling TDLR immediately"], correct: 1 },
  { id: 13, topic: "Sanitation & Infection Control", question: "Autoclave sterilization uses:", options: ["UV light", "Chemical vapor", "Steam under pressure", "Dry heat only"], correct: 2 },
  { id: 14, topic: "Sanitation & Infection Control", question: "Which of the following is a virus?", options: ["Staphylococci", "HIV", "Ringworm", "E. coli"], correct: 1 },
  { id: 15, topic: "Sanitation & Infection Control", question: "Bacteria that form pairs are called:", options: ["Staphylococci", "Streptococci", "Diplococci", "Bacilli"], correct: 2 },
  { id: 16, topic: "Sanitation & Infection Control", question: "What does CDC stand for?", options: ["Center for Disease Control", "Centers for Disease Control and Prevention", "Chemical Disinfection Council", "Cosmetology Disease Commission"], correct: 1 },
  { id: 17, topic: "Sanitation & Infection Control", question: "Fungi that cause skin infections are called:", options: ["Parasites", "Dermatophytes", "Cocci", "Bacilli"], correct: 1 },
  { id: 18, topic: "Sanitation & Infection Control", question: "An item is bioburden-free when:", options: ["It looks clean", "All visible debris is removed", "It has been disinfected", "It has been sterilized"], correct: 1 },
  { id: 19, topic: "Sanitation & Infection Control", question: "Which PPE should be worn when handling disinfectants?", options: ["Only gloves", "Gloves and eye protection", "Only a mask", "No PPE needed"], correct: 1 },
  { id: 20, topic: "Sanitation & Infection Control", question: "Quaternary ammonium compounds are used as:", options: ["Sterilants", "Disinfectants", "Sanitizers only", "Antibiotics"], correct: 1 },
  { id: 21, topic: "Sanitation & Infection Control", question: "Phenolic disinfectants are effective against:", options: ["Only bacteria", "Bacteria and some viruses", "Spores only", "All microorganisms"], correct: 1 },
  { id: 22, topic: "Sanitation & Infection Control", question: "What is the purpose of an SDS (Safety Data Sheet)?", options: ["Track inventory", "Provide chemical hazard information", "Record client history", "Document employee hours"], correct: 1 },
  { id: 23, topic: "Sanitation & Infection Control", question: "Nonpathogenic bacteria:", options: ["Cause disease", "Are harmless or beneficial", "Cannot be destroyed", "Only live on skin"], correct: 1 },
  { id: 24, topic: "Sanitation & Infection Control", question: "Which organism requires a living host to survive?", options: ["Bacteria", "Fungi", "Virus", "Mold"], correct: 2 },
  { id: 25, topic: "Sanitation & Infection Control", question: "The process of removing pathogens from non-living surfaces is:", options: ["Sterilization", "Disinfection", "Immunization", "Pasteurization"], correct: 1 },
  { id: 26, topic: "Sanitation & Infection Control", question: "Which is the most effective method of infection prevention in a salon?", options: ["Using gloves always", "Proper hand washing", "Disinfecting all surfaces", "Wearing a mask"], correct: 1 },
  { id: 27, topic: "Sanitation & Infection Control", question: "A cosmetologist should wash their hands:", options: ["Only before services", "Before and after each client", "Only after handling chemicals", "Once per day"], correct: 1 },
  { id: 28, topic: "Sanitation & Infection Control", question: "Contaminated items should be placed in:", options: ["Any available container", "A labeled, covered trash receptacle", "The supply closet", "The break room"], correct: 1 },
  { id: 29, topic: "Sanitation & Infection Control", question: "Which bacteria form long chains?", options: ["Staphylococci", "Diplococci", "Streptococci", "Spirilla"], correct: 2 },
  { id: 30, topic: "Sanitation & Infection Control", question: "Spores are dangerous because they:", options: ["Reproduce quickly", "Are resistant to disinfectants", "Only affect plants", "Are always visible"], correct: 1 },
  { id: 31, topic: "Sanitation & Infection Control", question: "Which disinfectant is safe for use on skin?", options: ["Quaternary ammonium", "Bleach solution", "70% isopropyl alcohol", "Phenolic compounds"], correct: 2 },
  { id: 32, topic: "Sanitation & Infection Control", question: "How often should towels used on clients be laundered?", options: ["Weekly", "Daily", "After each use", "Monthly"], correct: 2 },
  { id: 33, topic: "Sanitation & Infection Control", question: "The term 'aseptic' means:", options: ["Full of bacteria", "Free from infection", "Partially clean", "Chemically treated"], correct: 1 },
  { id: 34, topic: "Sanitation & Infection Control", question: "Which is the correct order of decontamination?", options: ["Disinfect, clean, sterilize", "Clean, disinfect, sterilize if needed", "Sterilize, clean, disinfect", "Disinfect, sterilize, clean"], correct: 1 },
  { id: 35, topic: "Sanitation & Infection Control", question: "A parasitic infestation on the scalp is treated by:", options: ["The cosmetologist using special shampoo", "Referring the client to a physician", "Using bleach on the scalp", "Ignoring it if minor"], correct: 1 },
  { id: 36, topic: "Sanitation & Infection Control", question: "What does EPA stand for?", options: ["Environmental Protection Agency", "Employee Protection Act", "Effective Products Administration", "Equipment Purification Agency"], correct: 0 },
  { id: 37, topic: "Sanitation & Infection Control", question: "Mixing bleach with ammonia creates:", options: ["A stronger disinfectant", "Toxic chloramine gas", "A safe cleaning solution", "A sanitizer"], correct: 1 },
  { id: 38, topic: "Sanitation & Infection Control", question: "Single-use items such as nail files should be:", options: ["Cleaned and reused", "Disinfected between clients", "Discarded after each use", "Sterilized and stored"], correct: 2 },
  { id: 39, topic: "Sanitation & Infection Control", question: "Bacteria that are rod-shaped are called:", options: ["Cocci", "Bacilli", "Spirilla", "Diplococci"], correct: 1 },
  { id: 40, topic: "Sanitation & Infection Control", question: "Bacteria that are spiral-shaped are called:", options: ["Cocci", "Bacilli", "Spirilla", "Diplococci"], correct: 2 },
  { id: 41, topic: "Sanitation & Infection Control", question: "Which is true about tuberculocidal disinfectants?", options: ["They only kill bacteria", "They kill TB bacteria and are broad-spectrum", "They are only used in hospitals", "They replace sterilization"], correct: 1 },
  { id: 42, topic: "Sanitation & Infection Control", question: "Salons must maintain disinfectant solution by:", options: ["Changing it weekly", "Changing it when visibly dirty or per manufacturer guidelines", "Never changing it", "Changing it daily regardless"], correct: 1 },
  { id: 43, topic: "Sanitation & Infection Control", question: "The goal of sanitation is to:", options: ["Eliminate all microorganisms", "Reduce microorganisms to safe levels", "Sterilize all surfaces", "Kill viruses only"], correct: 1 },
  { id: 44, topic: "Sanitation & Infection Control", question: "Which infection is caused by a parasitic mite?", options: ["Ringworm", "Scabies", "Impetigo", "Psoriasis"], correct: 1 },
  { id: 45, topic: "Sanitation & Infection Control", question: "A furuncle is a:", options: ["Fungal infection", "Boil caused by staph bacteria", "Type of ringworm", "Viral lesion"], correct: 1 },
  { id: 46, topic: "Sanitation & Infection Control", question: "Immunization helps prevent infection by:", options: ["Killing bacteria directly", "Stimulating immune response", "Disinfecting the body", "Sterilizing blood"], correct: 1 },
  { id: 47, topic: "Sanitation & Infection Control", question: "Which item can be sterilized with an autoclave?", options: ["Plastic combs", "Metal implements", "Synthetic brushes", "Paper towels"], correct: 1 },
  { id: 48, topic: "Sanitation & Infection Control", question: "What is the inactive stage of bacteria called?", options: ["Active phase", "Spore stage", "Mitosis phase", "Dormant state"], correct: 1 },
  { id: 49, topic: "Sanitation & Infection Control", question: "Cross-contamination occurs when:", options: ["Tools are sterilized", "Pathogens transfer between clients via tools or surfaces", "Clients wash their hands", "Proper disinfection is used"], correct: 1 },
  { id: 50, topic: "Sanitation & Infection Control", question: "Which of the following best describes 'standard precautions'?", options: ["Treating only visibly sick clients with care", "Treating all clients as potentially infectious", "Using gloves only for blood exposure", "Disinfecting only between chemical services"], correct: 1 },
  { id: 51, topic: "Sanitation & Infection Control", question: "The muslin or neck strip used during a haircut should be:", options: ["Reused for the day", "Changed for each client", "Washed weekly", "Disinfected between clients"], correct: 1 },
  { id: 52, topic: "Sanitation & Infection Control", question: "Disinfectants must be registered with which agency?", options: ["OSHA", "FDA", "EPA", "TDLR"], correct: 2 },
  { id: 53, topic: "Sanitation & Infection Control", question: "A cosmetologist notices open sores on a client's scalp. They should:", options: ["Proceed with the service", "Cover sores before starting", "Refuse service and refer to a doctor", "Apply disinfectant to the area"], correct: 2 },
  { id: 54, topic: "Sanitation & Infection Control", question: "Which is the safest way to handle sharp implements?", options: ["Leave on counter after use", "Place cap on immediately and store safely", "Rinse in water only", "Share with coworkers"], correct: 1 },
  { id: 55, topic: "Sanitation & Infection Control", question: "Alcohol-based hand sanitizers are effective against:", options: ["All pathogens including spores", "Most bacteria and viruses but not spores", "Only viruses", "Only bacteria"], correct: 1 },
  { id: 56, topic: "Sanitation & Infection Control", question: "The highest level of decontamination achievable in a salon is:", options: ["Sterilization", "Disinfection", "Sanitization", "Deodorization"], correct: 1 },
  { id: 57, topic: "Sanitation & Infection Control", question: "Carbolic acid is another name for:", options: ["Quaternary ammonium", "Phenol", "Bleach", "Hydrogen peroxide"], correct: 1 },
  { id: 58, topic: "Sanitation & Infection Control", question: "Which statement about HIV is correct?", options: ["It is easily spread by casual contact", "It requires blood, semen, or bodily fluid contact", "It can survive on dry surfaces for weeks", "It is the same as Hepatitis B"], correct: 1 },
  { id: 59, topic: "Sanitation & Infection Control", question: "Salmonella is an example of which type of bacteria?", options: ["Cocci", "Bacilli", "Spirilla", "Diplococci"], correct: 1 },
  { id: 60, topic: "Sanitation & Infection Control", question: "A clean and covered wet disinfectant container should be used to store:", options: ["All salon supplies", "Disinfected implements only", "Client belongings", "Chemical services products"], correct: 1 },

  // ─── HAIR CARE & CHEMISTRY (60 questions) ────────────────────────────────
  { id: 61, topic: "Hair Care & Chemistry", question: "What is the pH range of hair?", options: ["1-3", "4.5-5.5", "7-8", "9-10"], correct: 1 },
  { id: 62, topic: "Hair Care & Chemistry", question: "Which layer of the hair contains melanin (pigment)?", options: ["Cuticle", "Cortex", "Medulla", "Epidermis"], correct: 1 },
  { id: 63, topic: "Hair Care & Chemistry", question: "A permanent wave permanently changes the hair's:", options: ["Color", "Disulfide bonds", "Hydrogen bonds", "Cuticle"], correct: 1 },
  { id: 64, topic: "Hair Care & Chemistry", question: "What does a normalizing shampoo do?", options: ["Adds moisture", "Closes the cuticle and balances pH", "Opens the cuticle", "Adds protein"], correct: 1 },
  { id: 65, topic: "Hair Care & Chemistry", question: "Which chemical service raises the pH of hair the most?", options: ["Highlighting", "Relaxing", "Perming", "Toning"], correct: 1 },
  { id: 66, topic: "Hair Care & Chemistry", question: "What is the outermost layer of the hair shaft?", options: ["Medulla", "Cortex", "Cuticle", "Dermis"], correct: 2 },
  { id: 67, topic: "Hair Care & Chemistry", question: "Hydrogen peroxide used in color is measured in:", options: ["Percentages", "Volumes", "pH levels", "Grams"], correct: 1 },
  { id: 68, topic: "Hair Care & Chemistry", question: "A thio relaxer works by breaking:", options: ["Hydrogen bonds", "Salt bonds", "Disulfide bonds", "Peptide bonds"], correct: 2 },
  { id: 69, topic: "Hair Care & Chemistry", question: "Which hair type is most resistant to chemical services?", options: ["Fine hair", "Porous hair", "Low porosity hair", "Color-treated hair"], correct: 2 },
  { id: 70, topic: "Hair Care & Chemistry", question: "The process of returning hair to its natural pH after a chemical service is called:", options: ["Toning", "Neutralizing", "Conditioning", "Balancing"], correct: 1 },
  { id: 71, topic: "Hair Care & Chemistry", question: "An alkaline solution has a pH:", options: ["Below 7", "Equal to 7", "Above 7", "Between 4-5"], correct: 2 },
  { id: 72, topic: "Hair Care & Chemistry", question: "Which bond in hair is the strongest?", options: ["Hydrogen bond", "Salt bond", "Disulfide bond", "Van der Waals bond"], correct: 2 },
  { id: 73, topic: "Hair Care & Chemistry", question: "Keratin is the primary protein that makes up:", options: ["Skin only", "Hair and nails", "Blood", "Muscles"], correct: 1 },
  { id: 74, topic: "Hair Care & Chemistry", question: "Hair porosity refers to:", options: ["Hair thickness", "Hair's ability to absorb moisture", "Hair's curl pattern", "Hair's elasticity"], correct: 1 },
  { id: 75, topic: "Hair Care & Chemistry", question: "Which shampoo is best for color-treated hair?", options: ["Clarifying shampoo", "Moisturizing color-safe shampoo", "Dandruff shampoo", "Volumizing shampoo"], correct: 1 },
  { id: 76, topic: "Hair Care & Chemistry", question: "The medulla is:", options: ["The outer layer", "The middle layer", "The innermost layer", "The root sheath"], correct: 2 },
  { id: 77, topic: "Hair Care & Chemistry", question: "Hair elasticity refers to:", options: ["Its ability to absorb color", "Its ability to stretch and return to original length", "Its resistance to chemicals", "Its curl pattern"], correct: 1 },
  { id: 78, topic: "Hair Care & Chemistry", question: "Which ingredient in conditioner coats the hair shaft?", options: ["Surfactants", "Cationic polymers", "Sulfates", "Peroxides"], correct: 1 },
  { id: 79, topic: "Hair Care & Chemistry", question: "Temporary hair color coats:", options: ["The cortex", "The medulla", "The cuticle surface only", "All layers equally"], correct: 2 },
  { id: 80, topic: "Hair Care & Chemistry", question: "What is the active ingredient in most permanent waves?", options: ["Hydrogen peroxide", "Ammonium thioglycolate", "Sodium hydroxide", "Sodium bromate"], correct: 1 },
  { id: 81, topic: "Hair Care & Chemistry", question: "pH stands for:", options: ["Potential of hydrogen", "Power of hydrogen", "Percent hydrogen", "Both A and B"], correct: 3 },
  { id: 82, topic: "Hair Care & Chemistry", question: "A clarifying shampoo is used to:", options: ["Add moisture", "Remove product buildup", "Color the hair", "Straighten the hair"], correct: 1 },
  { id: 83, topic: "Hair Care & Chemistry", question: "Which bond is broken by water and heat styling?", options: ["Disulfide bonds", "Peptide bonds", "Hydrogen bonds", "Salt bonds"], correct: 2 },
  { id: 84, topic: "Hair Care & Chemistry", question: "High porosity hair:", options: ["Resists moisture", "Absorbs and loses moisture quickly", "Has a tight cuticle", "Requires no conditioning"], correct: 1 },
  { id: 85, topic: "Hair Care & Chemistry", question: "Which is the correct pH of a neutralizer used after a perm?", options: ["3.0-4.0", "4.5-5.5", "7.0", "8.0-9.0"], correct: 1 },
  { id: 86, topic: "Hair Care & Chemistry", question: "Eumelanin produces:", options: ["Red and yellow tones", "Brown and black tones", "Blonde tones", "Gray tones"], correct: 1 },
  { id: 87, topic: "Hair Care & Chemistry", question: "Pheomelanin produces:", options: ["Dark brown tones", "Black tones", "Red and yellow tones", "Gray tones"], correct: 2 },
  { id: 88, topic: "Hair Care & Chemistry", question: "The peptide bond connects:", options: ["Hair fibers to skin", "Amino acids together", "Cortex layers", "Melanin molecules"], correct: 1 },
  { id: 89, topic: "Hair Care & Chemistry", question: "A deep conditioning treatment is also called:", options: ["A gloss", "A hair mask or reconstructor", "A toner", "A relaxer"], correct: 1 },
  { id: 90, topic: "Hair Care & Chemistry", question: "Which type of hair has the most disulfide bonds?", options: ["Straight hair", "Wavy hair", "Curly hair", "All hair has the same"], correct: 2 },
  { id: 91, topic: "Hair Care & Chemistry", question: "Surfactants in shampoo function to:", options: ["Add protein", "Lift and suspend dirt and oil", "Add color", "Seal the cuticle"], correct: 1 },
  { id: 92, topic: "Hair Care & Chemistry", question: "A strand test before chemical services checks:", options: ["Hair color only", "Timing, results, and hair integrity", "Scalp sensitivity only", "Product fragrance"], correct: 1 },
  { id: 93, topic: "Hair Care & Chemistry", question: "Which pH level would be considered neutral?", options: ["4", "7", "9", "12"], correct: 1 },
  { id: 94, topic: "Hair Care & Chemistry", question: "The cuticle of the hair is made of:", options: ["Round cells", "Overlapping scale-like cells", "Liquid keratin", "Melanin clusters"], correct: 1 },
  { id: 95, topic: "Hair Care & Chemistry", question: "Hair is approximately what percent protein?", options: ["20%", "50%", "70%", "97%"], correct: 3 },
  { id: 96, topic: "Hair Care & Chemistry", question: "Which type of conditioner is used after shampooing and rinsed out?", options: ["Leave-in", "Rinse-out", "Deep treatment", "Protein pack"], correct: 1 },
  { id: 97, topic: "Hair Care & Chemistry", question: "Damaged hair has:", options: ["Tightly closed cuticle", "High elasticity", "Raised or missing cuticle scales", "Low porosity"], correct: 2 },
  { id: 98, topic: "Hair Care & Chemistry", question: "Which term describes the number of hairs per square inch of scalp?", options: ["Texture", "Porosity", "Density", "Elasticity"], correct: 2 },
  { id: 99, topic: "Hair Care & Chemistry", question: "Hair texture refers to:", options: ["How many hairs there are", "The diameter of individual hair strands", "The curl pattern", "The color depth"], correct: 1 },
  { id: 100, topic: "Hair Care & Chemistry", question: "Lye relaxers contain:", options: ["Ammonium thioglycolate", "Sodium hydroxide", "Guanidine carbonate", "Lithium hydroxide"], correct: 1 },
  { id: 101, topic: "Hair Care & Chemistry", question: "No-lye relaxers contain:", options: ["Sodium hydroxide", "Ammonium thioglycolate", "Guanidine hydroxide", "Thio compounds"], correct: 2 },
  { id: 102, topic: "Hair Care & Chemistry", question: "After a relaxer, the neutralizing shampoo:", options: ["Lifts remaining relaxer", "Stops the chemical action and closes cuticle", "Adds color", "Increases lift"], correct: 1 },
  { id: 103, topic: "Hair Care & Chemistry", question: "Which vitamin deficiency can cause hair loss?", options: ["Vitamin C", "Vitamin D", "Biotin (B7)", "Vitamin K"], correct: 2 },
  { id: 104, topic: "Hair Care & Chemistry", question: "The anagen phase of hair growth is:", options: ["The resting phase", "The transitional phase", "The active growth phase", "The shedding phase"], correct: 2 },
  { id: 105, topic: "Hair Care & Chemistry", question: "The telogen phase is:", options: ["Active growth", "Transition", "Resting/shedding phase", "Regeneration"], correct: 2 },
  { id: 106, topic: "Hair Care & Chemistry", question: "The catagen phase is:", options: ["Active growth", "Transitional/regression phase", "Resting phase", "Shedding phase"], correct: 1 },
  { id: 107, topic: "Hair Care & Chemistry", question: "How long does the anagen phase typically last?", options: ["Days to weeks", "2-6 years", "6 months", "10 years"], correct: 1 },
  { id: 108, topic: "Hair Care & Chemistry", question: "Sebum is produced by:", options: ["The sweat glands", "The sebaceous glands", "The hair follicle only", "The epidermis"], correct: 1 },
  { id: 109, topic: "Hair Care & Chemistry", question: "Which shampoo would you use on a client with an oily scalp?", options: ["Moisturizing shampoo", "Balancing or clarifying shampoo", "Color-protective shampoo", "Dry shampoo"], correct: 1 },
  { id: 110, topic: "Hair Care & Chemistry", question: "Protein treatments are used to:", options: ["Add color", "Strengthen and repair damaged hair", "Relax curls", "Add volume to fine hair"], correct: 1 },
  { id: 111, topic: "Hair Care & Chemistry", question: "Chelating shampoos remove:", options: ["Excess oil", "Mineral buildup from hard water", "Color deposits", "Dandruff flakes"], correct: 1 },
  { id: 112, topic: "Hair Care & Chemistry", question: "Which bond is reformed during the neutralization step of a perm?", options: ["Hydrogen bonds", "Salt bonds", "Disulfide bonds", "Peptide bonds"], correct: 2 },
  { id: 113, topic: "Hair Care & Chemistry", question: "Terminal hair is:", options: ["Fine, light, short hair", "The coarse, pigmented hair on head and body", "Newborn hair", "Hair that has stopped growing"], correct: 1 },
  { id: 114, topic: "Hair Care & Chemistry", question: "Vellus hair is:", options: ["Coarse scalp hair", "Fine, soft, unpigmented body hair", "Beard hair", "Terminal hair"], correct: 1 },
  { id: 115, topic: "Hair Care & Chemistry", question: "The arrector pili muscle causes:", options: ["Hair growth", "Goosebumps/hair to stand up", "Sebum production", "Hair pigmentation"], correct: 1 },
  { id: 116, topic: "Hair Care & Chemistry", question: "Which tool measures hair porosity?", options: ["pH strip", "Strand test", "Porosity test with water", "Elasticity test"], correct: 2 },
  { id: 117, topic: "Hair Care & Chemistry", question: "A hair that springs back when stretched has good:", options: ["Porosity", "Density", "Elasticity", "Texture"], correct: 2 },
  { id: 118, topic: "Hair Care & Chemistry", question: "Formaldehyde-based smoothing treatments work by:", options: ["Breaking disulfide bonds", "Temporarily straightening with heat and forming bonds", "Adding keratin to medulla", "Raising the cuticle permanently"], correct: 1 },
  { id: 119, topic: "Hair Care & Chemistry", question: "The hair bulb is located:", options: ["At the tip of the hair", "At the base of the follicle", "In the cortex", "In the cuticle"], correct: 1 },
  { id: 120, topic: "Hair Care & Chemistry", question: "Sulfate-free shampoos are recommended for:", options: ["Oily scalp types", "Color-treated or dry hair", "Thick coarse hair", "Dandruff-prone scalps"], correct: 1 },

  // ─── SCALP & HAIR DISORDERS (32 questions) ───────────────────────────────
  { id: 121, topic: "Scalp & Hair Disorders", question: "Tinea capitis is a fungal infection of the:", options: ["Nails", "Skin", "Scalp", "Eyes"], correct: 2 },
  { id: 122, topic: "Scalp & Hair Disorders", question: "Alopecia areata is characterized by:", options: ["Total hair loss", "Patchy hair loss", "Gradual thinning", "Scalp flaking"], correct: 1 },
  { id: 123, topic: "Scalp & Hair Disorders", question: "Pediculosis capitis is an infestation of:", options: ["Fungi", "Bacteria", "Head lice", "Mites"], correct: 2 },
  { id: 124, topic: "Scalp & Hair Disorders", question: "A cosmetologist should NOT service a client with:", options: ["Dry scalp", "Dandruff", "Ringworm (active)", "Oily hair"], correct: 2 },
  { id: 125, topic: "Scalp & Hair Disorders", question: "Dandruff is technically known as:", options: ["Tinea capitis", "Pityriasis", "Alopecia", "Psoriasis"], correct: 1 },
  { id: 126, topic: "Scalp & Hair Disorders", question: "Which condition causes excessive hair loss due to hormones?", options: ["Tinea capitis", "Androgenic alopecia", "Pediculosis", "Canities"], correct: 1 },
  { id: 127, topic: "Scalp & Hair Disorders", question: "Canities refers to:", options: ["Hair loss", "Gray hair", "Brittle hair", "Oily scalp"], correct: 1 },
  { id: 128, topic: "Scalp & Hair Disorders", question: "Monilethrix is a condition where the hair shaft is:", options: ["Curly", "Beaded", "Split", "Coarse"], correct: 1 },
  { id: 129, topic: "Scalp & Hair Disorders", question: "Trichorrhexis nodosa is a condition where:", options: ["Hair grows in spirals", "Hair splits at nodes along the shaft", "Hair falls out in patches", "The scalp flakes excessively"], correct: 1 },
  { id: 130, topic: "Scalp & Hair Disorders", question: "Fragilitas crinium refers to:", options: ["Hair loss", "Brittle hair", "Gray hair", "Oily hair"], correct: 1 },
  { id: 131, topic: "Scalp & Hair Disorders", question: "Alopecia totalis refers to:", options: ["Patchy hair loss", "Complete loss of scalp hair", "Loss of all body hair", "Gradual thinning"], correct: 1 },
  { id: 132, topic: "Scalp & Hair Disorders", question: "Alopecia universalis refers to:", options: ["Patchy hair loss", "Scalp hair loss only", "Loss of all body and scalp hair", "Temporary hair loss"], correct: 2 },
  { id: 133, topic: "Scalp & Hair Disorders", question: "Hypertrichosis refers to:", options: ["Hair loss", "Excessive hair growth", "Gray hair", "Brittle hair"], correct: 1 },
  { id: 134, topic: "Scalp & Hair Disorders", question: "Hirsuties is excessive hair growth in women in areas where:", options: ["Normal hair grows", "Terminal hair typically grows on men", "Vellus hair grows on all", "Hair never grows"], correct: 1 },
  { id: 135, topic: "Scalp & Hair Disorders", question: "Seborrheic dermatitis is characterized by:", options: ["Dry flaking without redness", "Oily flaking with redness and inflammation", "Hair loss only", "Fungal infection of the shaft"], correct: 1 },
  { id: 136, topic: "Scalp & Hair Disorders", question: "Psoriasis of the scalp presents as:", options: ["Smooth red patches", "Thick silvery scales with redness", "Oily dandruff only", "Hair loss patches"], correct: 1 },
  { id: 137, topic: "Scalp & Hair Disorders", question: "Traction alopecia is caused by:", options: ["Chemical damage", "Prolonged tension on hair follicles", "Fungal infection", "Hormonal imbalance"], correct: 1 },
  { id: 138, topic: "Scalp & Hair Disorders", question: "Telogen effluvium is:", options: ["Permanent hair loss", "Temporary hair shedding after stress or illness", "Fungal hair loss", "Alopecia areata"], correct: 1 },
  { id: 139, topic: "Scalp & Hair Disorders", question: "Which scalp condition is contagious?", options: ["Androgenic alopecia", "Seborrheic dermatitis", "Tinea capitis", "Psoriasis"], correct: 2 },
  { id: 140, topic: "Scalp & Hair Disorders", question: "A cosmetologist finds nits on a client. They should:", options: ["Remove them and proceed", "Refer the client and sanitize everything", "Apply a clarifying shampoo", "Ignore if client is not scratching"], correct: 1 },
  { id: 141, topic: "Scalp & Hair Disorders", question: "Pityriasis steatoides is:", options: ["Dry dandruff", "Oily dandruff (waxy, yellow flakes)", "Psoriasis", "Tinea capitis"], correct: 1 },
  { id: 142, topic: "Scalp & Hair Disorders", question: "Postpartum hair loss is an example of:", options: ["Alopecia areata", "Telogen effluvium", "Traction alopecia", "Androgenic alopecia"], correct: 1 },
  { id: 143, topic: "Scalp & Hair Disorders", question: "Ringed hair (pili annulati) is characterized by:", options: ["Hair growing in rings", "Alternating light and dark bands on the shaft", "Circular bald patches", "Scalp ringworm"], correct: 1 },
  { id: 144, topic: "Scalp & Hair Disorders", question: "Bamboo hair is associated with which condition?", options: ["Monilethrix", "Netherton syndrome", "Tinea capitis", "Trichorrhexis"], correct: 1 },
  { id: 145, topic: "Scalp & Hair Disorders", question: "Which condition is NOT contagious?", options: ["Head lice", "Ringworm", "Androgenic alopecia", "Scabies"], correct: 2 },
  { id: 146, topic: "Scalp & Hair Disorders", question: "A scalp massage is contraindicated when:", options: ["Client has dry scalp", "Scalp has abrasions or infections", "Client requests it", "Client has thin hair"], correct: 1 },
  { id: 147, topic: "Scalp & Hair Disorders", question: "Which medication can cause hair loss as a side effect?", options: ["Vitamins", "Chemotherapy drugs", "Antibiotics", "Antihistamines"], correct: 1 },
  { id: 148, topic: "Scalp & Hair Disorders", question: "The medical term for split ends is:", options: ["Fragilitas crinium", "Trichoptilosis", "Monilethrix", "Canities"], correct: 1 },
  { id: 149, topic: "Scalp & Hair Disorders", question: "Trichotillomania is:", options: ["Fungal hair infection", "Compulsive hair pulling disorder", "Excessive hair growth", "Scalp psoriasis"], correct: 1 },
  { id: 150, topic: "Scalp & Hair Disorders", question: "Minoxidil is used to treat:", options: ["Dandruff", "Hair loss", "Scalp infections", "Split ends"], correct: 1 },
  { id: 151, topic: "Scalp & Hair Disorders", question: "Which scalp condition appears as yellowish crusts?", options: ["Psoriasis", "Favus (tinea favosa)", "Seborrheic dermatitis", "Pityriasis"], correct: 1 },
  { id: 152, topic: "Scalp & Hair Disorders", question: "Female pattern baldness typically affects:", options: ["The hairline first", "The crown and top of the head", "The nape area", "Patchy areas randomly"], correct: 1 },

  // ─── SKIN CARE & ANATOMY (40 questions) ──────────────────────────────────
  { id: 153, topic: "Skin Care & Anatomy", question: "The outermost layer of the skin is the:", options: ["Dermis", "Hypodermis", "Epidermis", "Subcutis"], correct: 2 },
  { id: 154, topic: "Skin Care & Anatomy", question: "Melanin is produced by cells called:", options: ["Keratinocytes", "Melanocytes", "Fibroblasts", "Langerhans cells"], correct: 1 },
  { id: 155, topic: "Skin Care & Anatomy", question: "Which skin type has enlarged pores and excess shine?", options: ["Dry", "Normal", "Oily", "Sensitive"], correct: 2 },
  { id: 156, topic: "Skin Care & Anatomy", question: "SPF stands for:", options: ["Sun Protection Foundation", "Sun Protection Factor", "Skin Protection Formula", "Solar Prevention Filter"], correct: 1 },
  { id: 157, topic: "Skin Care & Anatomy", question: "A comedone is commonly known as:", options: ["A pimple", "A whitehead or blackhead", "A cold sore", "A skin tag"], correct: 1 },
  { id: 158, topic: "Skin Care & Anatomy", question: "Which layer of the skin contains collagen and elastin?", options: ["Epidermis", "Stratum corneum", "Dermis", "Hypodermis"], correct: 2 },
  { id: 159, topic: "Skin Care & Anatomy", question: "Rosacea is characterized by:", options: ["Dry flaky skin", "Persistent redness and flushing", "Deep acne cysts", "Hyperpigmentation"], correct: 1 },
  { id: 160, topic: "Skin Care & Anatomy", question: "A cosmetologist should refer a client with suspicious moles to:", options: ["Another cosmetologist", "A dermatologist", "An esthetician", "A pharmacist"], correct: 1 },
  { id: 161, topic: "Skin Care & Anatomy", question: "Exfoliation removes:", options: ["Deep wrinkles", "Dead surface skin cells", "Moles", "Scars"], correct: 1 },
  { id: 162, topic: "Skin Care & Anatomy", question: "The stratum corneum is:", options: ["The deepest layer of epidermis", "The outermost layer of epidermis", "The entire dermis", "The subcutaneous layer"], correct: 1 },
  { id: 163, topic: "Skin Care & Anatomy", question: "Hyperpigmentation is caused by:", options: ["Too little melanin", "Too much melanin in an area", "Loss of skin elasticity", "Dehydration"], correct: 1 },
  { id: 164, topic: "Skin Care & Anatomy", question: "A macule is:", options: ["A raised lesion", "A flat, discolored spot", "A fluid-filled blister", "A scaly patch"], correct: 1 },
  { id: 165, topic: "Skin Care & Anatomy", question: "A papule is:", options: ["A flat spot", "A small solid raised lesion", "A fluid-filled vesicle", "A large nodule"], correct: 1 },
  { id: 166, topic: "Skin Care & Anatomy", question: "A vesicle is:", options: ["A solid raised bump", "A small fluid-filled blister", "A flat dark spot", "A large cyst"], correct: 1 },
  { id: 167, topic: "Skin Care & Anatomy", question: "Collagen provides skin with:", options: ["Color", "Structure and firmness", "Oil", "Moisture only"], correct: 1 },
  { id: 168, topic: "Skin Care & Anatomy", question: "Elastin provides skin with:", options: ["Pigmentation", "Flexibility and elasticity", "Immune protection", "Hydration"], correct: 1 },
  { id: 169, topic: "Skin Care & Anatomy", question: "The hypodermis is also known as:", options: ["Epidermis", "Subcutaneous layer", "Stratum granulosum", "Stratum spinosum"], correct: 1 },
  { id: 170, topic: "Skin Care & Anatomy", question: "Which skin condition is caused by the herpes simplex virus?", options: ["Warts", "Cold sores", "Psoriasis", "Eczema"], correct: 1 },
  { id: 171, topic: "Skin Care & Anatomy", question: "Vitiligo is characterized by:", options: ["Excess pigment", "Loss of pigment in patches", "Redness", "Scaling"], correct: 1 },
  { id: 172, topic: "Skin Care & Anatomy", question: "Acne vulgaris is caused by:", options: ["Bacteria, excess oil, and clogged pores", "Dry skin only", "UV exposure", "Allergic reactions only"], correct: 0 },
  { id: 173, topic: "Skin Care & Anatomy", question: "A pustule contains:", options: ["Clear fluid", "Pus (cloudy fluid)", "Blood", "Sebum only"], correct: 1 },
  { id: 174, topic: "Skin Care & Anatomy", question: "Telangiectasia refers to:", options: ["Enlarged pores", "Dilated surface blood vessels", "Brown spots", "Raised scars"], correct: 1 },
  { id: 175, topic: "Skin Care & Anatomy", question: "Sun damage primarily affects which layer of skin?", options: ["Hypodermis only", "Dermis and epidermis", "Only the stratum corneum", "Only the subcutaneous layer"], correct: 1 },
  { id: 176, topic: "Skin Care & Anatomy", question: "Which skin type feels tight and may flake?", options: ["Oily", "Combination", "Dry", "Normal"], correct: 2 },
  { id: 177, topic: "Skin Care & Anatomy", question: "Combination skin has:", options: ["All oily zones", "Oily T-zone with dry cheeks", "All dry zones", "Uniform normal zones"], correct: 1 },
  { id: 178, topic: "Skin Care & Anatomy", question: "A skin tag is medically known as:", options: ["Acrochordon", "Papule", "Macule", "Nevus"], correct: 0 },
  { id: 179, topic: "Skin Care & Anatomy", question: "Keloid scars are:", options: ["Flat, pale scars", "Raised, overgrown scar tissue", "Sunken scars", "Temporary redness"], correct: 1 },
  { id: 180, topic: "Skin Care & Anatomy", question: "Which cells in the skin provide immune protection?", options: ["Keratinocytes", "Melanocytes", "Langerhans cells", "Fibroblasts"], correct: 2 },
  { id: 181, topic: "Skin Care & Anatomy", question: "The stratum basale is the:", options: ["Outermost layer", "Deepest layer of the epidermis", "Top of the dermis", "The subcutaneous layer"], correct: 1 },
  { id: 182, topic: "Skin Care & Anatomy", question: "Sebaceous glands produce:", options: ["Sweat", "Sebum", "Melanin", "Collagen"], correct: 1 },
  { id: 183, topic: "Skin Care & Anatomy", question: "Eccrine glands produce:", options: ["Sebum", "Apocrine sweat", "Eccrine sweat (cooling)", "Melanin"], correct: 2 },
  { id: 184, topic: "Skin Care & Anatomy", question: "Apocrine glands are located primarily in:", options: ["All skin surfaces", "Armpits and groin area", "The face only", "The palms and soles"], correct: 1 },
  { id: 185, topic: "Skin Care & Anatomy", question: "UV-A rays primarily cause:", options: ["Sunburn", "Skin aging and deeper damage", "Melanoma only", "No skin damage"], correct: 1 },
  { id: 186, topic: "Skin Care & Anatomy", question: "UV-B rays primarily cause:", options: ["Tanning and aging", "Sunburn and surface damage", "No skin damage", "Deep tissue damage only"], correct: 1 },
  { id: 187, topic: "Skin Care & Anatomy", question: "Dermatitis is:", options: ["A type of cancer", "Inflammation of the skin", "A fungal infection", "A bacterial infection"], correct: 1 },
  { id: 188, topic: "Skin Care & Anatomy", question: "Contact dermatitis is caused by:", options: ["Internal hormones", "Direct skin contact with an irritant or allergen", "Fungal infection", "Viral infection"], correct: 1 },
  { id: 189, topic: "Skin Care & Anatomy", question: "A nevus is:", options: ["A wart", "A mole (pigmented spot)", "A scar", "A blister"], correct: 1 },
  { id: 190, topic: "Skin Care & Anatomy", question: "Which is a primary skin lesion?", options: ["Scale", "Crust", "Papule", "Scar"], correct: 2 },
  { id: 191, topic: "Skin Care & Anatomy", question: "Which is a secondary skin lesion?", options: ["Macule", "Vesicle", "Scale", "Papule"], correct: 2 },
  { id: 192, topic: "Skin Care & Anatomy", question: "The ABCDE rule is used to evaluate:", options: ["Acne", "Moles for signs of melanoma", "Skin type", "Rosacea"], correct: 1 },

  // ─── NAIL CARE (32 questions) ─────────────────────────────────────────────
  { id: 193, topic: "Nail Care", question: "The living skin at the base of the nail is called the:", options: ["Nail bed", "Lunula", "Cuticle", "Matrix"], correct: 2 },
  { id: 194, topic: "Nail Care", question: "Where does nail growth originate?", options: ["Nail plate", "Nail bed", "Matrix", "Cuticle"], correct: 2 },
  { id: 195, topic: "Nail Care", question: "Onychomycosis is a fungal infection of the:", options: ["Skin", "Scalp", "Nails", "Hair"], correct: 2 },
  { id: 196, topic: "Nail Care", question: "A white spot on the nail is called:", options: ["Onychorrhexis", "Leukonychia", "Onycholysis", "Paronychia"], correct: 1 },
  { id: 197, topic: "Nail Care", question: "Paronychia is an infection of the:", options: ["Nail plate", "Tissue surrounding the nail", "Nail bed", "Matrix"], correct: 1 },
  { id: 198, topic: "Nail Care", question: "Which nail condition is contraindicated for nail services?", options: ["Dry cuticles", "Ridged nails", "Onychomycosis", "Leukonychia"], correct: 2 },
  { id: 199, topic: "Nail Care", question: "The half-moon shape at the base of the nail is called:", options: ["Matrix", "Lunula", "Hyponychium", "Eponychium"], correct: 1 },
  { id: 200, topic: "Nail Care", question: "The free edge of the nail extends beyond the:", options: ["Matrix", "Cuticle", "Fingertip", "Lunula"], correct: 2 },
  { id: 201, topic: "Nail Care", question: "Onycholysis is:", options: ["Nail thickening", "Separation of nail plate from nail bed", "Nail infection", "White spots"], correct: 1 },
  { id: 202, topic: "Nail Care", question: "Onychorrhexis refers to:", options: ["Nail fungus", "Brittle nails with lengthwise ridges", "Nail separation", "Nail inflammation"], correct: 1 },
  { id: 203, topic: "Nail Care", question: "Pterygium is:", options: ["A nail fungus", "Overgrowth of cuticle onto nail plate", "Nail separation", "White spots"], correct: 1 },
  { id: 204, topic: "Nail Care", question: "Koilonychia refers to:", options: ["Thickened nails", "Spoon-shaped concave nails", "Fungal nails", "Ingrown nails"], correct: 1 },
  { id: 205, topic: "Nail Care", question: "Onychauxis is:", options: ["Nail thinning", "Abnormal nail thickening", "Nail separation", "Nail infection"], correct: 1 },
  { id: 206, topic: "Nail Care", question: "The hyponychium is:", options: ["The base of the nail", "Skin under the free edge", "The nail plate", "The matrix"], correct: 1 },
  { id: 207, topic: "Nail Care", question: "The nail plate is made of:", options: ["Collagen", "Keratin", "Melanin", "Elastin"], correct: 1 },
  { id: 208, topic: "Nail Care", question: "Nails grow an average of:", options: ["1 inch per month", "1/8 inch per month", "1 cm per week", "1/4 inch per week"], correct: 1 },
  { id: 209, topic: "Nail Care", question: "An ingrown nail is called:", options: ["Onycholysis", "Onychocryptosis", "Onychauxis", "Leukonychia"], correct: 1 },
  { id: 210, topic: "Nail Care", question: "Which condition should immediately stop a nail service?", options: ["Ridges on nails", "Hangnail", "Signs of infection or open wounds", "Yellow staining"], correct: 2 },
  { id: 211, topic: "Nail Care", question: "Nail hardeners work by:", options: ["Adding moisture", "Cross-linking keratin proteins", "Removing layers", "Adding color"], correct: 1 },
  { id: 212, topic: "Nail Care", question: "A nail biter (onychophagia) client may have:", options: ["Thickened nails", "Short, uneven nail edges and cuticle damage", "Fungal infection always", "Normal nail shape"], correct: 1 },
  { id: 213, topic: "Nail Care", question: "Beau's lines are:", options: ["Vertical ridges", "Horizontal grooves across the nail", "White spots", "Yellow discoloration"], correct: 1 },
  { id: 214, topic: "Nail Care", question: "Yellow nail syndrome causes nails to be:", options: ["Soft and peeling", "Yellow, thick, and slow-growing", "Brittle and ridged", "Separated from the bed"], correct: 1 },
  { id: 215, topic: "Nail Care", question: "Acrylic nails are a combination of:", options: ["Gel and polish", "Liquid monomer and powder polymer", "Silk and resin", "Fiberglass and glue"], correct: 1 },
  { id: 216, topic: "Nail Care", question: "UV gel nails are cured using:", options: ["Air drying", "UV or LED lamp", "Heat gun", "Chemical activator"], correct: 1 },
  { id: 217, topic: "Nail Care", question: "The proper way to remove acrylic nails is:", options: ["Peel them off", "Cut and soak in acetone", "Use a nail drill only", "Pull quickly"], correct: 1 },
  { id: 218, topic: "Nail Care", question: "Nail dehydrators are used to:", options: ["Add moisture before enhancements", "Remove surface oils before enhancements", "Cure gel polish", "Remove acrylic"], correct: 1 },
  { id: 219, topic: "Nail Care", question: "Primer is used in nail enhancements to:", options: ["Add shine", "Promote adhesion between nail and product", "Remove cuticle", "Cure the product"], correct: 1 },
  { id: 220, topic: "Nail Care", question: "MMA (methyl methacrylate) in nail products is:", options: ["Required by law", "Prohibited by many state boards due to safety concerns", "The safest monomer", "Used in all gel products"], correct: 1 },
  { id: 221, topic: "Nail Care", question: "A nail tip is applied to:", options: ["Cover the entire nail", "Extend the free edge", "Replace the matrix", "Treat nail fungus"], correct: 1 },
  { id: 222, topic: "Nail Care", question: "Which filing motion is correct for natural nails?", options: ["Back and forth sawing", "Filing in one direction", "Circular motion only", "Any motion is fine"], correct: 1 },
  { id: 223, topic: "Nail Care", question: "Cuticle oil is used to:", options: ["Harden nails", "Moisturize cuticles and surrounding skin", "Remove dead cuticle", "Bond enhancements"], correct: 1 },
  { id: 224, topic: "Nail Care", question: "The nail fold is the:", options: ["Free edge of nail", "Skin that overlaps the nail on sides and base", "Nail plate", "Matrix area"], correct: 1 },

  // ─── CHEMICAL SERVICES (40 questions) ────────────────────────────────────
  { id: 225, topic: "Chemical Services", question: "Before any chemical service, a cosmetologist should perform:", options: ["A strand test only", "A patch test and strand test", "A porosity test only", "No test needed"], correct: 1 },
  { id: 226, topic: "Chemical Services", question: "Sodium hydroxide relaxers are also known as:", options: ["No-lye relaxers", "Lye relaxers", "Thio relaxers", "Keratin relaxers"], correct: 1 },
  { id: 227, topic: "Chemical Services", question: "How long should a patch test be observed before chemical services?", options: ["12 hours", "24-48 hours", "1 hour", "1 week"], correct: 1 },
  { id: 228, topic: "Chemical Services", question: "A positive patch test result means:", options: ["Proceed with service", "Do not proceed — client is allergic", "Use less product", "Dilute the chemical"], correct: 1 },
  { id: 229, topic: "Chemical Services", question: "Which neutralizer is used after a thio perm?", options: ["Sodium hydroxide", "Hydrogen peroxide", "Ammonium thioglycolate", "Sodium bromate"], correct: 1 },
  { id: 230, topic: "Chemical Services", question: "Overlapping chemical relaxers onto previously relaxed hair can cause:", options: ["Better results", "Hair breakage", "More curl", "Color change"], correct: 1 },
  { id: 231, topic: "Chemical Services", question: "A virgin application of hair color means:", options: ["Coloring hair for the first time", "Using natural ingredients only", "Applying to previously colored hair", "A semi-permanent application"], correct: 0 },
  { id: 232, topic: "Chemical Services", question: "A retouch application of relaxer is applied to:", options: ["The entire head", "New growth only", "The ends only", "The mid-shaft"], correct: 1 },
  { id: 233, topic: "Chemical Services", question: "The purpose of a base cream during relaxing is to:", options: ["Add shine", "Protect the scalp", "Speed up processing", "Neutralize the relaxer"], correct: 1 },
  { id: 234, topic: "Chemical Services", question: "Thio perms require a pH of approximately:", options: ["4.5-5.5", "7.0", "8.5-9.5", "11-14"], correct: 2 },
  { id: 235, topic: "Chemical Services", question: "Which perm solution is gentlest on hair?", options: ["Acid wave", "Alkaline wave", "Sodium hydroxide", "High-pH thio"], correct: 0 },
  { id: 236, topic: "Chemical Services", question: "Acid waves require heat because:", options: ["They have a lower pH and need activation", "They contain bleach", "They work faster with heat", "The client prefers it"], correct: 0 },
  { id: 237, topic: "Chemical Services", question: "Which type of rod creates the tightest curl?", options: ["Largest diameter rod", "Smallest diameter rod", "Concave rod", "Straight rod"], correct: 1 },
  { id: 238, topic: "Chemical Services", question: "The processing time for a perm is checked by:", options: ["A timer only", "S-curl test and visual check", "Smell only", "Client comfort"], correct: 1 },
  { id: 239, topic: "Chemical Services", question: "After neutralizing a perm, the rods should be:", options: ["Left in for 24 hours", "Removed and hair rinsed", "Removed immediately without rinsing", "Left in until dry"], correct: 1 },
  { id: 240, topic: "Chemical Services", question: "A predisposition test is another name for:", options: ["Strand test", "Patch test", "Porosity test", "Elasticity test"], correct: 1 },
  { id: 241, topic: "Chemical Services", question: "Chemical burns from relaxers should be treated by:", options: ["Applying more neutralizer", "Rinsing thoroughly and seeking medical help", "Applying ice only", "Ignoring if minor"], correct: 1 },
  { id: 242, topic: "Chemical Services", question: "Hair that is over-processed from a relaxer appears:", options: ["Shiny and smooth", "Mushy and weak", "Curlier than before", "Darker in color"], correct: 1 },
  { id: 243, topic: "Chemical Services", question: "Thio relaxers are safer for which type of hair?", options: ["Coarse resistant hair", "Color-treated or previously relaxed hair", "Natural virgin hair", "Thick hair"], correct: 1 },
  { id: 244, topic: "Chemical Services", question: "A soft curl permanent gives hair:", options: ["Straight texture", "Defined curl formation without full straightening", "Tight coil pattern", "Loose wave only"], correct: 1 },
  { id: 245, topic: "Chemical Services", question: "Japanese straightening permanently changes hair by:", options: ["Breaking and rebonding disulfide bonds with heat", "Using sodium hydroxide only", "Coating the cuticle", "Using keratin only"], correct: 0 },
  { id: 246, topic: "Chemical Services", question: "Keratin smoothing treatments are:", options: ["Permanent", "Semi-permanent, lasting 3-6 months", "Temporary, lasting 1-2 weeks", "Instant and permanent"], correct: 1 },
  { id: 247, topic: "Chemical Services", question: "When perming color-treated hair, you should:", options: ["Use the same strength perm", "Use a gentler acid perm", "Avoid perming colored hair entirely", "Use a stronger alkaline perm"], correct: 1 },
  { id: 248, topic: "Chemical Services", question: "The number of rods used in a perm affects:", options: ["The color result", "The volume and curl pattern", "The chemical strength needed", "The processing time only"], correct: 1 },
  { id: 249, topic: "Chemical Services", question: "Waving lotion softens hair by:", options: ["Adding moisture", "Reducing disulfide bonds", "Raising the cuticle only", "Depositing protein"], correct: 1 },
  { id: 250, topic: "Chemical Services", question: "A brick lay perm wrap pattern is used to:", options: ["Avoid splits in the curl pattern", "Create defined sections", "Speed processing", "Use fewer rods"], correct: 0 },
  { id: 251, topic: "Chemical Services", question: "End papers in a perm wrap are used to:", options: ["Add color", "Protect and smooth hair ends around the rod", "Speed neutralization", "Condition the hair"], correct: 1 },
  { id: 252, topic: "Chemical Services", question: "A patch test for hair color checks for:", options: ["Color results", "Allergic reaction to PPD or other dye ingredients", "Hair porosity", "Scalp health"], correct: 1 },
  { id: 253, topic: "Chemical Services", question: "A strand test for hair color determines:", options: ["Whether client is allergic", "Processing time and color result", "Scalp sensitivity", "Product strength"], correct: 1 },
  { id: 254, topic: "Chemical Services", question: "PPD stands for:", options: ["Para-phenylenediamine", "Peroxide Processing Dye", "Permanent Pigment Deposit", "Post-Processing Developer"], correct: 0 },
  { id: 255, topic: "Chemical Services", question: "Which chemical service should NOT be performed on the same day as another chemical service?", options: ["Toning after lightening", "Relaxer and perm on the same day", "Gloss after coloring", "Toner after bleaching"], correct: 1 },
  { id: 256, topic: "Chemical Services", question: "The main hazard associated with chemical straightening services is:", options: ["Staining", "Scalp burns and hair breakage", "Eye color change", "Skin tanning"], correct: 1 },
  { id: 257, topic: "Chemical Services", question: "Which tool is used to section hair for a perm?", options: ["Wide tooth comb only", "Tail comb and clips", "Brush", "Fingers only"], correct: 1 },
  { id: 258, topic: "Chemical Services", question: "The reduction step in perming:", options: ["Neutralizes the hair", "Softens and breaks disulfide bonds", "Adds color", "Closes the cuticle"], correct: 1 },
  { id: 259, topic: "Chemical Services", question: "The oxidation step in perming:", options: ["Opens the cuticle", "Reforms disulfide bonds in new position", "Adds protein", "Removes the product"], correct: 1 },
  { id: 260, topic: "Chemical Services", question: "Proper ventilation during chemical services is important because:", options: ["It cools the client", "Fumes from chemicals can be harmful if inhaled", "It helps the product process faster", "It prevents color from fading"], correct: 1 },
  { id: 261, topic: "Chemical Services", question: "Protective gloves should be worn during chemical services to:", options: ["Look professional", "Prevent skin contact with potentially harmful chemicals", "Keep hands warm", "Improve grip on tools"], correct: 1 },
  { id: 262, topic: "Chemical Services", question: "A curl reformer changes:", options: ["Hair color permanently", "Curl pattern by breaking and rebuilding disulfide bonds", "Hair texture to straight only", "Hair density"], correct: 1 },
  { id: 263, topic: "Chemical Services", question: "When should a relaxer service be stopped immediately?", options: ["After 20 minutes", "If client reports burning or scalp irritation", "When the timer goes off", "After the first application"], correct: 1 },
  { id: 264, topic: "Chemical Services", question: "Hydroxide relaxers cannot be used on hair that has been:", options: ["Colored with permanent color", "Previously permed with thio", "Highlighted", "Deep conditioned"], correct: 1 },

  // ─── TEXAS TDLR LAWS & REGULATIONS (40 questions) ────────────────────────
  { id: 265, topic: "Texas TDLR Laws & Regulations", question: "Which agency regulates cosmetology in Texas?", options: ["FDA", "OSHA", "TDLR", "EPA"], correct: 2 },
  { id: 266, topic: "Texas TDLR Laws & Regulations", question: "How many hours of CE does a Texas cosmetologist need for renewal?", options: ["4 hours", "6 hours", "8 hours", "10 hours"], correct: 0 },
  { id: 267, topic: "Texas TDLR Laws & Regulations", question: "A Texas cosmetology license must be renewed every:", options: ["1 year", "2 years", "3 years", "5 years"], correct: 1 },
  { id: 268, topic: "Texas TDLR Laws & Regulations", question: "The TDLR license must be displayed:", options: ["In a drawer", "At the workstation in plain view", "In the break room", "Not required to display"], correct: 1 },
  { id: 269, topic: "Texas TDLR Laws & Regulations", question: "Which service requires a cosmetology license in Texas?", options: ["Eyebrow threading", "Ear piercing", "Tattooing", "Permanent makeup only"], correct: 0 },
  { id: 270, topic: "Texas TDLR Laws & Regulations", question: "A salon owner who violates TDLR rules may face:", options: ["Only a warning", "Fines and license suspension", "Criminal charges only", "No penalty"], correct: 1 },
  { id: 271, topic: "Texas TDLR Laws & Regulations", question: "How many operator hours are required for a Texas cosmetology license?", options: ["1000 hours", "1500 hours", "1000 + 100 hours", "500 hours"], correct: 0 },
  { id: 272, topic: "Texas TDLR Laws & Regulations", question: "A client record card should contain:", options: ["Only name and phone", "Services, products used, and any reactions", "Payment info only", "Address and email only"], correct: 1 },
  { id: 273, topic: "Texas TDLR Laws & Regulations", question: "Cosmetology schools in Texas are regulated by:", options: ["Local school boards", "TDLR", "The federal government", "Individual counties"], correct: 1 },
  { id: 274, topic: "Texas TDLR Laws & Regulations", question: "A booth renter in a salon is considered:", options: ["An employee", "An independent contractor", "A salon owner", "An apprentice"], correct: 1 },
  { id: 275, topic: "Texas TDLR Laws & Regulations", question: "A cosmetology student in Texas must complete their training at:", options: ["Any location", "A TDLR-licensed cosmetology school", "Online only", "A private home studio"], correct: 1 },
  { id: 276, topic: "Texas TDLR Laws & Regulations", question: "Working in a salon without a valid license in Texas is:", options: ["Acceptable if supervised", "A violation subject to fines", "Allowed for students", "Not regulated"], correct: 1 },
  { id: 277, topic: "Texas TDLR Laws & Regulations", question: "Which of the following is required to be posted in a Texas salon?", options: ["Price list only", "TDLR license and sanitation rules", "Staff photos", "Client testimonials"], correct: 1 },
  { id: 278, topic: "Texas TDLR Laws & Regulations", question: "How many hours are required for a Texas esthetician license?", options: ["750 hours", "1000 hours", "600 hours", "500 hours"], correct: 0 },
  { id: 279, topic: "Texas TDLR Laws & Regulations", question: "A mobile salon in Texas must:", options: ["Have no license requirements", "Be licensed by TDLR", "Only serve private clients", "Be licensed by the city only"], correct: 1 },
  { id: 280, topic: "Texas TDLR Laws & Regulations", question: "A Texas cosmetology license is valid in:", options: ["All states automatically", "Texas only unless reciprocity agreement exists", "All states by federal law", "Only the county issued"], correct: 1 },
  { id: 281, topic: "Texas TDLR Laws & Regulations", question: "TDLR stands for:", options: ["Texas Department of Licensing and Regulation", "Texas Division of Labor and Registration", "Texas Department of Legal Regulation", "Texas Directorate of Licensing Rules"], correct: 0 },
  { id: 282, topic: "Texas TDLR Laws & Regulations", question: "A nail technician license in Texas requires:", options: ["600 hours", "750 hours", "1000 hours", "500 hours"], correct: 0 },
  { id: 283, topic: "Texas TDLR Laws & Regulations", question: "A salon inspection by TDLR can occur:", options: ["Only with 30 days notice", "Only after a complaint", "At any time without prior notice", "Only annually"], correct: 2 },
  { id: 284, topic: "Texas TDLR Laws & Regulations", question: "Which is true about performing services outside your license scope?", options: ["It is acceptable if supervised", "It is a violation of Texas law", "It is encouraged for learning", "It is only a warning offense"], correct: 1 },
  { id: 285, topic: "Texas TDLR Laws & Regulations", question: "A cosmetology license can be suspended for:", options: ["Being late to work", "Violating sanitation rules or practicing without a license", "Missing a CE class", "Having a complaint filed"], correct: 1 },
  { id: 286, topic: "Texas TDLR Laws & Regulations", question: "Which of the following does TDLR NOT regulate?", options: ["Cosmetology salons", "Tattoo studios", "Barbershops", "Medical spas performing laser"], correct: 3 },
  { id: 287, topic: "Texas TDLR Laws & Regulations", question: "Reciprocity allows a licensed cosmetologist from another state to:", options: ["Work in Texas without any process", "Apply for a Texas license based on their existing license", "Practice only in schools", "Never work in Texas"], correct: 1 },
  { id: 288, topic: "Texas TDLR Laws & Regulations", question: "The Texas Occupations Code governs:", options: ["Federal labor law", "State licensing requirements including cosmetology", "City health codes only", "Insurance requirements"], correct: 1 },
  { id: 289, topic: "Texas TDLR Laws & Regulations", question: "Continuing education requirements in Texas include:", options: ["Any topic chosen by licensee", "TDLR-approved courses only", "Courses from any state", "No requirements until renewal"], correct: 1 },
  { id: 290, topic: "Texas TDLR Laws & Regulations", question: "A salon must keep sanitation records for:", options: ["1 year", "2 years", "5 years", "Indefinitely"], correct: 0 },
  { id: 291, topic: "Texas TDLR Laws & Regulations", question: "Student permits in Texas allow students to:", options: ["Work in salons without supervision", "Practice in approved educational settings only", "Perform all services", "Skip the licensing exam"], correct: 1 },
  { id: 292, topic: "Texas TDLR Laws & Regulations", question: "Which of the following is an example of unprofessional conduct?", options: ["Being late once", "Performing services under the influence of drugs or alcohol", "Missing a staff meeting", "Charging too much for services"], correct: 1 },
  { id: 293, topic: "Texas TDLR Laws & Regulations", question: "A Texas cosmetology operator can legally perform:", options: ["Medical procedures", "Hair, skin, and nail services within scope", "Tattoos", "Laser hair removal"], correct: 1 },
  { id: 294, topic: "Texas TDLR Laws & Regulations", question: "How should a salon handle a client who experiences an allergic reaction?", options: ["Ignore it if mild", "Document it, stop service, and seek medical help if needed", "Apply more product to see if it goes away", "Ask the client to leave"], correct: 1 },
  { id: 295, topic: "Texas TDLR Laws & Regulations", question: "A cosmetology manager license allows the holder to:", options: ["Perform all services", "Manage cosmetology operations and supervise staff", "Open any type of salon", "Skip renewal requirements"], correct: 1 },
  { id: 296, topic: "Texas TDLR Laws & Regulations", question: "Eye services such as lash extensions in Texas require:", options: ["A cosmetology or esthetician license", "No license", "A medical license", "A specialty permit only"], correct: 0 },
  { id: 297, topic: "Texas TDLR Laws & Regulations", question: "Which form of identification must a cosmetologist present when requested?", options: ["Social security card", "Valid TDLR license", "Birth certificate", "School diploma"], correct: 1 },
  { id: 298, topic: "Texas TDLR Laws & Regulations", question: "The fee for renewing a cosmetology license in Texas is set by:", options: ["The salon owner", "TDLR", "The federal government", "The local health department"], correct: 1 },
  { id: 299, topic: "Texas TDLR Laws & Regulations", question: "A complaint against a cosmetologist in Texas should be filed with:", options: ["The police", "TDLR", "The Better Business Bureau", "The city health department"], correct: 1 },
  { id: 300, topic: "Texas TDLR Laws & Regulations", question: "Which of the following services is within the scope of a Texas cosmetologist?", options: ["Microblading", "Dermaplaning", "Facials and skin care", "Botox injections"], correct: 2 },
  { id: 301, topic: "Texas TDLR Laws & Regulations", question: "An expired Texas cosmetology license means the holder:", options: ["Can still practice for 6 months", "Cannot legally practice until renewed", "Is automatically suspended", "Only needs to take a test"], correct: 1 },
  { id: 302, topic: "Texas TDLR Laws & Regulations", question: "Schools must provide students with a written disclosure of:", options: ["Staff salaries", "Program costs, hours required, and job placement rates", "Exam pass rates only", "Insurance information"], correct: 1 },
  { id: 303, topic: "Texas TDLR Laws & Regulations", question: "Which agency sets the rules for sanitation in Texas salons?", options: ["Local city council", "TDLR", "OSHA", "The salon owner"], correct: 1 },
  { id: 304, topic: "Texas TDLR Laws & Regulations", question: "Texas law requires minors working as cosmetology apprentices to:", options: ["Have parental consent only", "Meet age requirements set by TDLR", "Have a medical certificate", "Not be allowed to work"], correct: 1 },

  // ─── COLORING & LIGHTENING (32 questions) ────────────────────────────────
  { id: 305, topic: "Coloring & Lightening", question: "Which level of hair color only coats the outside of the hair shaft?", options: ["Permanent", "Semi-permanent", "Temporary", "Demi-permanent"], correct: 2 },
  { id: 306, topic: "Coloring & Lightening", question: "What developer is used for maximum lightening with bleach?", options: ["10 volume", "20 volume", "30 volume", "40 volume"], correct: 3 },
  { id: 307, topic: "Coloring & Lightening", question: "When performing a single-process color, where do you apply color first?", options: ["Mid-strand", "Ends", "New growth/roots", "Anywhere"], correct: 2 },
  { id: 308, topic: "Coloring & Lightening", question: "A toner is applied after lightening to:", options: ["Add more lift", "Neutralize unwanted warmth", "Darken the hair", "Add shine only"], correct: 1 },
  { id: 309, topic: "Coloring & Lightening", question: "Green tones in hair can be neutralized with:", options: ["Blue", "Yellow", "Red", "Purple"], correct: 2 },
  { id: 310, topic: "Coloring & Lightening", question: "Hydrogen peroxide activates hair color by:", options: ["Closing the cuticle", "Oxidizing melanin and the dye", "Adding protein", "Lowering pH"], correct: 1 },
  { id: 311, topic: "Coloring & Lightening", question: "Which of the following is a cool tone?", options: ["Orange", "Red-orange", "Ash/Blue", "Gold"], correct: 2 },
  { id: 312, topic: "Coloring & Lightening", question: "20 volume developer lifts hair approximately:", options: ["1 level", "1-2 levels", "3-4 levels", "5+ levels"], correct: 1 },
  { id: 313, topic: "Coloring & Lightening", question: "30 volume developer lifts hair approximately:", options: ["1 level", "2 levels", "3 levels", "5+ levels"], correct: 2 },
  { id: 314, topic: "Coloring & Lightening", question: "Which color is opposite violet on the color wheel?", options: ["Red", "Blue", "Yellow", "Green"], correct: 2 },
  { id: 315, topic: "Coloring & Lightening", question: "Which color is opposite orange on the color wheel?", options: ["Yellow", "Red", "Blue", "Green"], correct: 2 },
  { id: 316, topic: "Coloring & Lightening", question: "Balayage is a technique that:", options: ["Uses foils throughout", "Paints color freehand on the surface", "Applies color root to tip", "Only uses bleach"], correct: 1 },
  { id: 317, topic: "Coloring & Lightening", question: "Ombre color creates:", options: ["Even all-over color", "A gradual transition from dark to light", "Highlights throughout", "A solid block color"], correct: 1 },
  { id: 318, topic: "Coloring & Lightening", question: "Hair color levels range from:", options: ["1-5", "1-10", "1-20", "0-12"], correct: 1 },
  { id: 319, topic: "Coloring & Lightening", question: "Level 1 hair is:", options: ["Lightest blonde", "Medium brown", "Black", "Dark brown"], correct: 2 },
  { id: 320, topic: "Coloring & Lightening", question: "Level 10 hair is:", options: ["Black", "Medium brown", "Light blonde", "Lightest blonde/pale yellow"], correct: 3 },
  { id: 321, topic: "Coloring & Lightening", question: "Demi-permanent color:", options: ["Contains no developer", "Uses low-volume developer and deposits only", "Lifts and deposits", "Only lasts 1-2 washes"], correct: 1 },
  { id: 322, topic: "Coloring & Lightening", question: "Permanent color can:", options: ["Only deposit color", "Only lift color", "Both lift and deposit color", "Neither lift nor deposit"], correct: 2 },
  { id: 323, topic: "Coloring & Lightening", question: "The underlying pigment revealed when lifting dark hair is:", options: ["Ash tones", "Warm red/orange/yellow tones", "Cool violet tones", "Gray tones"], correct: 1 },
  { id: 324, topic: "Coloring & Lightening", question: "Which developer would you use just to deposit color with no lift?", options: ["40 volume", "30 volume", "20 volume", "10 volume"], correct: 3 },
  { id: 325, topic: "Coloring & Lightening", question: "Highlighting techniques include:", options: ["Balayage only", "Foiling, balayage, and cap highlighting", "Only foiling", "Only cap methods"], correct: 1 },
  { id: 326, topic: "Coloring & Lightening", question: "When applying color to previously colored hair, you should:", options: ["Apply root to end in one step", "Apply to new growth first, then pull through", "Apply to ends first", "Apply all at once"], correct: 1 },
  { id: 327, topic: "Coloring & Lightening", question: "Brassiness in colored hair refers to:", options: ["Cool unwanted tones", "Unwanted warm orange or yellow tones", "Gray tones appearing", "Color fading to neutral"], correct: 1 },
  { id: 328, topic: "Coloring & Lightening", question: "Purple/violet shampoos are used to:", options: ["Add warmth", "Neutralize yellow and brassy tones in blonde hair", "Darken blonde hair", "Remove all color"], correct: 1 },
  { id: 329, topic: "Coloring & Lightening", question: "Color correction services require:", options: ["One simple application", "Multiple steps, time, and professional assessment", "Only a toner", "Only a bleach wash"], correct: 1 },
  { id: 330, topic: "Coloring & Lightening", question: "Bleach is a:", options: ["Deposit-only product", "Lift-only product", "Both lift and deposit", "Neither"], correct: 1 },
  { id: 331, topic: "Coloring & Lightening", question: "On-scalp bleach formulas are:", options: ["Stronger than off-scalp", "Gentler than off-scalp formulas", "The same as off-scalp", "Not available"], correct: 1 },
  { id: 332, topic: "Coloring & Lightening", question: "A gloss treatment is used to:", options: ["Permanently change color", "Add shine and tone with semi-permanent color", "Bleach the hair", "Remove color"], correct: 1 },
  { id: 333, topic: "Coloring & Lightening", question: "A color retouch should be applied:", options: ["To all the hair every visit", "Only to the new growth area", "To the ends first", "Anywhere convenient"], correct: 1 },
  { id: 334, topic: "Coloring & Lightening", question: "The primary colors are:", options: ["Red, orange, yellow", "Red, yellow, blue", "Blue, green, yellow", "Red, blue, purple"], correct: 1 },
  { id: 335, topic: "Coloring & Lightening", question: "The secondary colors are:", options: ["Red, yellow, blue", "Orange, green, violet", "Brown, gray, black", "Pink, teal, coral"], correct: 1 },
  { id: 336, topic: "Coloring & Lightening", question: "Mixing complementary colors creates:", options: ["A brighter hue", "A neutral or brown tone", "A cooler tone", "A warmer tone"], correct: 1 },

  // ─── HAIRCUTTING & STYLING (32 questions) ────────────────────────────────
  { id: 337, topic: "Haircutting & Styling", question: "A stationary guide is used in which type of haircut?", options: ["Layers", "Blunt/one-length cut", "Graduated bob", "Razor cut"], correct: 1 },
  { id: 338, topic: "Haircutting & Styling", question: "A 90-degree elevation creates:", options: ["A one-length look", "A layered look", "A wedge", "A graduated bob"], correct: 1 },
  { id: 339, topic: "Haircutting & Styling", question: "Which tool removes bulk from thick hair?", options: ["Thinning shears", "Straight shears", "Razor", "Clippers"], correct: 0 },
  { id: 340, topic: "Haircutting & Styling", question: "Overdirection in haircutting means:", options: ["Cutting at 90 degrees", "Pulling hair away from its natural fall", "Cutting with the grain", "Zero elevation cutting"], correct: 1 },
  { id: 341, topic: "Haircutting & Styling", question: "A razor cut creates hair ends that are:", options: ["Blunt and thick", "Tapered and soft", "Uniform and even", "Choppy and textured"], correct: 1 },
  { id: 342, topic: "Haircutting & Styling", question: "Point cutting means:", options: ["Cutting straight across", "Cutting into the ends at an angle", "Cutting at zero elevation", "Removing bulk"], correct: 1 },
  { id: 343, topic: "Haircutting & Styling", question: "A graduated haircut builds weight at:", options: ["The top", "The perimeter/bottom", "The sides only", "The crown"], correct: 1 },
  { id: 344, topic: "Haircutting & Styling", question: "The purpose of backcombing is:", options: ["To smooth the hair", "To create volume and texture", "To detangle", "To add shine"], correct: 1 },
  { id: 345, topic: "Haircutting & Styling", question: "A blunt cut is also called:", options: ["A layered cut", "A one-length cut", "A graduated cut", "A razor cut"], correct: 1 },
  { id: 346, topic: "Haircutting & Styling", question: "Zero elevation cutting means:", options: ["Hair is pulled straight up", "Hair hangs at natural fall with no lift", "Hair is cut at 90 degrees", "Hair is cut at 45 degrees"], correct: 1 },
  { id: 347, topic: "Haircutting & Styling", question: "A 45-degree elevation creates:", options: ["A one-length cut", "A layered cut", "A graduated/wedge shape", "A uniform layer"], correct: 2 },
  { id: 348, topic: "Haircutting & Styling", question: "The traveling guide moves:", options: ["Stays in one place", "With each new section as you cut", "Only toward the face", "Only toward the nape"], correct: 1 },
  { id: 349, topic: "Haircutting & Styling", question: "Which is the correct way to hold shears when not cutting?", options: ["Blades open pointing outward", "Closed with blades facing away from client", "In the back pocket", "On the counter"], correct: 1 },
  { id: 350, topic: "Haircutting & Styling", question: "A diffuser attachment on a blow dryer:", options: ["Increases heat concentration", "Disperses airflow to reduce frizz and enhance curls", "Straightens hair faster", "Removes humidity"], correct: 1 },
  { id: 351, topic: "Haircutting & Styling", question: "Finger waving creates:", options: ["Defined curls", "S-shaped waves using fingers and a comb", "Straight styles", "Volume at the root"], correct: 1 },
  { id: 352, topic: "Haircutting & Styling", question: "A pin curl set creates:", options: ["Straight styles", "Soft curls and waves when dry", "Volume at the crown only", "Tight coils only"], correct: 1 },
  { id: 353, topic: "Haircutting & Styling", question: "Which setting lotion is used to hold a wet set?", options: ["Hair spray", "Pomade", "Mousse or setting lotion", "Oil serum"], correct: 2 },
  { id: 354, topic: "Haircutting & Styling", question: "Face shape analysis before a haircut is important to:", options: ["Determine color", "Choose a style that complements the client's features", "Decide on chemical services", "Determine hair texture"], correct: 1 },
  { id: 355, topic: "Haircutting & Styling", question: "An oval face shape is considered:", options: ["Least flattering", "The ideal shape — most styles suit it", "Requires the most careful styling", "Best for short cuts only"], correct: 1 },
  { id: 356, topic: "Haircutting & Styling", question: "Hair is held at elevation to:", options: ["Change the color", "Control where weight falls in the haircut", "Speed up the service", "Increase volume only"], correct: 1 },
  { id: 357, topic: "Haircutting & Styling", question: "Which product adds shine and controls frizz on dry hair?", options: ["Mousse", "Hairspray", "Serum or oil", "Volumizing spray"], correct: 2 },
  { id: 358, topic: "Haircutting & Styling", question: "A thermal iron is used to:", options: ["Remove color", "Create curls or waves using heat", "Relax hair chemically", "Cut hair"], correct: 1 },
  { id: 359, topic: "Haircutting & Styling", question: "The nape area is located:", options: ["At the crown", "At the hairline below the occipital bone", "At the temples", "At the front hairline"], correct: 1 },
  { id: 360, topic: "Haircutting & Styling", question: "Clipper over comb technique is used for:", options: ["Chemical services", "Precision cutting close to the head", "Blow drying", "Coloring"], correct: 1 },
  { id: 361, topic: "Haircutting & Styling", question: "Slithering is a technique that:", options: ["Removes bulk by sliding shears down the strand", "Blunts the ends", "Adds volume", "Creates waves"], correct: 0 },
  { id: 362, topic: "Haircutting & Styling", question: "An asymmetrical haircut is:", options: ["The same length on both sides", "Different lengths on each side", "All one length", "Only for short hair"], correct: 1 },
  { id: 363, topic: "Haircutting & Styling", question: "Flat irons should be used with:", options: ["Wet hair only", "A heat protectant on dry or nearly dry hair", "No product for best results", "Color-treated hair only"], correct: 1 },
  { id: 364, topic: "Haircutting & Styling", question: "The correct tension when cutting hair is:", options: ["As tight as possible", "Consistent and moderate", "No tension at all", "Varies randomly"], correct: 1 },
  { id: 365, topic: "Haircutting & Styling", question: "Cross-checking a haircut means:", options: ["Checking the color", "Checking the cut from a perpendicular angle to find any unevenness", "Measuring with a ruler", "Having another stylist cut it again"], correct: 1 },
  { id: 366, topic: "Haircutting & Styling", question: "Hair grows in which pattern from the crown?", options: ["Always clockwise", "In a circular cowlick pattern", "Straight down always", "Randomly with no pattern"], correct: 1 },
  { id: 367, topic: "Haircutting & Styling", question: "Which product is best for adding volume at the roots?", options: ["Serum", "Pomade", "Volumizing mousse or spray", "Finishing spray"], correct: 2 },
  { id: 368, topic: "Haircutting & Styling", question: "A French braid starts:", options: ["At the nape", "At the crown and incorporates hair as it progresses", "At the temples", "At the side part"], correct: 1 },

  // ─── ANATOMY & PHYSIOLOGY (32 questions) ─────────────────────────────────
  { id: 369, topic: "Anatomy & Physiology", question: "The muscle responsible for raising the eyebrows is:", options: ["Orbicularis oculi", "Frontalis", "Temporalis", "Masseter"], correct: 1 },
  { id: 370, topic: "Anatomy & Physiology", question: "Which system transports blood throughout the body?", options: ["Lymphatic", "Nervous", "Circulatory", "Digestive"], correct: 2 },
  { id: 371, topic: "Anatomy & Physiology", question: "The nerve that controls facial expression is the:", options: ["Trigeminal nerve", "Facial nerve", "Optic nerve", "Auditory nerve"], correct: 1 },
  { id: 372, topic: "Anatomy & Physiology", question: "Arteries carry blood:", options: ["Away from the heart", "To the heart", "To the lungs only", "Through capillaries"], correct: 0 },
  { id: 373, topic: "Anatomy & Physiology", question: "The largest organ of the body is the:", options: ["Liver", "Brain", "Skin", "Intestine"], correct: 2 },
  { id: 374, topic: "Anatomy & Physiology", question: "Which bone forms the lower jaw?", options: ["Maxilla", "Mandible", "Zygomatic", "Temporal"], correct: 1 },
  { id: 375, topic: "Anatomy & Physiology", question: "The occipital bone is located at the:", options: ["Front of the skull", "Side of the skull", "Back of the skull", "Top of the skull"], correct: 2 },
  { id: 376, topic: "Anatomy & Physiology", question: "Mitosis refers to:", options: ["Cell death", "Cell division", "Cell repair", "Cell mutation"], correct: 1 },
  { id: 377, topic: "Anatomy & Physiology", question: "The sebaceous glands produce:", options: ["Sweat", "Sebum (oil)", "Melanin", "Keratin"], correct: 1 },
  { id: 378, topic: "Anatomy & Physiology", question: "Veins carry blood:", options: ["Away from the heart", "To the heart", "Only to organs", "Only in the legs"], correct: 1 },
  { id: 379, topic: "Anatomy & Physiology", question: "The frontal bone forms:", options: ["The cheekbones", "The forehead", "The lower jaw", "The nose bridge only"], correct: 1 },
  { id: 380, topic: "Anatomy & Physiology", question: "The parietal bones form:", options: ["The cheeks", "The top and sides of the skull", "The forehead", "The chin"], correct: 1 },
  { id: 381, topic: "Anatomy & Physiology", question: "The temporal bones are located:", options: ["At the forehead", "At the sides of the skull above the ears", "At the back of the head", "At the jaw"], correct: 1 },
  { id: 382, topic: "Anatomy & Physiology", question: "The zygomatic bones form:", options: ["The jaw", "The cheekbones", "The forehead", "The nose"], correct: 1 },
  { id: 383, topic: "Anatomy & Physiology", question: "The masseter muscle is used for:", options: ["Raising eyebrows", "Chewing", "Smiling", "Closing eyes"], correct: 1 },
  { id: 384, topic: "Anatomy & Physiology", question: "The orbicularis oculi muscle controls:", options: ["The mouth", "Opening and closing the eye", "The nose", "The forehead"], correct: 1 },
  { id: 385, topic: "Anatomy & Physiology", question: "The orbicularis oris muscle controls:", options: ["The eyes", "The mouth and lips", "The nose", "The chin"], correct: 1 },
  { id: 386, topic: "Anatomy & Physiology", question: "The lymphatic system:", options: ["Pumps blood", "Drains excess fluid and supports immunity", "Produces red blood cells", "Controls hormone levels"], correct: 1 },
  { id: 387, topic: "Anatomy & Physiology", question: "Red blood cells carry:", options: ["White blood cells", "Oxygen throughout the body", "Nutrients only", "Antibodies"], correct: 1 },
  { id: 388, topic: "Anatomy & Physiology", question: "White blood cells function to:", options: ["Carry oxygen", "Fight infection and disease", "Clot blood", "Carry nutrients"], correct: 1 },
  { id: 389, topic: "Anatomy & Physiology", question: "Platelets are responsible for:", options: ["Fighting infection", "Blood clotting", "Carrying oxygen", "Producing hormones"], correct: 1 },
  { id: 390, topic: "Anatomy & Physiology", question: "The trigeminal nerve is the primary sensory nerve of the:", options: ["Neck", "Face", "Scalp only", "Arms"], correct: 1 },
  { id: 391, topic: "Anatomy & Physiology", question: "The zygomaticus muscle is used for:", options: ["Chewing", "Smiling", "Raising eyebrows", "Closing the jaw"], correct: 1 },
  { id: 392, topic: "Anatomy & Physiology", question: "The trapezius muscle is located in the:", options: ["Face", "Upper back and neck", "Arm", "Leg"], correct: 1 },
  { id: 393, topic: "Anatomy & Physiology", question: "Capillaries are:", options: ["Large arteries", "Tiny blood vessels where exchange occurs", "Veins returning blood", "Lymph nodes"], correct: 1 },
  { id: 394, topic: "Anatomy & Physiology", question: "The nervous system is divided into:", options: ["Skeletal and muscular", "Central and peripheral", "Voluntary and involuntary only", "Sensory only"], correct: 1 },
  { id: 395, topic: "Anatomy & Physiology", question: "The corrugator muscle causes:", options: ["Smiling", "Frowning/drawing eyebrows together", "Chewing", "Raising eyebrows"], correct: 1 },
  { id: 396, topic: "Anatomy & Physiology", question: "How many bones are in the human skull?", options: ["8", "14", "22", "30"], correct: 2 },
  { id: 397, topic: "Anatomy & Physiology", question: "The platysma muscle is located in the:", options: ["Forehead", "Cheek", "Neck", "Chin"], correct: 2 },
  { id: 398, topic: "Anatomy & Physiology", question: "The integumentary system includes:", options: ["Heart and blood vessels", "Skin, hair, and nails", "Muscles and bones", "Lungs and airways"], correct: 1 },
  { id: 399, topic: "Anatomy & Physiology", question: "The nasal bones form:", options: ["The cheeks", "The bridge of the nose", "The jaw", "The chin"], correct: 1 },
  { id: 400, topic: "Anatomy & Physiology", question: "Motor nerves control:", options: ["Sensation and feeling", "Muscle movement", "Blood flow", "Hormone production"], correct: 1 },
]
